import { Vehicle } from './types';

export const AUDI_MODELS: Vehicle[] = [
    // Audi A3
    {
        id: 'a3-sportback',
        brand: 'audi',
        name: 'A3 Sportback',
        category: 'Sportback',
        price: 32990000,
        image: '/images/audi/a3sportback.webp',
        isHybrid: false,
        isNew: false,
        slogan: 'Vanguardia en cada línea',
    },
    {
        id: 'a3-sedan',
        brand: 'audi',
        name: 'A3 Sedán',
        category: 'Sedán',
        price: 33990000,
        image: '/images/audi/a3-sedan.webp',
        isHybrid: false,
        isNew: false,
    },
    // Audi A5
    {
        id: 'nuevo-s5',
        brand: 'audi',
        name: 'Nuevo S5',
        category: 'Deportivo',
        price: 58990000,
        image: '/images/audi/nuevo-s5.webp',
        isHybrid: false,
        isNew: true,
    },
    {
        id: 'nuevo-a5',
        brand: 'audi',
        name: 'Nuevo A5',
        category: 'Sedán',
        price: 45990000,
        image: '/images/audi/nuevo-a5.webp',
        isHybrid: false,
        isNew: true,
    },
    // Audi A6 e-tron
    {
        id: 'a6-sportback-etron',
        brand: 'audi',
        name: 'A6 Sportback e-tron',
        category: 'Eléctrico',
        price: 85990000,
        image: '/images/audi/a6-etron.webp',
        isElectric: true,
        isNew: true,
    },
    // Audi Q3
    {
        id: 'q3',
        brand: 'audi',
        name: 'Q3',
        category: 'SUV',
        price: 37990000,
        image: '/images/audi/q3.webp',
        isHybrid: false,
        isNew: false,
    },
    {
        id: 'q3-sportback',
        brand: 'audi',
        name: 'Q3 Sportback',
        category: 'Sportback',
        price: 40990000,
        image: '/images/audi/q3-sportback.webp',
        isHybrid: false,
        isNew: false,
    },
    {
        id: 'nuevo-q3-suv',
        brand: 'audi',
        name: 'Nuevo Q3 SUV',
        category: 'SUV',
        price: 38990000,
        image: '/images/audi/q3-suv.webp',
        isHybrid: false,
        isNew: true,
    },
    {
        id: 'nuevo-q3-sportback',
        brand: 'audi',
        name: 'Nuevo Q3 Sportback',
        category: 'Sportback',
        price: 42990000,
        image: '/images/audi/nuevo-q3-sportback.webp',
        isHybrid: false,
        isNew: true,
    },
    // Audi Q4
    {
        id: 'q4-sportback-etron',
        brand: 'audi',
        name: 'Q4 Sportback e-tron',
        category: 'Eléctrico',
        price: 75990000,
        image: '/images/audi/q4-etron-sportback.webp',
        isElectric: true,
        isNew: true,
    },
    // Audi Q5
    {
        id: 'nuevo-q5-suv',
        brand: 'audi',
        name: 'Nuevo Q5 SUV',
        category: 'SUV',
        price: 52990000,
        image: '/images/audi/nuevo-suv-q5.webp',
        isHybrid: false,
        isNew: true,
    },
    {
        id: 'nuevo-sq5-suv',
        brand: 'audi',
        name: 'Nuevo SQ5 SUV',
        category: 'Deportivo',
        price: 68990000,
        image: '/images/audi/Nuevo-SQ5.webp',
        isHybrid: false,
        isNew: true,
    },
    {
        id: 'nuevo-q5-sportback',
        brand: 'audi',
        name: 'Nuevo Q5 Sportback',
        category: 'Sportback',
        price: 55990000,
        image: '/images/audi/nuevo-q5-sportback.webp',
        isHybrid: false,
        isNew: true,
    },
    // Audi Q6 e-tron
    {
        id: 'q6-etron',
        brand: 'audi',
        name: 'Q6 e-tron',
        category: 'Eléctrico',
        price: 92990000,
        image: '/images/audi/q6-etron.webp',
        isElectric: true,
        isNew: true,
    },
    {
        id: 'q6-sportback-etron',
        brand: 'audi',
        name: 'Q6 Sportback e-tron',
        category: 'Eléctrico',
        price: 95990000,
        image: '/images/audi/q6-sportback-etron.webp',
        isElectric: true,
        isNew: true,
    },
    // Audi Q7
    {
        id: 'q7',
        brand: 'audi',
        name: 'Q7',
        category: 'SUV',
        price: 72990000,
        image: '/images/audi/q7.webp',
        isHybrid: false,
        isNew: false,
    },
    {
        id: 'sq7',
        brand: 'audi',
        name: 'SQ7',
        category: 'Deportivo',
        price: 88990000,
        image: '/images/audi/sq7.webp',
        isHybrid: false,
        isNew: false,
    },
    // Audi Q8
    {
        id: 'q8',
        brand: 'audi',
        name: 'Q8',
        category: 'SUV',
        price: 82990000,
        image: '/images/audi/q8.webp',
        isHybrid: false,
        isNew: false,
    },
    {
        id: 'sq8',
        brand: 'audi',
        name: 'SQ8',
        category: 'Deportivo',
        price: 98990000,
        image: '/images/audi/sq8.webp',
        isHybrid: false,
        isNew: false,
    },
    {
        id: 'rs-q8-performance',
        brand: 'audi',
        name: 'RS Q8 performance',
        category: 'Deportivo',
        price: 145990000,
        image: '/images/audi/rs-q8-performance.webp',
        isHybrid: false,
        isNew: true,
    }
];
