import { Vehicle } from './types';

export const AUDI_MODELS: Vehicle[] = [
//     {
//         id: "a3-sed\u00e1n",
//         brand: "audi",
//         name: "A3 Sed\u00e1n",
//         category: "Híbrido, Sedán",
//         price: 39050000,
//         vehicleType: "liviano",
//         ivaIncluded: true,
//         isHybrid: true,
//         isElectric: false,
//         isNew: false,
//         versions: [
//             {
//             name: "A3 Sedan PI 35 TFSI S line MHEV",
//             motor: "1.5 TFSI",
//             fuel: "H\u00edbrido",
//             transmission: "DCT / DSG",
//             consumptionMixed: "6.0 l/100km",
//             power: "150 HP",
//             torque: "250 Nm",
//             traction: "4x2",
//             listPrice: 41990000,
//             brandBonus: 2290000,
//             financingBonus: 650000,
//             bonusPrice: 39050000,
//         },
//         ],
//         slogan: "Ilumina las calles.",
//         videoUrl: "CARACTER\u00cdSTICAS:",
//         features: [
//             {
//             title: "Dise\u00f1o Din\u00e1mico",
//             desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
//         },
//             {
//             title: "Conducci\u00f3n Eficiente",
//             desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
//         },
//             {
//             title: "Tecnolog\u00edas Innovadoras",
//             desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
//         },
//         ],
//     },
//     {
//         id: "a3-sportback",
//         brand: "audi",
//         name: "A3 Sportback",
//         category: "Hatchback, Híbrido",
//         price: 31450000,
//         vehicleType: "liviano",
//         ivaIncluded: true,
//         isHybrid: true,
//         isElectric: false,
//         isNew: false,
//         versions: [
//             {
//             name: "A3 Sportback PI 35 TFSI MHEV",
//             motor: "1.5 TFSI",
//             fuel: "H\u00edbrido",
//             transmission: "DCT / DSG",
//             consumptionMixed: "6.0 l/100km",
//             power: "150 HP",
//             torque: "250 Nm",
//             traction: "4x2",
//             listPrice: 37990000,
//             brandBonus: 4090000,
//             financingBonus: 2450000,
//             bonusPrice: 31450000,
//         },
//             {
//             name: "A3 Sportback PI 35 TFSI S line MHEV",
//             motor: "1.5 TFSI",
//             fuel: "H\u00edbrido",
//             transmission: "DCT / DSG",
//             consumptionMixed: "6.0 l/100km",
//             power: "150 HP",
//             torque: "250 Nm",
//             traction: "4x2",
//             listPrice: 42490000,
//             brandBonus: 2590000,
//             financingBonus: 2450000,
//             bonusPrice: 37450000,
//         },
//             {
//             name: "A3 Sportback PI 35 TFSI S line MHEV Special Edition",
//             motor: "1.5 TFSI",
//             fuel: "H\u00edbrido",
//             transmission: "DCT / DSG",
//             consumptionMixed: "6.0 l/100km",
//             power: "150 HP",
//             torque: "250 Nm",
//             traction: "4x2",
//             listPrice: 44490000,
//             brandBonus: 1990000,
//             financingBonus: 2450000,
//             bonusPrice: 40050000,
//         },
//         ],
//         slogan: "Emociones a flor de piel.",
//         videoUrl: "CARACTER\u00cdSTICAS:",
//         features: [
//             {
//             title: "Dise\u00f1o Din\u00e1mico",
//             desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
//         },
//             {
//             title: "Conducci\u00f3n Eficiente",
//             desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
//         },
//             {
//             title: "Tecnolog\u00edas Innovadoras",
//             desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
//         },
//         ],
//     },
//     {
//         id: "a6-sportback-e-tron",
//         brand: "audi",
//         name: "A6 Sportback e-tron",
//         category: "Eléctrico, Sedán",
//         price: 88750000,
//         vehicleType: "liviano",
//         ivaIncluded: true,
//         isHybrid: false,
//         isElectric: true,
//         isNew: false,
//         versions: [
//             {
//             name: "A6 Sportback e-tron S line",
//             motor: "Motor El\u00e9ctrico",
//             fuel: "El\u00e9ctrico",
//             transmission: "Autom\u00e1tica",
//             consumptionMixed: "16.0 kWh/100km",
//             electricRange: "750 km",
//             power: "285 HP",
//             torque: "565 Nm",
//             traction: "4x2",
//             listPrice: 89900000,
//             brandBonus: 0,
//             financingBonus: 1150000,
//             bonusPrice: 88750000,
//         },
//             {
//             name: "A6 Sportback e-tron performance S line",
//             motor: "Motor El\u00e9ctrico",
//             fuel: "El\u00e9ctrico",
//             transmission: "Autom\u00e1tica",
//             consumptionMixed: "16.0 kWh/100km",
//             electricRange: "716 km",
//             power: "367 HP",
//             torque: "610 Nm",
//             traction: "4x2",
//             listPrice: 104900000,
//             brandBonus: 0,
//             financingBonus: 1150000,
//             bonusPrice: 103750000,
//         },
//         ],
//         slogan: "100% Audi A6. 100% el\u00e9ctrico. This is Audi.",
//         videoUrl: "CARACTER\u00cdSTICAS:",
//         features: [
//             {
//             title: "Dise\u00f1o Din\u00e1mico",
//             desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
//         },
//             {
//             title: "Conducci\u00f3n Eficiente",
//             desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
//         },
//             {
//             title: "Tecnolog\u00edas Innovadoras",
//             desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
//         },
//         ],
//     },
//     {
//         id: "nuevo-a5",
//         brand: "audi",
//         name: "Nuevo A5",
//         category: "Sedán",
//         price: 50450000,
//         vehicleType: "liviano",
//         ivaIncluded: true,
//         isHybrid: false,
//         isElectric: false,
//         isNew: false,
//         versions: [
//             {
//             name: "New A5 TFSI",
//             motor: "2.0 TFSI",
//             fuel: "Gasolina",
//             transmission: "DCT / DSG",
//             consumptionMixed: "7.5 l/100km",
//             power: "204 HP",
//             torque: "370 Nm",
//             traction: "4x2",
//             listPrice: 53900000,
//             brandBonus: 1000000,
//             financingBonus: 2450000,
//             bonusPrice: 50450000,
//         },
//             {
//             name: "New A5 TFSI quattro S line",
//             motor: "2.0 TFSI",
//             fuel: "Gasolina",
//             transmission: "DCT / DSG",
//             consumptionMixed: "7.5 l/100km",
//             power: "204 HP",
//             torque: "370 Nm",
//             traction: "AWD",
//             listPrice: 59900000,
//             brandBonus: 1000000,
//             financingBonus: 2450000,
//             bonusPrice: 56450000,
//         },
//         ],
//         slogan: "Tu Audi A5, en cada detalle.",
//         videoUrl: "CARACTER\u00cdSTICAS:",
//         features: [
//             {
//             title: "Dise\u00f1o Din\u00e1mico",
//             desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
//         },
//             {
//             title: "Conducci\u00f3n Eficiente",
//             desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
//         },
//             {
//             title: "Tecnolog\u00edas Innovadoras",
//             desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
//         },
//         ],
//     },
//     {
//         id: "nuevo-q3",
//         brand: "audi",
//         name: "Nuevo Q3",
//         category: "SUV",
//         price: 42040000,
//         vehicleType: "liviano",
//         ivaIncluded: true,
//         isHybrid: false,
//         isElectric: false,
//         isNew: false,
//         versions: [
//             {
//             name: "New Q3 TFSI",
//             motor: "1.5 TFSI",
//             fuel: "Gasolina",
//             transmission: "DCT / DSG",
//             consumptionMixed: "8.1 l/100km",
//             power: "150 HP",
//             torque: "250 Nm",
//             traction: "4x2",
//             listPrice: 44990000,
//             brandBonus: 1000000,
//             financingBonus: 1950000,
//             bonusPrice: 42040000,
//         },
//         ],
//         slogan: "Talento integral.",
//         videoUrl: "CARACTER\u00cdSTICAS:",
//         features: [
//             {
//             title: "Dise\u00f1o Din\u00e1mico",
//             desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
//         },
//             {
//             title: "Conducci\u00f3n Eficiente",
//             desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
//         },
//             {
//             title: "Tecnolog\u00edas Innovadoras",
//             desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
//         },
//         ],
//     },
//     {
//         id: "nuevo-q3-sportback",
//         brand: "audi",
//         name: "Nuevo Q3 Sportback",
//         category: "SUV",
//         price: 44540000,
//         vehicleType: "liviano",
//         ivaIncluded: true,
//         isHybrid: false,
//         isElectric: false,
//         isNew: false,
//         versions: [
//             {
//             name: "New Q3 Sportback TFSI",
//             motor: "1.5 TFSI",
//             fuel: "Gasolina",
//             transmission: "DCT / DSG",
//             consumptionMixed: "7.1 l/100km",
//             power: "150 HP",
//             torque: "250 Nm",
//             traction: "4x2",
//             listPrice: 47490000,
//             brandBonus: 1000000,
//             financingBonus: 1950000,
//             bonusPrice: 44540000,
//         },
//         ],
//         slogan: "Extrovertido Coup\u00e9.",
//         videoUrl: "CARACTER\u00cdSTICAS:",
//         features: [
//             {
//             title: "Dise\u00f1o Din\u00e1mico",
//             desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
//         },
//             {
//             title: "Conducci\u00f3n Eficiente",
//             desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
//         },
//             {
//             title: "Tecnolog\u00edas Innovadoras",
//             desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
//         },
//         ],
//     },
//     {
//         id: "nuevo-q5",
//         brand: "audi",
//         name: "Nuevo Q5",
//         category: "SUV",
//         price: 53250000,
//         vehicleType: "liviano",
//         ivaIncluded: true,
//         isHybrid: false,
//         isElectric: false,
//         isNew: false,
//         versions: [
//             {
//             name: "Q5 45 TFSI S line",
//             motor: "2.0 TFSI",
//             fuel: "Gasolina",
//             transmission: "DCT / DSG",
//             consumptionMixed: "8.5 l/100km",
//             power: "249 HP",
//             torque: "370 Nm",
//             traction: "AWD",
//             listPrice: 74390000,
//             brandBonus: 14290000,
//             financingBonus: 1150000,
//             bonusPrice: 58950000,
//         },
//             {
//             name: "New Q5 TFSI quattro",
//             motor: "2.0 TFSI",
//             fuel: "Gasolina",
//             transmission: "DCT / DSG",
//             consumptionMixed: "8.5 l/100km",
//             power: "204 HP",
//             torque: "370 Nm",
//             traction: "AWD",
//             listPrice: 56700000,
//             brandBonus: 2000000,
//             financingBonus: 1450000,
//             bonusPrice: 53250000,
//         },
//             {
//             name: "New Q5 TFSI quattro S line",
//             motor: "2.0 TFSI",
//             fuel: "Gasolina",
//             transmission: "DCT / DSG",
//             consumptionMixed: "8.5 l/100km",
//             power: "204 HP",
//             torque: "370 Nm",
//             traction: "AWD",
//             listPrice: 63700000,
//             brandBonus: 2000000,
//             financingBonus: 1450000,
//             bonusPrice: 60250000,
//         },
//         ],
//         slogan: "Fuera de la vista. A\u00fan en la mente.",
//         videoUrl: "CARACTER\u00cdSTICAS:",
//         features: [
//             {
//             title: "Dise\u00f1o Din\u00e1mico",
//             desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
//         },
//             {
//             title: "Conducci\u00f3n Eficiente",
//             desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
//         },
//             {
//             title: "Tecnolog\u00edas Innovadoras",
//             desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
//         },
//         ],
//     },
//     {
//         id: "nuevo-q5-sportback",
//         brand: "audi",
//         name: "Nuevo Q5 Sportback",
//         category: "SUV",
//         price: 55750000,
//         vehicleType: "liviano",
//         ivaIncluded: true,
//         isHybrid: false,
//         isElectric: false,
//         isNew: false,
//         versions: [
//             {
//             name: "New Q5 Sportback TFSI quattro",
//             motor: "2.0 TFSI",
//             fuel: "Gasolina",
//             transmission: "DCT / DSG",
//             consumptionMixed: "8.2 l/100km",
//             power: "204 HP",
//             torque: "370 Nm",
//             traction: "AWD",
//             listPrice: 59200000,
//             brandBonus: 2000000,
//             financingBonus: 1450000,
//             bonusPrice: 55750000,
//         },
//             {
//             name: "New Q5 Sportback TFSI quattro S line",
//             motor: "2.0 TFSI",
//             fuel: "Gasolina",
//             transmission: "DCT / DSG",
//             consumptionMixed: "8.2 l/100km",
//             power: "204 HP",
//             torque: "370 Nm",
//             traction: "AWD",
//             listPrice: 66200000,
//             brandBonus: 2000000,
//             financingBonus: 1450000,
//             bonusPrice: 62750000,
//         },
//         ],
//         slogan: "Impresionante en cada momento.",
//         videoUrl: "CARACTER\u00cdSTICAS:",
//         features: [
//             {
//             title: "Dise\u00f1o Din\u00e1mico",
//             desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
//         },
//             {
//             title: "Conducci\u00f3n Eficiente",
//             desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
//         },
//             {
//             title: "Tecnolog\u00edas Innovadoras",
//             desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
//         },
//         ],
//     },
//     {
//         id: "nuevo-s5",
//         brand: "audi",
//         name: "Nuevo S5",
//         category: "Sedán",
//         price: 75450000,
//         vehicleType: "liviano",
//         ivaIncluded: true,
//         isHybrid: false,
//         isElectric: false,
//         isNew: false,
//         versions: [
//             {
//             name: "New S5 TFSI quattro",
//             motor: "3.0 TFSI",
//             fuel: "Gasolina",
//             transmission: "DCT / DSG",
//             consumptionMixed: "9.5 l/100km",
//             power: "367 HP",
//             torque: "500 Nm",
//             traction: "AWD",
//             listPrice: 78900000,
//             brandBonus: 1000000,
//             financingBonus: 2450000,
//             bonusPrice: 75450000,
//         },
//         ],
//         slogan: "Hechos que inspiran.",
//         videoUrl: "CARACTER\u00cdSTICAS:",
//         features: [
//             {
//             title: "Dise\u00f1o Din\u00e1mico",
//             desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
//         },
//             {
//             title: "Conducci\u00f3n Eficiente",
//             desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
//         },
//             {
//             title: "Tecnolog\u00edas Innovadoras",
//             desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
//         },
//         ],
//     },
//     {
//         id: "nuevo-sq5",
//         brand: "audi",
//         name: "Nuevo SQ5",
//         category: "SUV",
//         price: 80250000,
//         vehicleType: "liviano",
//         ivaIncluded: true,
//         isHybrid: false,
//         isElectric: false,
//         isNew: false,
//         versions: [
//             {
//             name: "New SQ5 TFSI quattro",
//             motor: "3.0 TFSI",
//             fuel: "Gasolina",
//             transmission: "DCT / DSG",
//             consumptionMixed: "10.0 l/100km",
//             power: "367 HP",
//             torque: "550 Nm",
//             traction: "AWD",
//             listPrice: 83700000,
//             brandBonus: 2000000,
//             financingBonus: 1450000,
//             bonusPrice: 80250000,
//         },
//         ],
//         slogan: "Un cumplido a la carretera.",
//         videoUrl: "CARACTER\u00cdSTICAS:",
//         features: [
//             {
//             title: "Dise\u00f1o Din\u00e1mico",
//             desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
//         },
//             {
//             title: "Conducci\u00f3n Eficiente",
//             desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
//         },
//             {
//             title: "Tecnolog\u00edas Innovadoras",
//             desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
//         },
//         ],
//     },
    {
        id: "q3",
        brand: "audi",
        name: "Q3",
        category: "SUV",
        price: 37450000,
        image: "/images/audi/Q3/Q3_14.jpg",
        vehicleType: "liviano",
        ivaIncluded: true,
        isHybrid: false,
        isElectric: false,
        isNew: false,
        versions: [
            {
            name: "Q3 35 TFSI",
            motor: "1.4 TFSI",
            fuel: "Gasolina",
            transmission: "DCT / DSG",
            consumptionMixed: "8.1 l/100km",
            power: "150 HP",
            torque: "250 Nm",
            traction: "4x2",
            listPrice: 42990000,
            brandBonus: 3390000,
            financingBonus: 2150000,
            bonusPrice: 37450000,
        },
            {
            name: "Q3 35 TFSI (MY26)",
            motor: "1.5 TFSI",
            fuel: "Gasolina",
            transmission: "DCT / DSG",
            consumptionMixed: "8.1 l/100km",
            power: "150 HP",
            torque: "250 Nm",
            traction: "4x2",
            listPrice: 43490000,
            brandBonus: 2390000,
            financingBonus: 2150000,
            bonusPrice: 38950000,
        },
        ],
        slogan: "Talento integral.",
        videoUrl: "CARACTER\u00cdSTICAS:",
        features: [
            {
            title: "Dise\u00f1o Din\u00e1mico",
            desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
        },
            {
            title: "Conducci\u00f3n Eficiente",
            desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
        },
            {
            title: "Tecnolog\u00edas Innovadoras",
            desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
        },
        ],
    },
//     {
//         id: "q3-sportback",
//         brand: "audi",
//         name: "Q3 Sportback",
//         category: "SUV",
//         price: 38950000,
//         vehicleType: "liviano",
//         ivaIncluded: true,
//         isHybrid: false,
//         isElectric: false,
//         isNew: false,
//         versions: [
//             {
//             name: "Q3 Sportback 35 TFSI (MY26)",
//             motor: "1.5 TFSI",
//             fuel: "Gasolina",
//             transmission: "DCT / DSG",
//             consumptionMixed: "7.1 l/100km",
//             power: "150 HP",
//             torque: "250 Nm",
//             traction: "4x2",
//             listPrice: 45490000,
//             brandBonus: 3690000,
//             financingBonus: 2850000,
//             bonusPrice: 38950000,
//         },
//             {
//             name: "Q3 Sportback 35 TFSI S line",
//             motor: "1.5 TFSI",
//             fuel: "Gasolina",
//             transmission: "DCT / DSG",
//             consumptionMixed: "7.1 l/100km",
//             power: "150 HP",
//             torque: "250 Nm",
//             traction: "4x2",
//             listPrice: 50990000,
//             brandBonus: 3190000,
//             financingBonus: 2850000,
//             bonusPrice: 44950000,
//         },
//         ],
//         slogan: "Extrovertido Coup\u00e9.",
//         videoUrl: "CARACTER\u00cdSTICAS:",
//         features: [
//             {
//             title: "Dise\u00f1o Din\u00e1mico",
//             desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
//         },
//             {
//             title: "Conducci\u00f3n Eficiente",
//             desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
//         },
//             {
//             title: "Tecnolog\u00edas Innovadoras",
//             desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
//         },
//         ],
//     },
//     {
//         id: "q4-sportback-e-tron",
//         brand: "audi",
//         name: "Q4 Sportback e-tron",
//         category: "Eléctrico, SUV",
//         price: 62950000,
//         vehicleType: "liviano",
//         ivaIncluded: true,
//         isHybrid: false,
//         isElectric: true,
//         isNew: false,
//         versions: [
//             {
//             name: "Q4 Sportback e-tron",
//             motor: "Motor El\u00e9ctrico",
//             fuel: "El\u00e9ctrico",
//             transmission: "Autom\u00e1tica",
//             consumptionMixed: "18.0 kWh/100km",
//             electricRange: "579 km",
//             power: "285 HP",
//             torque: "545 Nm",
//             traction: "4x2",
//             listPrice: 66990000,
//             brandBonus: 2890000,
//             financingBonus: 1150000,
//             bonusPrice: 62950000,
//         },
//             {
//             name: "Q4 Sportback e-tron S line",
//             motor: "Motor El\u00e9ctrico",
//             fuel: "El\u00e9ctrico",
//             transmission: "Autom\u00e1tica",
//             consumptionMixed: "18.0 kWh/100km",
//             electricRange: "579 km",
//             power: "285 HP",
//             torque: "545 Nm",
//             traction: "4x2",
//             listPrice: 71990000,
//             brandBonus: 3890000,
//             financingBonus: 1150000,
//             bonusPrice: 66950000,
//         },
//         ],
//         slogan: "Una nueva perspectiva.",
//         videoUrl: "CARACTER\u00cdSTICAS:",
//         features: [
//             {
//             title: "Dise\u00f1o Din\u00e1mico",
//             desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
//         },
//             {
//             title: "Conducci\u00f3n Eficiente",
//             desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
//         },
//             {
//             title: "Tecnolog\u00edas Innovadoras",
//             desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
//         },
//         ],
//     },
//     {
//         id: "q6-sportback-e-tron",
//         brand: "audi",
//         name: "Q6 Sportback e-tron",
//         category: "Eléctrico, SUV",
//         price: 86250000,
//         vehicleType: "liviano",
//         ivaIncluded: true,
//         isHybrid: false,
//         isElectric: true,
//         isNew: false,
//         versions: [
//             {
//             name: "Q6 Sportback e-tron 50 S line",
//             motor: "Motor El\u00e9ctrico",
//             fuel: "El\u00e9ctrico",
//             transmission: "Autom\u00e1tica",
//             consumptionMixed: "17.5 kWh/100km",
//             electricRange: "656 km",
//             power: "306 HP",
//             torque: "535 Nm",
//             traction: "4x2",
//             listPrice: 88490000,
//             brandBonus: 1090000,
//             financingBonus: 1150000,
//             bonusPrice: 86250000,
//         },
//             {
//             name: "Q6 Sportback e-tron 55 S line quattro",
//             motor: "Motores El\u00e9ctricos",
//             fuel: "El\u00e9ctrico",
//             transmission: "Autom\u00e1tica",
//             consumptionMixed: "18.5 kWh/100km",
//             electricRange: "657 km",
//             power: "388 HP",
//             torque: "650 Nm",
//             traction: "AWD",
//             listPrice: 95490000,
//             brandBonus: 1090000,
//             financingBonus: 1150000,
//             bonusPrice: 93250000,
//         },
//         ],
//         slogan: "Transforma la energ\u00eda en entusiasmo. This is Audi.",
//         videoUrl: "CARACTER\u00cdSTICAS:",
//         features: [
//             {
//             title: "Dise\u00f1o Din\u00e1mico",
//             desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
//         },
//             {
//             title: "Conducci\u00f3n Eficiente",
//             desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
//         },
//             {
//             title: "Tecnolog\u00edas Innovadoras",
//             desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
//         },
//         ],
//     },
//     {
//         id: "q6-e-tron",
//         brand: "audi",
//         name: "Q6 e-tron",
//         category: "Eléctrico, SUV",
//         price: 73750000,
//         vehicleType: "liviano",
//         ivaIncluded: true,
//         isHybrid: false,
//         isElectric: true,
//         isNew: false,
//         versions: [
//             {
//             name: "Q6 e-tron 45",
//             motor: "Motor El\u00e9ctrico",
//             fuel: "El\u00e9ctrico",
//             transmission: "Autom\u00e1tica",
//             consumptionMixed: "18.0 kWh/100km",
//             electricRange: "625 km",
//             power: "252 HP",
//             torque: "485 Nm",
//             traction: "4x2",
//             listPrice: 75990000,
//             brandBonus: 1090000,
//             financingBonus: 1150000,
//             bonusPrice: 73750000,
//         },
//             {
//             name: "Q6 e-tron 50 S line",
//             motor: "Motor El\u00e9ctrico",
//             fuel: "El\u00e9ctrico",
//             transmission: "Autom\u00e1tica",
//             consumptionMixed: "18.0 kWh/100km",
//             electricRange: "625 km",
//             power: "306 HP",
//             torque: "535 Nm",
//             traction: "4x2",
//             listPrice: 85990000,
//             brandBonus: 1090000,
//             financingBonus: 1150000,
//             bonusPrice: 83750000,
//         },
//             {
//             name: "Q6 e-tron 55 quattro S line",
//             motor: "Motores El\u00e9ctricos",
//             fuel: "El\u00e9ctrico",
//             transmission: "Autom\u00e1tica",
//             consumptionMixed: "19.0 kWh/100km",
//             electricRange: "640 km",
//             power: "388 HP",
//             torque: "650 Nm",
//             traction: "AWD",
//             listPrice: 92990000,
//             brandBonus: 1090000,
//             financingBonus: 1150000,
//             bonusPrice: 90750000,
//         },
//         ],
//         slogan: "El\u00e9ctrico y con incre\u00edbles detalles.",
//         videoUrl: "CARACTER\u00cdSTICAS:",
//         features: [
//             {
//             title: "Dise\u00f1o Din\u00e1mico",
//             desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
//         },
//             {
//             title: "Conducci\u00f3n Eficiente",
//             desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
//         },
//             {
//             title: "Tecnolog\u00edas Innovadoras",
//             desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
//         },
//         ],
//     },
    {
        id: "q7",
        brand: "audi",
        name: "Q7",
        category: "SUV",
        price: 75950000,
        image: "/images/audi/Q7/Q7_13.jpg",
        vehicleType: "liviano",
        ivaIncluded: true,
        isHybrid: false,
        isElectric: false,
        isNew: false,
        versions: [
            {
            name: "Q7 PI 55 TFSI (7P)",
            motor: "3.0 TFSI",
            fuel: "Gasolina",
            transmission: "Autom\u00e1tica",
            consumptionMixed: "9.8 l/100km",
            power: "340 HP",
            torque: "500 Nm",
            traction: "AWD",
            seats: 7,
            listPrice: 85600000,
            brandBonus: 6700000,
            financingBonus: 2950000,
            bonusPrice: 75950000,
        },
            {
            name: "Q7 PI 55 TFSI S line (7P)",
            motor: "3.0 TFSI",
            fuel: "Gasolina",
            transmission: "Autom\u00e1tica",
            consumptionMixed: "9.8 l/100km",
            power: "340 HP",
            torque: "500 Nm",
            traction: "AWD",
            seats: 7,
            listPrice: 104600000,
            brandBonus: 7700000,
            financingBonus: 2950000,
            bonusPrice: 93950000,
        },
            {
            name: "Q7 PI 55 TFSI (7P) - MY26",
            motor: "3.0 TFSI",
            fuel: "Gasolina",
            transmission: "Autom\u00e1tica",
            consumptionMixed: "9.8 l/100km",
            power: "340 HP",
            torque: "500 Nm",
            traction: "AWD",
            seats: 7,
            listPrice: 90600000,
            brandBonus: 6700000,
            financingBonus: 2950000,
            bonusPrice: 80950000,
        },
            {
            name: "Q7 PI 55 TFSI S line (7P) - MY26",
            motor: "3.0 TFSI",
            fuel: "Gasolina",
            transmission: "Autom\u00e1tica",
            consumptionMixed: "9.8 l/100km",
            power: "340 HP",
            torque: "500 Nm",
            traction: "AWD",
            seats: 7,
            listPrice: 109600000,
            brandBonus: 7700000,
            financingBonus: 2950000,
            bonusPrice: 98950000,
        },
        ],
        slogan: "Todo terreno con car\u00e1cter.",
        videoUrl: "CARACTER\u00cdSTICAS:",
        features: [
            {
            title: "Dise\u00f1o Din\u00e1mico",
            desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
        },
            {
            title: "Conducci\u00f3n Eficiente",
            desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
        },
            {
            title: "Tecnolog\u00edas Innovadoras",
            desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
        },
        ],
    },
    {
        id: "q8",
        brand: "audi",
        name: "Q8",
        category: "SUV",
        price: 82450000,
        image: "/images/audi/Q8/Q8_09.jpg",
        vehicleType: "liviano",
        ivaIncluded: true,
        isHybrid: false,
        isElectric: false,
        isNew: false,
        versions: [
            {
            name: "Q8 55 TFSI",
            motor: "3.0 TFSI",
            fuel: "Gasolina",
            transmission: "Autom\u00e1tica",
            consumptionMixed: "10.5 l/100km",
            power: "340 HP",
            torque: "500 Nm",
            traction: "AWD",
            listPrice: 92600000,
            brandBonus: 7200000,
            financingBonus: 2950000,
            bonusPrice: 82450000,
        },
            {
            name: "Q8 55 TFSI S line",
            motor: "3.0 TFSI",
            fuel: "Gasolina",
            transmission: "Autom\u00e1tica",
            consumptionMixed: "10.5 l/100km",
            power: "340 HP",
            torque: "500 Nm",
            traction: "AWD",
            listPrice: 105600000,
            brandBonus: 9200000,
            financingBonus: 2950000,
            bonusPrice: 93450000,
        },
            {
            name: "Q8 55 TFSI - MY26",
            motor: "3.0 TFSI",
            fuel: "Gasolina",
            transmission: "Autom\u00e1tica",
            consumptionMixed: "10.5 l/100km",
            power: "340 HP",
            torque: "500 Nm",
            traction: "AWD",
            listPrice: 97600000,
            brandBonus: 7200000,
            financingBonus: 2950000,
            bonusPrice: 87450000,
        },
            {
            name: "Q8 55 TFSI S line - MY26",
            motor: "3.0 TFSI",
            fuel: "Gasolina",
            transmission: "Autom\u00e1tica",
            consumptionMixed: "10.5 l/100km",
            power: "340 HP",
            torque: "500 Nm",
            traction: "AWD",
            listPrice: 110600000,
            brandBonus: 9200000,
            financingBonus: 2950000,
            bonusPrice: 98450000,
        },
        ],
        slogan: "Un car\u00e1cter fuerte de forma elegante.",
        videoUrl: "CARACTER\u00cdSTICAS:",
        features: [
            {
            title: "Dise\u00f1o Din\u00e1mico",
            desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
        },
            {
            title: "Conducci\u00f3n Eficiente",
            desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
        },
            {
            title: "Tecnolog\u00edas Innovadoras",
            desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
        },
        ],
    },
//     {
//         id: "rs-q8-performance",
//         brand: "audi",
//         name: "RS Q8 performance",
//         category: "SUV",
//         price: 198250000,
//         vehicleType: "liviano",
//         ivaIncluded: true,
//         isHybrid: false,
//         isElectric: false,
//         isNew: false,
//         versions: [
//             {
//             name: "RSQ8 Performance",
//             motor: "4.0 TFSI",
//             fuel: "Gasolina",
//             transmission: "Autom\u00e1tica",
//             consumptionMixed: "13.5 l/100km",
//             power: "640 HP",
//             torque: "850 Nm",
//             traction: "AWD",
//             listPrice: 199400000,
//             brandBonus: 0,
//             financingBonus: 1150000,
//             bonusPrice: 198250000,
//         },
//         ],
//         slogan: "El rendimiento se une a la elegancia.",
//         videoUrl: "CARACTER\u00cdSTICAS:",
//         features: [
//             {
//             title: "Dise\u00f1o Din\u00e1mico",
//             desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
//         },
//             {
//             title: "Conducci\u00f3n Eficiente",
//             desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
//         },
//             {
//             title: "Tecnolog\u00edas Innovadoras",
//             desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
//         },
//         ],
//     },
    {
        id: "sq7",
        brand: "audi",
        name: "SQ7",
        category: "SUV",
        price: 124450000,
        image: "/images/audi/SQ7/SQ7_19.jpg",
        vehicleType: "liviano",
        ivaIncluded: true,
        isHybrid: false,
        isElectric: false,
        isNew: false,
        versions: [
            {
            name: "SQ7 (7P)",
            motor: "4.0 TFSI",
            fuel: "Gasolina",
            transmission: "Autom\u00e1tica",
            consumptionMixed: "11.8 l/100km",
            power: "507 HP",
            torque: "770 Nm",
            traction: "AWD",
            seats: 7,
            listPrice: 134600000,
            brandBonus: 7200000,
            financingBonus: 2950000,
            bonusPrice: 124450000,
        },
        ],
        slogan: "Rendimiento con personalidad.",
        videoUrl: "CARACTER\u00cdSTICAS:",
        features: [
            {
            title: "Dise\u00f1o Din\u00e1mico",
            desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
        },
            {
            title: "Conducci\u00f3n Eficiente",
            desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
        },
            {
            title: "Tecnolog\u00edas Innovadoras",
            desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
        },
        ],
    },
    {
        id: "sq8",
        brand: "audi",
        name: "SQ8",
        category: "SUV",
        price: 127450000,
        image: "/images/audi/SQ8/SQ8_14.jpg",
        vehicleType: "liviano",
        ivaIncluded: true,
        isHybrid: false,
        isElectric: false,
        isNew: false,
        versions: [
            {
            name: "SQ8",
            motor: "4.0 TFSI",
            fuel: "Gasolina",
            transmission: "Autom\u00e1tica",
            consumptionMixed: "12.2 l/100km",
            power: "507 HP",
            torque: "770 Nm",
            traction: "AWD",
            listPrice: 137600000,
            brandBonus: 7200000,
            financingBonus: 2950000,
            bonusPrice: 127450000,
        },
        ],
        slogan: "Potente rendimiento.",
        videoUrl: "CARACTER\u00cdSTICAS:",
        features: [
            {
            title: "Dise\u00f1o Din\u00e1mico",
            desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
        },
            {
            title: "Conducci\u00f3n Eficiente",
            desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
        },
            {
            title: "Tecnolog\u00edas Innovadoras",
            desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
        },
        ],
    },
    {
        id: "a3-sportback",
        brand: "audi",
        name: "A3 Sportback",
        category: "Hatchback, Híbrido",
        price: 31450000,
        image: "/images/audi/a3-sportback/A3_Sportback_09.jpg",
        vehicleType: "liviano",
        ivaIncluded: true,
        isHybrid: true,
        isElectric: false,
        isNew: false,
        versions: [
            {
            name: "A3 Sportback PI 35 TFSI MHEV",
            motor: "1.5 TFSI",
            fuel: "H\u00edbrido",
            transmission: "DCT / DSG",
            consumptionMixed: "6.0 l/100km",
            power: "150 HP",
            torque: "250 Nm",
            traction: "4x2",
            listPrice: 37990000,
            brandBonus: 4090000,
            financingBonus: 2450000,
            bonusPrice: 31450000,
        },
            {
            name: "A3 Sportback PI 35 TFSI S line MHEV",
            motor: "1.5 TFSI",
            fuel: "H\u00edbrido",
            transmission: "DCT / DSG",
            consumptionMixed: "6.0 l/100km",
            power: "150 HP",
            torque: "250 Nm",
            traction: "4x2",
            listPrice: 42490000,
            brandBonus: 2590000,
            financingBonus: 2450000,
            bonusPrice: 37450000,
        },
            {
            name: "A3 Sportback PI 35 TFSI S line MHEV Special Edition",
            motor: "1.5 TFSI",
            fuel: "H\u00edbrido",
            transmission: "DCT / DSG",
            consumptionMixed: "6.0 l/100km",
            power: "150 HP",
            torque: "250 Nm",
            traction: "4x2",
            listPrice: 44490000,
            brandBonus: 1990000,
            financingBonus: 2450000,
            bonusPrice: 40050000,
        },
        ],
        slogan: "Emociones a flor de piel.",
        videoUrl: "CARACTER\u00cdSTICAS:",
        features: [
            {
            title: "Dise\u00f1o Din\u00e1mico",
            desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
        },
            {
            title: "Conducci\u00f3n Eficiente",
            desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
        },
            {
            title: "Tecnolog\u00edas Innovadoras",
            desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
        },
        ],
    },
];
