import { Vehicle } from './types';

export const BMW_MOTORRAD_MODELS: Vehicle[] = [
    {
        id: "c-400-gt",
        brand: "bmw-motorrad",
        name: "C 400 GT",
        category: "Urban Mobility",
        price: 13490000,
        image: "/images/bmw-motorrad/C 400 GT/C_400_GT.png",
        vehicleType: "moto",
        ivaIncluded: true,
        isHybrid: false,
        isElectric: false,
        isNew: false,
        versions: [
            {
                name: "C 400 GT",
                motor: "350 cm3",
                fuel: "Gasolina",
                transmission: "CVT",
                consumptionMixed: "8.6 l/100km",
                power: "34 HP",
                traction: "4x2",
                listPrice: 14090000,
                brandBonus: 600000,
                financingBonus: 0,
                bonusPrice: 13490000,
            },
        ],
        slogan: "Make Life a Ride",
        videoUrl: "CARACTER\u00cdSTICAS:",
        features: [
            {
                title: "Dise\u00f1o Din\u00e1mico",
                desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
                image: "/images/bmw-motorrad/C 400 GT/caracteristicas/conexion.avif",
            },
            {
                title: "Conducci\u00f3n Eficiente",
                desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
                image: "/images/bmw-motorrad/C 400 GT/caracteristicas/espacio.avif",
            },
            {
                title: "Tecnolog\u00edas Innovadoras",
                desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
                image: "/images/bmw-motorrad/C 400 GT/caracteristicas/parabrisas.avif",
            },
        ],
        gallery: [
            "/images/bmw-motorrad/C 400 GT/galeria/2.avif",
            "/images/bmw-motorrad/C 400 GT/galeria/3.avif",
            "/images/bmw-motorrad/C 400 GT/galeria/4.avif",
        ],
        desktopBanner: "/images/bmw-motorrad/C 400 GT/banner/banner.avif",
    },
    {
        id: "c-400-x",
        brand: "bmw-motorrad",
        name: "C 400 X",
        category: "Urban Mobility",
        price: 11490000,
        image: "/images/bmw-motorrad/C 400 X/min.avif",
        vehicleType: "moto",
        ivaIncluded: true,
        isHybrid: false,
        isElectric: false,
        isNew: false,
        versions: [
            {
                name: "C 400 X",
                motor: "350 cm3",
                fuel: "Gasolina",
                transmission: "CVT",
                consumptionMixed: "8.8 l/100km",
                power: "34 HP",
                traction: "4X2",
                listPrice: 11990000,
                brandBonus: 500000,
                financingBonus: 0,
                bonusPrice: 11490000,
            },
        ],
        slogan: "Make Life a Ride",
        videoUrl: "CARACTER\u00cdSTICAS:",
        features: [
            {
                title: "Dise\u00f1o Din\u00e1mico",
                desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
                image: "/images/bmw-motorrad/C 400 X/caracteristicas/conexion-inteligente.avif",
            },
            {
                title: "Conducci\u00f3n Eficiente",
                desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
                image: "/images/bmw-motorrad/C 400 X/caracteristicas/diseno-fronta.avif",
            },
            {
                title: "Tecnolog\u00edas Innovadoras",
                desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
                image: "/images/bmw-motorrad/C 400 X/caracteristicas/connect-ride.avif",
            },
        ],
        gallery: [
            "/images/bmw-motorrad/C 400 X/galeria/1.avif",
            "/images/bmw-motorrad/C 400 X/galeria/2.avif",
            "/images/bmw-motorrad/C 400 X/galeria/3.png",
            "/images/bmw-motorrad/C 400 X/galeria/4.avif",
        ],
        desktopBanner: "/images/bmw-motorrad/C 400 X/banner/nsc-c400x-P0NA2-multiimage-1920x1200.jpg.asset.1732605111567.jpg.16_10_1920.avif",
    },
    {
        id: "ce-02",
        brand: "bmw-motorrad",
        name: "CE 02",
        category: "Eléctricos, Urban Mobility",
        price: 10490000,
        image: "/images/bmw-motorrad/CE 02/min-ce02.avif",
        vehicleType: "moto",
        ivaIncluded: true,
        isHybrid: false,
        isElectric: true,
        isNew: false,
        versions: [
            {
                name: "CE 02",
                motor: "El\u00e9ctrico S\u00edncrono",
                fuel: "El\u00e9ctrico",
                transmission: "Mec\u00e1nica",
                electricRange: "90 km",
                power: "15 HP",
                traction: "4x2",
                listPrice: 12490000,
                brandBonus: 2000000,
                financingBonus: 0,
                bonusPrice: 10490000,
            },
        ],
        slogan: "Make Life a Ride",
        videoUrl: "CARACTER\u00cdSTICAS:",
        features: [
            {
                title: "Dise\u00f1o Din\u00e1mico",
                desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
                image: "/images/bmw-motorrad/CE 02/caracteristicas/soporte.avif",
            },
            {
                title: "Conducci\u00f3n Eficiente",
                desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
                image: "/images/bmw-motorrad/CE 02/caracteristicas/asiento-pro.avif",
            },
            {
                title: "Tecnolog\u00edas Innovadoras",
                desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
                image: "/images/bmw-motorrad/CE 02/caracteristicas/experiencia-conducion.avif",
            },
        ],
        gallery: [
            "/images/bmw-motorrad/CE 02/galeria/1.avif",
            "/images/bmw-motorrad/CE 02/galeria/2.avif",
            "/images/bmw-motorrad/CE 02/galeria/3.jpg",
            "/images/bmw-motorrad/CE 02/galeria/4.jpg",
        ],
        desktopBanner: "/images/bmw-motorrad/CE 02/banner/banner.jpg",
    },
    {
        id: "ce-04",
        brand: "bmw-motorrad",
        name: "CE 04",
        category: "Eléctricos, Urban Mobility",
        price: 15990000,
        image: "/images/bmw-motorrad/CE 04/min-ce04.png",
        vehicleType: "moto",
        ivaIncluded: true,
        isHybrid: false,
        isElectric: true,
        isNew: false,
        versions: [
            {
                name: "CE 04",
                motor: "El\u00e9ctrico S\u00edncrono",
                fuel: "El\u00e9ctrico",
                transmission: "Mec\u00e1nica",
                electricRange: "130 km",
                power: "42 HP",
                traction: "4x2",
                listPrice: 16290000,
                brandBonus: 300000,
                financingBonus: 0,
                bonusPrice: 15990000,
            },
        ],
        slogan: "Make Life a Ride",
        videoUrl: "CARACTER\u00cdSTICAS:",
        features: [
            {
                title: "Dise\u00f1o Din\u00e1mico",
                desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
                image: "/images/bmw-motorrad/CE 04/caracteristicas/electric-drive.avif",
            },
            {
                title: "Conducci\u00f3n Eficiente",
                desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
                image: "/images/bmw-motorrad/CE 04/caracteristicas/1.avif",
            },
            {
                title: "Tecnolog\u00edas Innovadoras",
                desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
                image: "/images/bmw-motorrad/CE 04/caracteristicas/practical-storage.avif",
            },
        ],
        gallery: [
            "/images/bmw-motorrad/CE 04/galeria/03_Foto_Hero_1440x665.jpg",
            "/images/bmw-motorrad/CE 04/galeria/05_Componente_536x302.jpg",
            "/images/bmw-motorrad/CE 04/galeria/07_Componente_537x303.jpg",
            "/images/bmw-motorrad/CE 04/galeria/1.jpg",
            "/images/bmw-motorrad/CE 04/galeria/2.jpg",
            "/images/bmw-motorrad/CE 04/galeria/3.avif",
            "/images/bmw-motorrad/CE 04/galeria/4.avif",
        ],
        desktopBanner: "/images/bmw-motorrad/CE 04/banner/03_Foto_Hero_1440x665.avif",
    },
    {
        id: "f-800-gs",
        brand: "bmw-motorrad",
        name: "F 800 GS",
        category: "Adventure",
        price: 13490000,
        image: "/images/bmw-motorrad/F 800 GS/min.webp",
        vehicleType: "moto",
        ivaIncluded: true,
        isHybrid: false,
        isElectric: false,
        isNew: false,
        versions: [
            {
                name: "F 800 GS",
                motor: "895 cm3",
                fuel: "Gasolina",
                transmission: "Mec\u00e1nica",
                power: "87 HP",
                torque: "91 Nm",
                traction: "4x2",
                listPrice: 14990000,
                brandBonus: 1500000,
                financingBonus: 0,
                bonusPrice: 13490000,
            },
        ],
        slogan: "Make Life a Ride",
        videoUrl: "CARACTER\u00cdSTICAS:",
        features: [
            {
                title: "Dise\u00f1o Din\u00e1mico",
                desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
                image: "/images/bmw-motorrad/F 800 GS/caracteristicas/usb.avif",
            },
            {
                title: "Conducci\u00f3n Eficiente",
                desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
                image: "/images/bmw-motorrad/F 800 GS/caracteristicas/abs.avif",
            },
            {
                title: "Tecnolog\u00edas Innovadoras",
                desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
                image: "/images/bmw-motorrad/F 800 GS/caracteristicas/estribos.avif",
            },
        ],
        gallery: [
            "/images/bmw-motorrad/F 800 GS/galeria/1.avif",
            "/images/bmw-motorrad/F 800 GS/galeria/2.avif",
            "/images/bmw-motorrad/F 800 GS/galeria/3.avif",
            "/images/bmw-motorrad/F 800 GS/galeria/4.avif",
            "/images/bmw-motorrad/F 800 GS/galeria/5.avif",
            "/images/bmw-motorrad/F 800 GS/galeria/6.avif",
            "/images/bmw-motorrad/F 800 GS/galeria/7.avif",
        ],
        desktopBanner: "/images/bmw-motorrad/F 800 GS/banner/banner.avif",
    },
    {
        id: "f-900-gs",
        brand: "bmw-motorrad",
        name: "\"F 900 GS\"",
        category: "Adventure",
        price: 0,
        image: "/images/bmw-motorrad/F 900 GS/min.webp",
        vehicleType: "moto",
        ivaIncluded: true,
        isHybrid: false,
        isElectric: false,
        isNew: false,
        versions: [
            {
                name: "- version: \"BMW F 900 GS I\"",
                motor: "\"895 cm3 (Bicil\u00edndrico)\"",
                fuel: "-",
                transmission: "-",
                power: "105",
                traction: "\"Cadena M Endurance\"",
                listPrice: 0,
                brandBonus: 0,
                financingBonus: 0,
                bonusPrice: 0,
            },
            {
                name: "peso_vacio: \"Peso reducido (Uso todoterreno)\"",
                fuel: "-",
                transmission: "-",
                traction: "-",
                listPrice: 0,
                brandBonus: 0,
                financingBonus: 0,
                bonusPrice: 0,
            },
            {
                name: "consumo_wmtc: \"4.4 l / 100km\"",
                fuel: "-",
                transmission: "-",
                traction: "-",
                listPrice: 0,
                brandBonus: 0,
                financingBonus: 0,
                bonusPrice: 0,
            },
            {
                name: "equipamiento_clave:",
                fuel: "-",
                transmission: "-",
                traction: "-",
                listPrice: 0,
                brandBonus: 0,
                financingBonus: 0,
                bonusPrice: 0,
            },
            {
                name: "- \"Paquete Enduro Pro compatible\"",
                fuel: "-",
                transmission: "-",
                traction: "-",
                listPrice: 0,
                brandBonus: 0,
                financingBonus: 0,
                bonusPrice: 0,
            },
            {
                name: "- \"Horquilla Showa 45mm\"",
                fuel: "-",
                transmission: "-",
                traction: "-",
                listPrice: 0,
                brandBonus: 0,
                financingBonus: 0,
                bonusPrice: 0,
            },
            {
                name: "- \"Bater\u00eda 12V / 9Ah\"",
                fuel: "-",
                transmission: "-",
                traction: "-",
                listPrice: 0,
                brandBonus: 0,
                financingBonus: 0,
                bonusPrice: 0,
            },
            {
                name: "- \"Iluminaci\u00f3n LED\"",
                fuel: "-",
                transmission: "-",
                traction: "-",
                listPrice: 0,
                brandBonus: 0,
                financingBonus: 0,
                bonusPrice: 0,
            },
            {
                name: "precio_lista: 17990000",
                fuel: "-",
                transmission: "-",
                traction: "-",
                listPrice: 0,
                brandBonus: 0,
                financingBonus: 0,
                bonusPrice: 0,
            },
            {
                name: "bono_todo_medio_pago: 1500000",
                fuel: "-",
                transmission: "-",
                traction: "-",
                listPrice: 0,
                brandBonus: 0,
                financingBonus: 0,
                bonusPrice: 0,
            },
            {
                name: "bono_autofin: 0",
                fuel: "-",
                transmission: "-",
                traction: "-",
                listPrice: 0,
                brandBonus: 0,
                financingBonus: 0,
                bonusPrice: 0,
            },
            {
                name: "precio_final_con_bono: 16490000",
                fuel: "-",
                transmission: "-",
                traction: "-",
                listPrice: 0,
                brandBonus: 0,
                financingBonus: 0,
                bonusPrice: 0,
            },
            {
                name: "3. Condiciones y LegalesVigencia: Hasta el 28 de febrero de 2026 o hasta agotar stock (09 unidades).Simulaci\u00f3n Cr\u00e9dito Inteligente: 50% de pie ($8.245.000), 24 cuotas de $187.990 y cuota n\u00b0 25 (VFMG) de $8.245.000. CAE 26,4%. Costo total del cr\u00e9dito: $12.756.760.Sujeto a verificaci\u00f3n de antecedentes financieros por la entidad otorgante (Sociedad de Cr\u00e9ditos Automotrices S.A.). No incluye impuesto verde ni fletes. No v\u00e1lido para Zona Franca.",
                fuel: "-",
                transmission: "-",
                traction: "-",
                listPrice: 0,
                brandBonus: 0,
                financingBonus: 0,
                bonusPrice: 0,
            },
        ],
        gallery: [
            "/images/bmw-motorrad/F 900 GS/galeria/1.avif",
            "/images/bmw-motorrad/F 900 GS/galeria/2.avif",
            "/images/bmw-motorrad/F 900 GS/galeria/3.avif",
            "/images/bmw-motorrad/F 900 GS/galeria/4.jpg",
            "/images/bmw-motorrad/F 900 GS/galeria/5.avif",
            "/images/bmw-motorrad/F 900 GS/galeria/5.jpg",
            "/images/bmw-motorrad/F 900 GS/galeria/6.avif",
            "/images/bmw-motorrad/F 900 GS/galeria/7.avif",
            "/images/bmw-motorrad/F 900 GS/galeria/8.avif",
        ],
        desktopBanner: "/images/bmw-motorrad/F 900 GS/banner/banner.avif",
    },
    {
        id: "f-900-gs-adventure",
        brand: "bmw-motorrad",
        name: "F 900 GS Adventure",
        category: "Adventure",
        price: 20290000,
        image: "/images/bmw-motorrad/F 900 GS Adventure/min.webp",
        vehicleType: "moto",
        ivaIncluded: true,
        isHybrid: false,
        isElectric: false,
        isNew: false,
        versions: [
            {
                name: "F 900 GS Adventure",
                motor: "895 cm3",
                fuel: "Gasolina",
                transmission: "Mec\u00e1nica",
                power: "105 HP",
                torque: "93 Nm",
                traction: "4x2",
                listPrice: 21790000,
                brandBonus: 1500000,
                financingBonus: 0,
                bonusPrice: 20290000,
            },
        ],
        slogan: "Make Life a Ride",
        videoUrl: "CARACTER\u00cdSTICAS:",
        features: [
            {
                title: "Dise\u00f1o Din\u00e1mico",
                desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
                image: "/images/bmw-motorrad/F 900 GS Adventure/caracteristicas/proteccion.avif",
            },
            {
                title: "Conducci\u00f3n Eficiente",
                desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
                image: "/images/bmw-motorrad/F 900 GS Adventure/caracteristicas/asiento.avif",
            },
            {
                title: "Tecnolog\u00edas Innovadoras",
                desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
                image: "/images/bmw-motorrad/F 900 GS Adventure/caracteristicas/dynamic-esa.avif",
            },
        ],
        gallery: [
            "/images/bmw-motorrad/F 900 GS Adventure/galeria/nsc-f900gs-adventure-P0N52-animatedfacts-desktop.jpg.asset.1692092310552.avif",
            "/images/bmw-motorrad/F 900 GS Adventure/galeria/nsc-f900gs-adventure-P0N52-sound-desktop.jpg.asset.1692265020094.avif",
            "/images/bmw-motorrad/F 900 GS Adventure/galeria/nsc-multigallery-fullscreen-05-f900gs-adventuree.jpg.asset.1692092849372.avif",
            "/images/bmw-motorrad/F 900 GS Adventure/galeria/nsc-multigallery-fullscreen-06-f900gs-adventure.jpg.asset.1692092848626.avif",
            "/images/bmw-motorrad/F 900 GS Adventure/galeria/nsc-multigallery-fullscreen-07-f900gs-adventure.jpg.asset.1692092847917.avif",
            "/images/bmw-motorrad/F 900 GS Adventure/galeria/nsc-multigallery-fullscreen-08-f900gs-adventure.jpg.asset.1692092847269.avif",
        ],
        desktopBanner: "/images/bmw-motorrad/F 900 GS Adventure/banner/nsc-f900gs-adventure-P0N52-multiimage-2560x1440.jpg.asset.1732605002602.jpg.16_10_1920.avif",
    },
    {
        id: "f-900-r",
        brand: "bmw-motorrad",
        name: "F 900 R",
        category: "Roadster",
        price: 13390000,
        image: "/images/bmw-motorrad/F 900 R/min.webp",
        vehicleType: "moto",
        ivaIncluded: true,
        isHybrid: false,
        isElectric: false,
        isNew: false,
        versions: [
            {
                name: "F 900 R",
                motor: "895 cm3",
                fuel: "Gasolina",
                transmission: "Mec\u00e1nica",
                power: "105 HP",
                torque: "92 Nm",
                traction: "4x2",
                listPrice: 14890000,
                brandBonus: 1500000,
                financingBonus: 0,
                bonusPrice: 13390000,
            },
        ],
        slogan: "Make Life a Ride",
        videoUrl: "CARACTER\u00cdSTICAS:",
        features: [
            {
                title: "Dise\u00f1o Din\u00e1mico",
                desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
                image: "/images/bmw-motorrad/F 900 R/caracteristicas/foco.jpg",
            },
            {
                title: "Conducci\u00f3n Eficiente",
                desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
                image: "/images/bmw-motorrad/F 900 R/caracteristicas/superdeportiva.avif",
            },
            {
                title: "Tecnolog\u00edas Innovadoras",
                desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
                image: "/images/bmw-motorrad/F 900 R/caracteristicas/nsc-multigallery-fullllscreen-01-f900r-P0N2L.jpg.asset.1731488348271.avif",
            },
        ],
        gallery: [
            "/images/bmw-motorrad/F 900 R/galeria/1.avif",
            "/images/bmw-motorrad/F 900 R/galeria/2.jpg",
            "/images/bmw-motorrad/F 900 R/galeria/3.avif",
            "/images/bmw-motorrad/F 900 R/galeria/4.jpg",
            "/images/bmw-motorrad/F 900 R/galeria/5.jpg",
            "/images/bmw-motorrad/F 900 R/galeria/6.avif",
            "/images/bmw-motorrad/F 900 R/galeria/7.jpg",
            "/images/bmw-motorrad/F 900 R/galeria/8.avif",
        ],
        desktopBanner: "/images/bmw-motorrad/F 900 R/banner/banner.avif",
    },
    {
        id: "f-900-xr",
        brand: "bmw-motorrad",
        name: "F 900 XR",
        category: "Sport",
        price: 16190000,
        image: "/images/bmw-motorrad/F 900 XR/min.webp",
        vehicleType: "moto",
        ivaIncluded: true,
        isHybrid: false,
        isElectric: false,
        isNew: false,
        versions: [
            {
                name: "F 900 XR",
                motor: "895 cm3",
                fuel: "Gasolina",
                transmission: "Mec\u00e1nica",
                power: "105 HP",
                torque: "92 Nm",
                traction: "4x2",
                listPrice: 17690000,
                brandBonus: 1500000,
                financingBonus: 0,
                bonusPrice: 16190000,
            },
        ],
        slogan: "Make Life a Ride",
        videoUrl: "CARACTER\u00cdSTICAS:",
        features: [
            {
                title: "Dise\u00f1o Din\u00e1mico",
                desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
                image: "/images/bmw-motorrad/F 900 XR/caracteristicas/proteccion.avif",
            },
            {
                title: "Conducci\u00f3n Eficiente",
                desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
                image: "/images/bmw-motorrad/F 900 XR/caracteristicas/regulable.avif",
            },
            {
                title: "Tecnolog\u00edas Innovadoras",
                desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
                image: "/images/bmw-motorrad/F 900 XR/caracteristicas/llantas.jpg",
            },
        ],
        gallery: [
            "/images/bmw-motorrad/F 900 XR/galeria/1.avif",
            "/images/bmw-motorrad/F 900 XR/galeria/2.avif",
            "/images/bmw-motorrad/F 900 XR/galeria/3.avif",
            "/images/bmw-motorrad/F 900 XR/galeria/4.avif",
            "/images/bmw-motorrad/F 900 XR/galeria/5.avif",
            "/images/bmw-motorrad/F 900 XR/galeria/6.avif",
            "/images/bmw-motorrad/F 900 XR/galeria/7.avif",
            "/images/bmw-motorrad/F 900 XR/galeria/8.avif",
        ],
        desktopBanner: "/images/bmw-motorrad/F 900 XR/banner/nsc-f900xr-P0NA5-multiimage-2560x1440.jpg.asset.1732117565123.jpg.16_10_1920.avif",
    },
    {
        id: "g-310-gs",
        brand: "bmw-motorrad",
        name: "G 310 GS",
        category: "Adventure",
        price: 6790000,
        image: "/images/bmw-motorrad/G 310 GS/min.webp",
        vehicleType: "moto",
        ivaIncluded: true,
        isHybrid: false,
        isElectric: false,
        isNew: false,
        versions: [
            {
                name: "G 310 GS",
                motor: "313 cc",
                fuel: "Gasolina",
                transmission: "Mec\u00e1nica",
                power: "34 HP",
                torque: "28 Nm",
                traction: "4x2",
                listPrice: 6790000,
                brandBonus: 0,
                financingBonus: 0,
                bonusPrice: 6790000,
            },
        ],
        slogan: "Make Life a Ride",
        videoUrl: "CARACTER\u00cdSTICAS:",
        features: [
            {
                title: "Dise\u00f1o Din\u00e1mico",
                desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
                image: "/images/bmw-motorrad/G 310 GS/caracteristicas/flyline.avif",
            },
            {
                title: "Conducci\u00f3n Eficiente",
                desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
                image: "/images/bmw-motorrad/G 310 GS/caracteristicas/horquilla.avif",
            },
            {
                title: "Tecnolog\u00edas Innovadoras",
                desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
                image: "/images/bmw-motorrad/G 310 GS/caracteristicas/manetas.avif",
            },
        ],
        gallery: [
            "/images/bmw-motorrad/G 310 GS/galeria/1.avif",
            "/images/bmw-motorrad/G 310 GS/galeria/2.avif",
            "/images/bmw-motorrad/G 310 GS/galeria/3.avif",
            "/images/bmw-motorrad/G 310 GS/galeria/4.avif",
            "/images/bmw-motorrad/G 310 GS/galeria/5.avif",
            "/images/bmw-motorrad/G 310 GS/galeria/6.avif",
            "/images/bmw-motorrad/G 310 GS/galeria/7.avif",
        ],
        desktopBanner: "/images/bmw-motorrad/G 310 GS/banner/nsc-g310gs-P0N3V-multiimage-2560x1440-mx.jpg.asset.1732607652889.jpg.16_10_1920.avif",
    },
    {
        id: "g-310-r",
        brand: "bmw-motorrad",
        name: "G 310 R",
        category: "Roadster",
        price: 5790000,
        image: "/images/bmw-motorrad/G 310 R/min.webp",
        vehicleType: "moto",
        ivaIncluded: true,
        isHybrid: false,
        isElectric: false,
        isNew: false,
        versions: [
            {
                name: "G 310 R",
                motor: "313 cc",
                fuel: "Gasolina",
                transmission: "Mec\u00e1nica",
                consumptionMixed: "3.3 l/100km",
                power: "34 HP",
                torque: "28 Nm",
                traction: "4x2",
                listPrice: 5790000,
                brandBonus: 0,
                financingBonus: 0,
                bonusPrice: 5790000,
            },
        ],
        slogan: "Make Life a Ride",
        videoUrl: "CARACTER\u00cdSTICAS:",
        features: [
            {
                title: "Dise\u00f1o Din\u00e1mico",
                desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
                image: "/images/bmw-motorrad/G 310 R/caracteristicas/asiento.avif",
            },
            {
                title: "Conducci\u00f3n Eficiente",
                desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
                image: "/images/bmw-motorrad/G 310 R/caracteristicas/faro.avif",
            },
            {
                title: "Tecnolog\u00edas Innovadoras",
                desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
                image: "/images/bmw-motorrad/G 310 R/caracteristicas/abs.avif",
            },
        ],
        gallery: [
            "/images/bmw-motorrad/G 310 R/galeria/1.avif",
            "/images/bmw-motorrad/G 310 R/galeria/2.avif",
            "/images/bmw-motorrad/G 310 R/galeria/3.avif",
            "/images/bmw-motorrad/G 310 R/galeria/4.avif",
            "/images/bmw-motorrad/G 310 R/galeria/5.avif",
            "/images/bmw-motorrad/G 310 R/galeria/6.avif",
            "/images/bmw-motorrad/G 310 R/galeria/7.jpg",
        ],
        desktopBanner: "/images/bmw-motorrad/G 310 R/banner/nsc-master-g310r-P0N3C_2560x1440.jpg.asset.1732604929348.jpg.16_10_1920.avif",
    },
    {
        id: "k-1600-gt",
        brand: "bmw-motorrad",
        name: "K 1600 GT",
        category: "Tour",
        price: 33490000,
        image: "/images/bmw-motorrad/K 1600 GT/min.webp",
        vehicleType: "moto",
        ivaIncluded: true,
        isHybrid: false,
        isElectric: false,
        isNew: false,
        versions: [
            {
                name: "K 1600 GT",
                motor: "1.649 cc",
                fuel: "Gasolina",
                transmission: "Mec\u00e1nica",
                power: "160 HP",
                torque: "180 Nm",
                traction: "4x2",
                listPrice: 34890000,
                brandBonus: 1400000,
                financingBonus: 0,
                bonusPrice: 33490000,
            },
        ],
        slogan: "Make Life a Ride",
        videoUrl: "CARACTER\u00cdSTICAS:",
        features: [
            {
                title: "Dise\u00f1o Din\u00e1mico",
                desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
                image: "/images/bmw-motorrad/K 1600 GT/caracteristicas/compensacion.avif",
            },
            {
                title: "Conducci\u00f3n Eficiente",
                desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
                image: "/images/bmw-motorrad/K 1600 GT/caracteristicas/motor-legendario.avif",
            },
            {
                title: "Tecnolog\u00edas Innovadoras",
                desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
                image: "/images/bmw-motorrad/K 1600 GT/caracteristicas/style.jpg",
            },
        ],
        gallery: [
            "/images/bmw-motorrad/K 1600 GT/galeria/1.avif",
            "/images/bmw-motorrad/K 1600 GT/galeria/2.avif",
            "/images/bmw-motorrad/K 1600 GT/galeria/3.avif",
            "/images/bmw-motorrad/K 1600 GT/galeria/4.avif",
            "/images/bmw-motorrad/K 1600 GT/galeria/5.avif",
            "/images/bmw-motorrad/K 1600 GT/galeria/6.avif",
            "/images/bmw-motorrad/K 1600 GT/galeria/7.avif",
        ],
        desktopBanner: "/images/bmw-motorrad/K 1600 GT/banner/nsc-k1600gt-P0ND2-multiimage-2560x1440.jpg.asset.1732605101726.jpg.16_10_1920.avif",
    },
    {
        id: "k-1600-gtl",
        brand: "bmw-motorrad",
        name: "K 1600 GTL",
        category: "Tour",
        price: 34390000,
        image: "/images/bmw-motorrad/K 1600 GTL/min.webp",
        vehicleType: "moto",
        ivaIncluded: true,
        isHybrid: false,
        isElectric: false,
        isNew: false,
        versions: [
            {
                name: "K 1600 GTL",
                motor: "1.649 cc",
                fuel: "Gasolina",
                transmission: "Mec\u00e1nica",
                power: "160 HP",
                torque: "180 Nm",
                traction: "4x2",
                listPrice: 35790000,
                brandBonus: 1400000,
                financingBonus: 0,
                bonusPrice: 34390000,
            },
        ],
        slogan: "Make Life a Ride",
        videoUrl: "CARACTER\u00cdSTICAS:",
        features: [
            {
                title: "Dise\u00f1o Din\u00e1mico",
                desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
                image: "/images/bmw-motorrad/K 1600 GTL/caracteristicas/motor.jpg",
            },
            {
                title: "Conducci\u00f3n Eficiente",
                desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
                image: "/images/bmw-motorrad/K 1600 GTL/caracteristicas/rueda-forjada.avif",
            },
            {
                title: "Tecnolog\u00edas Innovadoras",
                desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
                image: "/images/bmw-motorrad/K 1600 GTL/caracteristicas/botones.avif",
            },
        ],
        gallery: [
            "/images/bmw-motorrad/K 1600 GTL/galeria/1.avif",
            "/images/bmw-motorrad/K 1600 GTL/galeria/2.avif",
            "/images/bmw-motorrad/K 1600 GTL/galeria/3.avif",
            "/images/bmw-motorrad/K 1600 GTL/galeria/4.avif",
            "/images/bmw-motorrad/K 1600 GTL/galeria/5.avif",
            "/images/bmw-motorrad/K 1600 GTL/galeria/6.avif",
            "/images/bmw-motorrad/K 1600 GTL/galeria/7.avif",
            "/images/bmw-motorrad/K 1600 GTL/galeria/8.avif",
            "/images/bmw-motorrad/K 1600 GTL/galeria/9.avif",
        ],
        desktopBanner: "/images/bmw-motorrad/K 1600 GTL/banner/nsc-k1600gtl-P0ND2-multiimage-2560x1440.jpg.asset.1732605103715.jpg.16_10_1920.avif",
    },
    {
        id: "m-1000-r",
        brand: "bmw-motorrad",
        name: "M 1000 R",
        category: "BMW M",
        price: 27990000,
        image: "/images/bmw-motorrad/M 1000 R/min.webp",
        vehicleType: "moto",
        ivaIncluded: true,
        isHybrid: false,
        isElectric: false,
        isNew: false,
        versions: [
            {
                name: "M 1000 R",
                motor: "999 cm3",
                fuel: "Gasolina",
                transmission: "Mec\u00e1nica",
                power: "210 HP",
                torque: "113 Nm",
                traction: "4x2",
                listPrice: 29190000,
                brandBonus: 1200000,
                financingBonus: 0,
                bonusPrice: 27990000,
            },
        ],
        slogan: "Make Life a Ride",
        videoUrl: "CARACTER\u00cdSTICAS:",
        features: [
            {
                title: "Dise\u00f1o Din\u00e1mico",
                desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
                image: "/images/bmw-motorrad/M 1000 R/caracteristicas/tapa-embrague.avif",
            },
            {
                title: "Conducci\u00f3n Eficiente",
                desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
                image: "/images/bmw-motorrad/M 1000 R/caracteristicas/chasis-trasero.avif",
            },
            {
                title: "Tecnolog\u00edas Innovadoras",
                desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
                image: "/images/bmw-motorrad/M 1000 R/caracteristicas/freno-m.avif",
            },
        ],
        gallery: [
            "/images/bmw-motorrad/M 1000 R/galeria/1.avif",
            "/images/bmw-motorrad/M 1000 R/galeria/2.avif",
            "/images/bmw-motorrad/M 1000 R/galeria/3.jpg",
            "/images/bmw-motorrad/M 1000 R/galeria/4.avif",
            "/images/bmw-motorrad/M 1000 R/galeria/5.avif",
            "/images/bmw-motorrad/M 1000 R/galeria/7.avif",
        ],
        desktopBanner: "/images/bmw-motorrad/M 1000 R/banner/nsc-m1000r-P0N52-multiimage-1920x1200.jpg.asset.1732605074688.jpg.16_10_1920.avif",
    },
    {
        id: "m-1000-rr",
        brand: "bmw-motorrad",
        name: "M 1000 RR",
        category: "BMW M",
        price: 48290000,
        image: "/images/bmw-motorrad/M 1000 RR/min.webp",
        vehicleType: "moto",
        ivaIncluded: true,
        isHybrid: false,
        isElectric: false,
        isNew: false,
        versions: [
            {
                name: "M 1000 RR",
                motor: "999 cm3",
                fuel: "Gasolina",
                transmission: "Mec\u00e1nica",
                power: "218 HP",
                torque: "113 Nm",
                traction: "4x2",
                listPrice: 48290000,
                brandBonus: 0,
                financingBonus: 0,
                bonusPrice: 48290000,
            },
        ],
        slogan: "Make Life a Ride",
        videoUrl: "CARACTER\u00cdSTICAS:",
        features: [
            {
                title: "Dise\u00f1o Din\u00e1mico",
                desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
                image: "/images/bmw-motorrad/M 1000 RR/caracteristicas/frontal.avif",
            },
            {
                title: "Conducci\u00f3n Eficiente",
                desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
                image: "/images/bmw-motorrad/M 1000 RR/caracteristicas/piezas-fresadas-m.avif",
            },
            {
                title: "Tecnolog\u00edas Innovadoras",
                desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
                image: "/images/bmw-motorrad/M 1000 RR/caracteristicas/aletas.avif",
            },
        ],
        gallery: [
            "/images/bmw-motorrad/M 1000 RR/galeria/1.avif",
            "/images/bmw-motorrad/M 1000 RR/galeria/2.avif",
            "/images/bmw-motorrad/M 1000 RR/galeria/3.avif",
            "/images/bmw-motorrad/M 1000 RR/galeria/4.avif",
            "/images/bmw-motorrad/M 1000 RR/galeria/5.avif",
            "/images/bmw-motorrad/M 1000 RR/galeria/6.avif",
            "/images/bmw-motorrad/M 1000 RR/galeria/7.avif",
        ],
        desktopBanner: "/images/bmw-motorrad/M 1000 RR/banner/nsc-m1000rr-P0N3S-multiimage-1920x1200.jpg.asset.1732605075760.jpg.16_10_1920.avif",
    },
    {
        id: "m-1000-xr",
        brand: "bmw-motorrad",
        name: "M 1000 XR",
        category: "BMW M",
        price: 38590000,
        image: "/images/bmw-motorrad/M 1000 XR/min.webp",
        vehicleType: "moto",
        ivaIncluded: true,
        isHybrid: false,
        isElectric: false,
        isNew: false,
        versions: [
            {
                name: "M 1000 XR",
                motor: "999 cm3",
                fuel: "Gasolina",
                transmission: "Mec\u00e1nica",
                power: "201 HP",
                torque: "113 Nm",
                traction: "4x2",
                listPrice: 40590000,
                brandBonus: 2000000,
                financingBonus: 0,
                bonusPrice: 38590000,
            },
        ],
        slogan: "Make Life a Ride",
        videoUrl: "CARACTER\u00cdSTICAS:",
        features: [
            {
                title: "Dise\u00f1o Din\u00e1mico",
                desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
                image: "/images/bmw-motorrad/M 1000 XR/caracteristicas/animacion-m-arranque.jpg",
            },
            {
                title: "Conducci\u00f3n Eficiente",
                desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
                image: "/images/bmw-motorrad/M 1000 XR/caracteristicas/motor.jpg",
            },
            {
                title: "Tecnolog\u00edas Innovadoras",
                desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
                image: "/images/bmw-motorrad/M 1000 XR/caracteristicas/fibra-carbono.jpg",
            },
        ],
        gallery: [
            "/images/bmw-motorrad/M 1000 XR/galeria/1.avif",
            "/images/bmw-motorrad/M 1000 XR/galeria/2.jpg",
            "/images/bmw-motorrad/M 1000 XR/galeria/3.jpg",
            "/images/bmw-motorrad/M 1000 XR/galeria/4.jpg",
            "/images/bmw-motorrad/M 1000 XR/galeria/5.jpg",
            "/images/bmw-motorrad/M 1000 XR/galeria/7.avif",
        ],
        desktopBanner: "/images/bmw-motorrad/M 1000 XR/banner/nsc-m1000xr-P0N3S-multiimage-2560x1440.jpg.asset.1732605076923.jpg.16_10_1920.avif",
    },
    {
        id: "r-12",
        brand: "bmw-motorrad",
        name: "R 12",
        category: "Heritage",
        price: 0,
        image: "/images/bmw-motorrad/R 12/min.webp",
        vehicleType: "moto",
        ivaIncluded: true,
        isHybrid: false,
        isElectric: false,
        isNew: false,
        versions: [
            {
                name: "- version: \"BMW R 12\"",
                motor: "\"1.170 cm3 (Boxer)\"",
                fuel: "-",
                transmission: "-",
                power: "95",
                traction: "\"Card\u00e1n\"",
                listPrice: 0,
                brandBonus: 0,
                financingBonus: 0,
                bonusPrice: 0,
            },
            {
                name: "peso_vacio: \"Informaci\u00f3n no especificada\"",
                fuel: "-",
                transmission: "-",
                traction: "-",
                listPrice: 0,
                brandBonus: 0,
                financingBonus: 0,
                bonusPrice: 0,
            },
            {
                name: "consumo_wmtc: \"5.1 l / 100km\"",
                fuel: "-",
                transmission: "-",
                traction: "-",
                listPrice: 0,
                brandBonus: 0,
                financingBonus: 0,
                bonusPrice: 0,
            },
            {
                name: "equipamiento_clave:",
                fuel: "-",
                transmission: "-",
                traction: "-",
                listPrice: 0,
                brandBonus: 0,
                financingBonus: 0,
                bonusPrice: 0,
            },
            {
                name: "- \"Faro LED\"",
                fuel: "-",
                transmission: "-",
                traction: "-",
                listPrice: 0,
                brandBonus: 0,
                financingBonus: 0,
                bonusPrice: 0,
            },
            {
                name: "- \"DTC\"",
                fuel: "-",
                transmission: "-",
                traction: "-",
                listPrice: 0,
                brandBonus: 0,
                financingBonus: 0,
                bonusPrice: 0,
            },
            {
                name: "- \"Asiento monoplaza 754mm\"",
                fuel: "-",
                transmission: "-",
                traction: "-",
                listPrice: 0,
                brandBonus: 0,
                financingBonus: 0,
                bonusPrice: 0,
            },
            {
                name: "- \"Embrague monodisco en seco\"",
                fuel: "-",
                transmission: "-",
                traction: "-",
                listPrice: 0,
                brandBonus: 0,
                financingBonus: 0,
                bonusPrice: 0,
            },
            {
                name: "- \"Horquilla invertida 45mm\"",
                fuel: "-",
                transmission: "-",
                traction: "-",
                listPrice: 0,
                brandBonus: 0,
                financingBonus: 0,
                bonusPrice: 0,
            },
            {
                name: "precio_lista: 18790000",
                fuel: "-",
                transmission: "-",
                traction: "-",
                listPrice: 0,
                brandBonus: 0,
                financingBonus: 0,
                bonusPrice: 0,
            },
            {
                name: "bono_todo_medio_pago: 1000000",
                fuel: "-",
                transmission: "-",
                traction: "-",
                listPrice: 0,
                brandBonus: 0,
                financingBonus: 0,
                bonusPrice: 0,
            },
            {
                name: "bono_autofin: 0",
                fuel: "-",
                transmission: "-",
                traction: "-",
                listPrice: 0,
                brandBonus: 0,
                financingBonus: 0,
                bonusPrice: 0,
            },
            {
                name: "precio_final_con_bono: 17790000",
                fuel: "-",
                transmission: "-",
                traction: "-",
                listPrice: 0,
                brandBonus: 0,
                financingBonus: 0,
                bonusPrice: 0,
            },
            {
                name: "3. Condiciones y Legales",
                fuel: "-",
                transmission: "-",
                traction: "-",
                listPrice: 0,
                brandBonus: 0,
                financingBonus: 0,
                bonusPrice: 0,
            },
        ],
        slogan: "Cat\u00e1logo Estructurado: BMW R 12",
        videoUrl: "https://youtu.be/qr7-k2hK9Io](https://youtu.be/qr7-k2hK9Io)\"",
        gallery: [
            "/images/bmw-motorrad/R 12/galeria/1.avif",
            "/images/bmw-motorrad/R 12/galeria/2.jpg",
            "/images/bmw-motorrad/R 12/galeria/4.avif",
            "/images/bmw-motorrad/R 12/galeria/5.jpg",
            "/images/bmw-motorrad/R 12/galeria/6.avif",
            "/images/bmw-motorrad/R 12/galeria/7.avif",
        ],
        desktopBanner: "/images/bmw-motorrad/R 12/banner/nsc-r12-P0ND2-multiimage-2560x1440.jpg.asset.1732605050837.jpg.16_10_1920.avif",
    },
    //     {
    //         id: "s",
    //         brand: "bmw-motorrad",
    //         name: "R 12 G/S",
    //         category: "Heritage",
    //         price: 20890000,
    //         vehicleType: "moto",
    //         ivaIncluded: true,
    //         isHybrid: false,
    //         isElectric: false,
    //         isNew: false,
    //         versions: [
    //             {
    //             name: "R 12 G/S",
    //             motor: "1.170 cm3",
    //             fuel: "Gasolina",
    //             transmission: "Mec\u00e1nica",
    //             power: "109 HP",
    //             torque: "115 Nm",
    //             traction: "4x2",
    //             listPrice: 21890000,
    //             brandBonus: 1000000,
    //             financingBonus: 0,
    //             bonusPrice: 20890000,
    //         },
    //         ],
    //         slogan: "Make Life a Ride",
    //         videoUrl: "CARACTER\u00cdSTICAS:",
    //         features: [
    //             {
    //             title: "Dise\u00f1o Din\u00e1mico",
    //             desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
    //         },
    //             {
    //             title: "Conducci\u00f3n Eficiente",
    //             desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
    //         },
    //             {
    //             title: "Tecnolog\u00edas Innovadoras",
    //             desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
    //         },
    //         ],
    //     },
    {
        id: "r-12-gs",
        brand: "bmw-motorrad",
        name: "R 12 GS",
        category: "Heritage",
        price: 17790000,
        image: "https://pub-5f17f36d654d46e6a6a748a95586b21f.r2.dev/carmona-assets/autos-nuevos/bmw-motorrad/modelos/r-12-gs/min.webp",
        vehicleType: "moto",
        ivaIncluded: true,
        isHybrid: false,
        isElectric: false,
        isNew: false,
        versions: [
            {
                name: "R 12 GS",
                motor: "1.170 cm3",
                fuel: "Gasolina",
                transmission: "Mecánica",
                power: "95 HP",
                torque: "110 Nm",
                traction: "4x2",
                listPrice: 18790000,
                brandBonus: 1000000,
                financingBonus: 0,
                bonusPrice: 17790000,
            },
        ],
        slogan: "Make Life a Ride",
        videoUrl: "CARACTERÍSTICAS:",
        features: [
            {
                title: "",
                desc: "",
                image: "https://pub-5f17f36d654d46e6a6a748a95586b21f.r2.dev/carmona-assets/autos-nuevos/bmw-motorrad/modelos/r-12-gs/caracteristicas/suspension.webp",
            },
            {
                title: "",
                desc: "",
                image: "https://pub-5f17f36d654d46e6a6a748a95586b21f.r2.dev/carmona-assets/autos-nuevos/bmw-motorrad/modelos/r-12-gs/caracteristicas/enduro-pro.webp",
            },
            {
                title: "",
                desc: "",
                image: "https://pub-5f17f36d654d46e6a6a748a95586b21f.r2.dev/carmona-assets/autos-nuevos/bmw-motorrad/modelos/r-12-gs/caracteristicas/connectride.webp",
            },
        ],
        gallery: [
            "https://pub-5f17f36d654d46e6a6a748a95586b21f.r2.dev/carmona-assets/autos-nuevos/bmw-motorrad/modelos/r-12-gs/galeria/1.webp",
            "https://pub-5f17f36d654d46e6a6a748a95586b21f.r2.dev/carmona-assets/autos-nuevos/bmw-motorrad/modelos/r-12-gs/galeria/2.webp",
            "https://pub-5f17f36d654d46e6a6a748a95586b21f.r2.dev/carmona-assets/autos-nuevos/bmw-motorrad/modelos/r-12-gs/galeria/3.webp",
            "https://pub-5f17f36d654d46e6a6a748a95586b21f.r2.dev/carmona-assets/autos-nuevos/bmw-motorrad/modelos/r-12-gs/galeria/4.webp",
            "https://pub-5f17f36d654d46e6a6a748a95586b21f.r2.dev/carmona-assets/autos-nuevos/bmw-motorrad/modelos/r-12-gs/galeria/5.webp",
            "https://pub-5f17f36d654d46e6a6a748a95586b21f.r2.dev/carmona-assets/autos-nuevos/bmw-motorrad/modelos/r-12-gs/galeria/6.webp",
        ],
        desktopBanner: "https://pub-5f17f36d654d46e6a6a748a95586b21f.r2.dev/carmona-assets/autos-nuevos/bmw-motorrad/modelos/r-12-gs/banner/nsc-r12gs-P0N4B-multiimage-2560x1440.jpg.asset.1749115148447.jpg.16_10_1920.webp",
    },
    {
        id: "r-12-ninet",
        brand: "bmw-motorrad",
        name: "R 12 nineT",
        category: "Heritage",
        price: 20790000,
        image: "/images/bmw-motorrad/R 12 nineT/min.webp",
        vehicleType: "moto",
        ivaIncluded: true,
        isHybrid: false,
        isElectric: false,
        isNew: false,
        versions: [
            {
                name: "R 12 nineT",
                motor: "1.170 cm3",
                fuel: "Gasolina",
                transmission: "Mec\u00e1nica",
                power: "109 HP",
                torque: "115 Nm",
                traction: "4x2",
                listPrice: 21790000,
                brandBonus: 1000000,
                financingBonus: 0,
                bonusPrice: 20790000,
            },
        ],
        slogan: "Make Life a Ride",
        videoUrl: "CARACTER\u00cdSTICAS:",
        features: [
            {
                title: "Dise\u00f1o Din\u00e1mico",
                desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
                image: "/images/bmw-motorrad/R 12 nineT/caracteristicas/superficie-aluminio.avif",
            },
            {
                title: "Conducci\u00f3n Eficiente",
                desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
                image: "/images/bmw-motorrad/R 12 nineT/caracteristicas/silenciador.avif",
            },
            {
                title: "Tecnolog\u00edas Innovadoras",
                desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
                image: "/images/bmw-motorrad/R 12 nineT/caracteristicas/llantas.avif",
            },
        ],
        gallery: [
            "/images/bmw-motorrad/R 12 nineT/galeria/1.avif",
            "/images/bmw-motorrad/R 12 nineT/galeria/2.avif",
            "/images/bmw-motorrad/R 12 nineT/galeria/3.avif",
            "/images/bmw-motorrad/R 12 nineT/galeria/4.avif",
            "/images/bmw-motorrad/R 12 nineT/galeria/5.avif",
            "/images/bmw-motorrad/R 12 nineT/galeria/6.avif",
            "/images/bmw-motorrad/R 12 nineT/galeria/7.avif",
        ],
        desktopBanner: "/images/bmw-motorrad/R 12 nineT/banner/nsc-r12-ninet-P0ND2-multiimage-2560x1440.jpg.asset.1732605049704.jpg.16_10_1920.avif",
    },
    {
        id: "r-1300-gs",
        brand: "bmw-motorrad",
        name: "R 1300 GS",
        category: "Adventure",
        price: 27990000,
        image: "/images/bmw-motorrad/R 1300 GS/min.webp",
        vehicleType: "moto",
        ivaIncluded: true,
        isHybrid: false,
        isElectric: false,
        isNew: false,
        versions: [
            {
                name: "R 1300 GS",
                motor: "1.300 cc",
                fuel: "Gasolina",
                transmission: "Mec\u00e1nica",
                power: "145 HP",
                torque: "149 Nm",
                traction: "4x2",
                listPrice: 28990000,
                brandBonus: 1000000,
                financingBonus: 0,
                bonusPrice: 27990000,
            },
        ],
        slogan: "Make Life a Ride",
        videoUrl: "CARACTER\u00cdSTICAS:",
        features: [
            {
                title: "Dise\u00f1o Din\u00e1mico",
                desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
                image: "/images/bmw-motorrad/R 1300 GS/caracteristicas/evoparalever.avif",
            },
            {
                title: "Conducci\u00f3n Eficiente",
                desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
                image: "/images/bmw-motorrad/R 1300 GS/caracteristicas/parabrisas.avif",
            },
            {
                title: "Tecnolog\u00edas Innovadoras",
                desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
                image: "/images/bmw-motorrad/R 1300 GS/caracteristicas/faro-led.avif",
            },
        ],
        gallery: [
            "/images/bmw-motorrad/R 1300 GS/galeria/1.avif",
            "/images/bmw-motorrad/R 1300 GS/galeria/2.avif",
            "/images/bmw-motorrad/R 1300 GS/galeria/3.avif",
            "/images/bmw-motorrad/R 1300 GS/galeria/4.avif",
            "/images/bmw-motorrad/R 1300 GS/galeria/5.jpg",
            "/images/bmw-motorrad/R 1300 GS/galeria/6.avif",
            "/images/bmw-motorrad/R 1300 GS/galeria/7.avif",
        ],
        desktopBanner: "/images/bmw-motorrad/R 1300 GS/banner/nsc-r1300gs-P0NB5-multiimage-2560x1440.jpg.asset.1732605042120.jpg.16_10_1920.avif",
    },
    {
        id: "r-1300-gs-adventure",
        brand: "bmw-motorrad",
        name: "R 1300 GS Adventure",
        category: "Adventure",
        price: 31990000,
        image: "/images/bmw-motorrad/R 1300 GS Adventure/min.webp",
        vehicleType: "moto",
        ivaIncluded: true,
        isHybrid: false,
        isElectric: false,
        isNew: false,
        versions: [
            {
                name: "R 1300 GS Adventure",
                motor: "1.300 cc",
                fuel: "Gasolina",
                transmission: "Mec\u00e1nica",
                power: "145 HP",
                torque: "149 Nm",
                traction: "4x2",
                listPrice: 31990000,
                brandBonus: 0,
                financingBonus: 0,
                bonusPrice: 31990000,
            },
        ],
        slogan: "Make Life a Ride",
        videoUrl: "CARACTER\u00cdSTICAS:",
        features: [
            {
                title: "Dise\u00f1o Din\u00e1mico",
                desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
                image: "/images/bmw-motorrad/R 1300 GS Adventure/caracteristicas/proteccion.avif",
            },
            {
                title: "Conducci\u00f3n Eficiente",
                desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
                image: "/images/bmw-motorrad/R 1300 GS Adventure/caracteristicas/enduro.avif",
            },
            {
                title: "Tecnolog\u00edas Innovadoras",
                desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
                image: "/images/bmw-motorrad/R 1300 GS Adventure/caracteristicas/autonomia.avif",
            },
        ],
        gallery: [
            "/images/bmw-motorrad/R 1300 GS Adventure/galeria/1.avif",
            "/images/bmw-motorrad/R 1300 GS Adventure/galeria/10.avif",
            "/images/bmw-motorrad/R 1300 GS Adventure/galeria/2.avif",
            "/images/bmw-motorrad/R 1300 GS Adventure/galeria/3.avif",
            "/images/bmw-motorrad/R 1300 GS Adventure/galeria/4.avif",
            "/images/bmw-motorrad/R 1300 GS Adventure/galeria/5.avif",
            "/images/bmw-motorrad/R 1300 GS Adventure/galeria/6.avif",
            "/images/bmw-motorrad/R 1300 GS Adventure/galeria/7.avif",
            "/images/bmw-motorrad/R 1300 GS Adventure/galeria/8.avif",
            "/images/bmw-motorrad/R 1300 GS Adventure/galeria/9.avif",
        ],
        desktopBanner: "/images/bmw-motorrad/R 1300 GS Adventure/banner/nsc-r1300gs-adventure-P0NA5-multiimage-2560x1440.jpg.asset.1732605012850.jpg.16_10_1920.avif",
    },
    {
        id: "r-1300-rt",
        brand: "bmw-motorrad",
        name: "R 1300 RT",
        category: "Tour",
        price: 32990000,
        image: "/images/bmw-motorrad/R 1300 RT/R_1300_RT.png",
        vehicleType: "moto",
        ivaIncluded: true,
        isHybrid: false,
        isElectric: false,
        isNew: false,
        versions: [
            {
                name: "R 1300 RT",
                motor: "1.300 cc",
                fuel: "Gasolina",
                transmission: "Autom\u00e1tica",
                power: "145 HP",
                torque: "149 Nm",
                traction: "4x2",
                listPrice: 33990000,
                brandBonus: 1000000,
                financingBonus: 0,
                bonusPrice: 32990000,
            },
        ],
        slogan: "Make Life a Ride",
        videoUrl: "CARACTER\u00cdSTICAS:",
        features: [
            {
                title: "Dise\u00f1o Din\u00e1mico",
                desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
                image: "/images/bmw-motorrad/R 1300 RT/caracteristicas/cambio-automatico.avif",
            },
            {
                title: "Conducci\u00f3n Eficiente",
                desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
                image: "/images/bmw-motorrad/R 1300 RT/caracteristicas/mas-vision.avif",
            },
            {
                title: "Tecnolog\u00edas Innovadoras",
                desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
                image: "/images/bmw-motorrad/R 1300 RT/caracteristicas/dynamic-chasis.avif",
            },
        ],
        gallery: [
            "/images/bmw-motorrad/R 1300 RT/galeria/1.avif",
            "/images/bmw-motorrad/R 1300 RT/galeria/2.avif",
            "/images/bmw-motorrad/R 1300 RT/galeria/3.avif",
            "/images/bmw-motorrad/R 1300 RT/galeria/4.avif",
            "/images/bmw-motorrad/R 1300 RT/galeria/5.avif",
            "/images/bmw-motorrad/R 1300 RT/galeria/6.avif",
            "/images/bmw-motorrad/R 1300 RT/galeria/7.avif",
            "/images/bmw-motorrad/R 1300 RT/galeria/8.avif",
            "/images/bmw-motorrad/R 1300 RT/galeria/9.avif",
        ],
        desktopBanner: "/images/bmw-motorrad/R 1300 RT/banner/nsc-r1300rt-P0N2L-multiimage-2560x1440.jpg.asset.1754916228695.jpg.16_10_1920.avif",
    },
    {
        id: "s-1000-r",
        brand: "bmw-motorrad",
        name: "S 1000 R",
        category: "Roadster",
        price: 22990000,
        image: "/images/bmw-motorrad/S 1000 R/min.webp",
        vehicleType: "moto",
        ivaIncluded: true,
        isHybrid: false,
        isElectric: false,
        isNew: false,
        versions: [
            {
                name: "S 1000 R",
                motor: "999 cm3",
                fuel: "Gasolina",
                transmission: "Mec\u00e1nica",
                power: "170 HP",
                torque: "114 Nm",
                traction: "4x2",
                listPrice: 23990000,
                brandBonus: 1000000,
                financingBonus: 0,
                bonusPrice: 22990000,
            },
        ],
        slogan: "Make Life a Ride",
        videoUrl: "CARACTER\u00cdSTICAS:",
        features: [
            {
                title: "Dise\u00f1o Din\u00e1mico",
                desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
                image: "/images/bmw-motorrad/S 1000 R/caracteristicas/puno-acelerador.avif",
            },
            {
                title: "Conducci\u00f3n Eficiente",
                desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
                image: "/images/bmw-motorrad/S 1000 R/caracteristicas/motor-superbike.avif",
            },
            {
                title: "Tecnolog\u00edas Innovadoras",
                desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
                image: "/images/bmw-motorrad/S 1000 R/caracteristicas/parabrisas-sport.avif",
            },
        ],
        gallery: [
            "/images/bmw-motorrad/S 1000 R/galeria/0.avif",
            "/images/bmw-motorrad/S 1000 R/galeria/1.avif",
            "/images/bmw-motorrad/S 1000 R/galeria/2.avif",
            "/images/bmw-motorrad/S 1000 R/galeria/3.avif",
            "/images/bmw-motorrad/S 1000 R/galeria/4.avif",
            "/images/bmw-motorrad/S 1000 R/galeria/5.avif",
            "/images/bmw-motorrad/S 1000 R/galeria/6.avif",
        ],
        desktopBanner: "/images/bmw-motorrad/S 1000 R/banner/banner.avif",
    },
    {
        id: "s-1000-rr",
        brand: "bmw-motorrad",
        name: "S 1000 RR",
        category: "Sport",
        price: 29690000,
        image: "/images/bmw-motorrad/S 1000 RR/min.webp",
        vehicleType: "moto",
        ivaIncluded: true,
        isHybrid: false,
        isElectric: false,
        isNew: false,
        versions: [
            {
                name: "S 1000 RR",
                motor: "999 cm3",
                fuel: "Gasolina",
                transmission: "Mec\u00e1nica",
                power: "210 HP",
                torque: "113 Nm",
                traction: "4x2",
                listPrice: 29690000,
                brandBonus: 0,
                financingBonus: 0,
                bonusPrice: 29690000,
            },
        ],
        slogan: "Make Life a Ride",
        videoUrl: "CARACTER\u00cdSTICAS:",
        features: [
            {
                title: "Dise\u00f1o Din\u00e1mico",
                desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
                image: "/images/bmw-motorrad/S 1000 RR/caracteristicas/bateria.avif",
            },
            {
                title: "Conducci\u00f3n Eficiente",
                desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
                image: "/images/bmw-motorrad/S 1000 RR/caracteristicas/vista-frontal.avif",
            },
            {
                title: "Tecnolog\u00edas Innovadoras",
                desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
                image: "/images/bmw-motorrad/S 1000 RR/caracteristicas/revestimiento.avif",
            },
        ],
        gallery: [
            "/images/bmw-motorrad/S 1000 RR/galeria/nsc-s1000rr-P0N3H-animatedfacts-desktop.jpg.asset.1729239726315.avif",
            "/images/bmw-motorrad/S 1000 RR/galeria/nsc-s1000rr-P0N3H-media-desktop-02.jpg.asset.1728910322561.avif",
            "/images/bmw-motorrad/S 1000 RR/galeria/nsc-s1000rr-P0N3H-sound-desktop.jpg.asset.1728649917387.avif",
            "/images/bmw-motorrad/S 1000 RR/galeria/nsc-s1000rr-P0N3H-teaserlarge-01.jpg.asset.1728650204836.avif",
        ],
        desktopBanner: "/images/bmw-motorrad/S 1000 RR/banner/nsc-s1000rr-P0N3H-multiimage-2560x1440.jpg.asset.1732605093940.jpg.16_10_1920.avif",
    },
    {
        id: "s-1000-xr",
        brand: "bmw-motorrad",
        name: "S 1000 XR",
        category: "Sport",
        price: 26290000,
        image: "/images/bmw-motorrad/S 1000 XR/S_1000_XR.png",
        vehicleType: "moto",
        ivaIncluded: true,
        isHybrid: false,
        isElectric: false,
        isNew: false,
        versions: [
            {
                name: "S 1000 XR",
                motor: "999 cm3",
                fuel: "Gasolina",
                transmission: "Mec\u00e1nica",
                power: "170 HP",
                torque: "114 Nm",
                traction: "4x2",
                listPrice: 27390000,
                brandBonus: 1100000,
                financingBonus: 0,
                bonusPrice: 26290000,
            },
        ],
        slogan: "Make Life a Ride",
        videoUrl: "CARACTER\u00cdSTICAS:",
        features: [
            {
                title: "Dise\u00f1o Din\u00e1mico",
                desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
                image: "/images/bmw-motorrad/S 1000 XR/caracteristicas/diseno-frontal.avif",
            },
            {
                title: "Conducci\u00f3n Eficiente",
                desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
                image: "/images/bmw-motorrad/S 1000 XR/caracteristicas/gama-accesorios.avif",
            },
            {
                title: "Tecnolog\u00edas Innovadoras",
                desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
                image: "/images/bmw-motorrad/S 1000 XR/caracteristicas/touring.avif",
            },
        ],
        gallery: [
            "/images/bmw-motorrad/S 1000 XR/galeria/1.avif",
            "/images/bmw-motorrad/S 1000 XR/galeria/2.avif",
            "/images/bmw-motorrad/S 1000 XR/galeria/3.avif",
            "/images/bmw-motorrad/S 1000 XR/galeria/4.avif",
        ],
        desktopBanner: "/images/bmw-motorrad/S 1000 XR/banner/nsc-s1000xr-P0N3N-multiimage-2560x1440.jpg.asset.1757081450509.jpg.16_10_1920.avif",
    },
];
