import { Vehicle } from './types';

export const BMW_MODELS: Vehicle[] = [
    // SUV
    {
        id: 'x1',
        brand: 'bmw',
        name: 'X1',
        category: 'SUV',
        price: 36990000,
        image: '/images/bmw/X1.png',
        isHybrid: false,
        isNew: false,
    },
    {
        id: 'x2',
        brand: 'bmw',
        name: 'X2',
        category: 'SUV',
        price: 41990000,
        image: '/images/bmw/X2.png',
        isHybrid: false,
        isNew: false,
    },
    {
        id: 'x3',
        brand: 'bmw',
        name: 'X3',
        category: 'SUV',
        price: 48990000,
        image: '/images/bmw/X3.png',
        isHybrid: false,
        isNew: false,
    },
    {
        id: 'x4',
        brand: 'bmw',
        name: 'X4',
        category: 'SUV',
        price: 53990000,
        image: '/images/bmw/X4.png',
        isHybrid: false,
        isNew: false,
    },
    {
        id: 'x5',
        brand: 'bmw',
        name: 'X5',
        category: 'SUV',
        price: 72990000,
        image: '/images/bmw/X5.png',
        isHybrid: false,
        isNew: false,
    },
    {
        id: 'x6',
        brand: 'bmw',
        name: 'X6',
        category: 'SUV',
        price: 82990000,
        image: '/images/bmw/X6.png',
        isHybrid: false,
        isNew: false,
    },
    {
        id: 'x7',
        brand: 'bmw',
        name: 'X7',
        category: 'SUV',
        price: 104990000,
        image: '/images/bmw/X7.png',
        isHybrid: false,
        isNew: false,
    },
    {
        id: 'x2-m35i',
        brand: 'bmw',
        name: 'X2 M35i',
        category: 'SUV',
        price: 54990000,
        image: '/images/bmw/X2_M35i.png',
        isHybrid: false,
        isNew: true,
    },

    // HATCHBACK
    {
        id: 'serie-1',
        brand: 'bmw',
        name: 'Serie 1',
        category: 'HATCHBACK',
        price: 26990000,
        image: '/images/bmw/serie-1.png',
        isHybrid: false,
        isNew: false,
    },
    {
        id: 'm135',
        brand: 'bmw',
        name: 'M135',
        category: 'HATCHBACK',
        price: 44990000,
        image: '/images/bmw/m135.png',
        isHybrid: false,
        isNew: false,
    },

    // COUPÉ
    {
        id: 'serie-2-coupe',
        brand: 'bmw',
        name: 'Serie 2 Coupé',
        category: 'COUPÉ',
        price: 33990000,
        image: '/images/bmw/serie-2_coupe.png',
        isHybrid: false,
        isNew: false,
    },
    {
        id: 'serie-2-gran-coupe',
        brand: 'bmw',
        name: 'Serie 2 Gran Coupé',
        category: 'COUPÉ',
        price: 31990000,
        image: '/images/bmw/serie-2_gran-coupe.png',
        isHybrid: false,
        isNew: false,
    },
    {
        id: 'serie-4-coupe',
        brand: 'bmw',
        name: 'Serie 4 Coupé',
        category: 'COUPÉ',
        price: 46990000,
        image: '/images/bmw/Serie-4_Coupe.png',
        isHybrid: false,
        isNew: false,
    },
    {
        id: 'serie-4-gran-coupe',
        brand: 'bmw',
        name: 'Serie 4 Gran Coupé',
        category: 'COUPÉ',
        price: 48990000,
        image: '/images/bmw/serie-4_gran-coupe.png',
        isHybrid: false,
        isNew: false,
    },
    {
        id: 'serie-8-coupe',
        brand: 'bmw',
        name: 'Serie 8 Coupé',
        category: 'COUPÉ',
        price: 89990000,
        image: '/images/bmw/serie-8_coupe.png',
        isHybrid: false,
        isNew: false,
    },
    {
        id: 'm240i',
        brand: 'bmw',
        name: 'M240i',
        category: 'COUPÉ',
        price: 53990000,
        image: '/images/bmw/m240i.png',
        isHybrid: false,
        isNew: false,
    },
    {
        id: 'm440i-gran-coupe',
        brand: 'bmw',
        name: 'M440i Gran Coupé',
        category: 'COUPÉ',
        price: 64990000,
        image: '/images/bmw/m440i_gran-coue.png',
        isHybrid: false,
        isNew: false,
    },
    {
        id: 'serie-2-gran',
        brand: 'bmw',
        name: 'Serie 2 Gran',
        category: 'COUPÉ',
        price: 30990000,
        image: '/images/bmw/serie-2_grand_coupe.png',
        isHybrid: false,
        isNew: false,
    },

    // SEDAN
    {
        id: 'serie-3',
        brand: 'bmw',
        name: 'Serie 3',
        category: 'SEDAN',
        price: 38990000,
        image: '/images/bmw/serie-3.png',
        isHybrid: false,
        isNew: false,
    },
    {
        id: 'serie-5',
        brand: 'bmw',
        name: 'Serie 5',
        category: 'SEDAN',
        price: 52990000,
        image: '/images/bmw/serie-5.png',
        isHybrid: false,
        isNew: false,
    },
    {
        id: 'serie-7-hibrido',
        brand: 'bmw',
        name: 'Serie 7 Híbrido',
        category: 'SEDAN',
        price: 114990000,
        image: '/images/bmw/serie-7_hibrido.png',
        isHybrid: true,
        isNew: true,
    },

    // CONVERTIBLE
    {
        id: 'serie-4-convertible',
        brand: 'bmw',
        name: 'Serie 4 Convertible',
        category: 'CONVERTIBLE',
        price: 58990000,
        image: '/images/bmw/serie-4_convertible.png',
        isHybrid: false,
        isNew: false,
    },
    {
        id: 'z4',
        brand: 'bmw',
        name: 'Z4',
        category: 'CONVERTIBLE',
        price: 53990000,
        image: '/images/bmw/z4.png',
        isHybrid: false,
        isNew: false,
    },
    {
        id: 'm4-convertible',
        brand: 'bmw',
        name: 'M4 Convertible',
        category: 'CONVERTIBLE',
        price: 92990000,
        image: '/images/bmw/m4_convertible.png',
        isHybrid: false,
        isNew: false,
    },

    // DEPORTIVOS
    {
        id: 'm2',
        brand: 'bmw',
        name: 'M2',
        category: 'DEPORTIVOS',
        price: 72990000,
        image: '/images/bmw/m2.png',
        isHybrid: false,
        isNew: false,
    },
    {
        id: 'm3',
        brand: 'bmw',
        name: 'M3',
        category: 'DEPORTIVOS',
        price: 84990000,
        image: '/images/bmw/m3.png',
        isHybrid: false,
        isNew: false,
    },
    {
        id: 'm4',
        brand: 'bmw',
        name: 'M4',
        category: 'DEPORTIVOS',
        price: 88990000,
        image: '/images/bmw/m4.png',
        isHybrid: false,
        isNew: false,
    },
    {
        id: 'm5',
        brand: 'bmw',
        name: 'M5',
        category: 'DEPORTIVOS',
        price: 114990000,
        image: '/images/bmw/m5.png',
        isHybrid: false,
        isNew: false,
    },
    {
        id: 'x5m',
        brand: 'bmw',
        name: 'X5 M',
        category: 'DEPORTIVOS',
        price: 119990000,
        image: '/images/bmw/x5m.png',
        isHybrid: false,
        isNew: false,
    },
    {
        id: 'x6m',
        brand: 'bmw',
        name: 'X6 M',
        category: 'DEPORTIVOS',
        price: 124990000,
        image: '/images/bmw/x6m.png',
        isHybrid: false,
        isNew: false,
    },

    // ELÉCTRICOS
    {
        id: 'i4',
        brand: 'bmw',
        name: 'i4',
        category: 'ELÉCTRICOS',
        price: 72990000,
        image: '/images/bmw/i4.png',
        isElectric: true,
        isNew: false,
    },
    {
        id: 'ix',
        brand: 'bmw',
        name: 'iX',
        category: 'ELÉCTRICOS',
        price: 92990000,
        image: '/images/bmw/iX.png',
        isElectric: true,
        isNew: false,
    },
    {
        id: 'serie-3-hibrido',
        brand: 'bmw',
        name: 'Serie 3 Híbrido',
        category: 'ELÉCTRICOS',
        price: 48990000,
        image: '/images/bmw/serie-3_hibrido.png',
        isHybrid: true,
        isNew: false,
    },
    {
        id: 'x5-hibrido',
        brand: 'bmw',
        name: 'X5 Híbrido',
        category: 'ELÉCTRICOS',
        price: 81990000,
        image: '/images/bmw/x5_hibrido.png',
        isHybrid: true,
        isNew: false,
    },
    {
        id: 'ix1',
        brand: 'bmw',
        name: 'iX1',
        category: 'ELÉCTRICOS',
        price: 52990000,
        image: '/images/bmw/iX1.png',
        isElectric: true,
        isNew: true,
    },
    {
        id: 'x1-hibrido',
        brand: 'bmw',
        name: 'X1 Híbrido',
        category: 'ELÉCTRICOS',
        price: 44990000,
        image: '/images/bmw/X1_Hibrido.png',
        isHybrid: true,
        isNew: true,
    },
    {
        id: 'i5',
        brand: 'bmw',
        name: 'i5',
        category: 'ELÉCTRICOS',
        price: 82990000,
        image: '/images/bmw/i5.png',
        isElectric: true,
        isNew: true,
    },
    {
        id: 'i7',
        brand: 'bmw',
        name: 'i7',
        category: 'ELÉCTRICOS',
        price: 134990000,
        image: '/images/bmw/i7.png',
        isElectric: true,
        isNew: true,
    },
    {
        id: 'ix2',
        brand: 'bmw',
        name: 'iX2',
        category: 'ELÉCTRICOS',
        price: 58990000,
        image: '/images/bmw/iX2.png',
        isElectric: true,
        isNew: true,
    },
    {
        id: 'serie-5-hibrido',
        brand: 'bmw',
        name: 'Serie 5 Híbrido',
        category: 'ELÉCTRICOS',
        price: 62990000,
        image: '/images/bmw/serie-5_hibrido.png',
        isHybrid: true,
        isNew: true,
    },
    {
        id: 'x3-hibrido',
        brand: 'bmw',
        name: 'X3 Híbrido',
        category: 'ELÉCTRICOS',
        price: 52990000,
        image: '/images/bmw/X3_hibrido.png',
        isHybrid: true,
        isNew: false,
    }
];
