import { Vehicle } from './types';

export const CUPRA_MODELS: Vehicle[] = [
    {
        id: "formentor",
        brand: "cupra",
        name: "Formentor",
        category: "SUV",
        price: 33490000,
        image: "/images/cupra/Formentor/formentor.webp",
        vehicleType: "liviano",
        ivaIncluded: true,
        isHybrid: false,
        isElectric: false,
        isNew: true,
        isFeatured: true,
        versions: [
            {
                name: "Formentor 2.0 TSI 204hp 4Drive",
                motor: "2.0 TSI",
                fuel: "Gasolina",
                transmission: "DCT / DSG",
                consumptionMixed: "10.4 km/l",
                power: "204 HP",
                torque: "320 Nm",
                traction: "AWD",
                listPrice: 36990000,
                brandBonus: 1300000,
                financingBonus: 2200000,
                bonusPrice: 33490000,
            },
            {
                name: "Formentor VZ 2.0 TSI AT 4Drive",
                motor: "2.0 TSI",
                fuel: "Gasolina",
                transmission: "DCT / DSG",
                consumptionMixed: "9.5 km/l",
                power: "333 HP",
                torque: "420 Nm",
                traction: "AWD",
                listPrice: 44990000,
                brandBonus: 800000,
                financingBonus: 1700000,
                bonusPrice: 42490000,
            },
            {
                name: "Formentor VZ 2.0 TSI AT 4Drive | Pintura Mate + Llantas Cobre",
                motor: "2.0 TSI",
                fuel: "Gasolina",
                transmission: "DCT / DSG",
                consumptionMixed: "9.5 km/l",
                power: "333 HP",
                torque: "420 Nm",
                traction: "AWD",
                listPrice: 47990000,
                brandBonus: 800000,
                financingBonus: 1700000,
                bonusPrice: 45490000,
            },
            {
                name: "Formentor VZ Black Rebel 2.0 TSI AT 4Drive",
                motor: "2.0 TSI",
                fuel: "Gasolina",
                transmission: "DCT / DSG",
                consumptionMixed: "9.5 km/l",
                power: "333 HP",
                torque: "420 Nm",
                traction: "AWD",
                listPrice: 47990000,
                brandBonus: 800000,
                financingBonus: 1700000,
                bonusPrice: 45490000,
            },
        ],
        slogan: "Nacido para Desafiar.",
        videoUrl: "CARACTERÍSTICAS:",
        features: [
            {
                title: "Sistema de sonido inmersivo Sennheiser",
                desc: "El sonido no es sólo escuchar; es una experiencia profunda, diseñada para acompañarte en cada momento.",
                image: "/images/cupra/Formentor/caracteristicas/sonido-inmersivo.webp",
            },
            {
                title: "Radio touchscreen de 12,9\"",
                desc: "Interacción intuitiva y conectividad avanzada en una pantalla que lleva el control y la emoción a otro nivel.",
                image: "/images/cupra/Formentor/caracteristicas/radio-touch.webp",
            },
            {
                title: "Digital Cockpit 10,25\"",
                desc: "Toda la información que necesitas, justo donde la necesitas. El Digital Cockpit de 10,25” te ofrece una experiencia de conducción totalmente digital, con una visualización personalizable y nítida que te mantiene conectado con el rendimiento de tu vehículo.",
                image: "/images/cupra/Formentor/caracteristicas/digital-cockpit.webp",
            },
        ],
        gallery: [
            "/images/cupra/Formentor/galeria/CUPRA-FORMENTOR-PA-001.webp",
            "/images/cupra/Formentor/galeria/CUPRA-FORMENTOR-PA-009.webp",
            "/images/cupra/Formentor/galeria/CUPRA-FORMENTOR-PA-035.webp",
            "/images/cupra/Formentor/galeria/CUPRA-FORMENTOR-PA-153.webp",
            "/images/cupra/Formentor/galeria/CUPRA-Formentor-2025-fascias-deportivas.webp",
            "/images/cupra/Formentor/galeria/CUPRA-Formentor-2025-luz-trasera-infinita.webp",
            "/images/cupra/Formentor/galeria/CUPRA-Formentor-2025-obsesion-por-el-control.webp",
        ],
        desktopBanner: "/images/cupra/Formentor/banner/banner.webp",
    },
    {
        id: "formentor-e-hybrid",
        brand: "cupra",
        name: "Formentor e-Hybrid",
        category: "Híbrido, SUV",
        price: 35490000,
        image: "/images/cupra/Formentor e-Hybrid/formentor e-hybrid.webp",
        vehicleType: "liviano",
        ivaIncluded: true,
        isHybrid: false,
        isElectric: false,
        isNew: false,
        versions: [
            {
                name: "Formentor 1.5 TSI e-Hybrid",
                motor: "1.5 TSI e-Hybrid",
                fuel: "Plug-in Hybrid",
                transmission: "DCT / DSG",
                consumptionMixed: "17.8 km/l",
                electricRange: "126 km",
                power: "204 HP",
                torque: "350 Nm",
                traction: "4x2",
                airbags: 10,
                listPrice: 40990000,
                brandBonus: 1500000,
                financingBonus: 4000000,
                bonusPrice: 35490000,
            },
        ],
        slogan: "Forget about refuelling",
        videoUrl: "CARACTERÍSTICAS:",
        features: [
            {
                title: "Asientos Bucket",
                desc: "Asientos Bucket de cuero con ajuste eléctrico en altura y soporte lumbar, diseñados para ofrecer confort y estilo en cada viaje.",
                image: "/images/cupra/Formentor e-Hybrid/caracteristicas/asientos.webp",
            },
            {
                title: "Llantas de aleación de 18\"",
                desc: "Llantas deportivas que mejoran el rendimiento, diseñadas para ofrecer una conducción más precisa y dinámica. Incorporan el logo de CUPRA en cobre, que no solo aporta un toque distintivo de estilo, sino que también reflejan un carácter deportivo y sofisticado.",
                image: "/images/cupra/Formentor e-Hybrid/caracteristicas/llantas.webp",
            }, {
                title: "Iluminación LED",
                desc: "Sus luces diurnas, principales y traseras LED ofrecen una firma luminosa única, mejorando la visibilidad y realzando su carácter deportivo con un diseño inconfundible.",
                image: "/images/cupra/Formentor e-Hybrid/caracteristicas/limunicaion-led.webp",
            },
        ],
        gallery: [
            "/images/cupra/Formentor e-Hybrid/galeria/CUPRA-FORMENTOR-PA-007-copy2.webp",
            "/images/cupra/Formentor e-Hybrid/galeria/CUPRA-FORMENTOR-PA-037-copy1.webp",
            "/images/cupra/Formentor e-Hybrid/galeria/CUPRA-FORMENTOR-PA-127-copy1.webp",
            "/images/cupra/Formentor e-Hybrid/galeria/CUPRA-FORMENTOR-PA-168-copy1.webp",
        ],
        desktopBanner: "/images/cupra/Formentor e-Hybrid/banner/banner.webp",
    },
    {
        id: "leon",
        brand: "cupra",
        name: "León",
        category: "Hatchback, Híbrido",
        price: 27990000,
        image: "/images/cupra/Leon/leon.webp",
        vehicleType: "liviano",
        ivaIncluded: true,
        isHybrid: true,
        isElectric: false,
        isNew: false,
        versions: [
            {
                name: "Cupra Leon 1.5 TSI mHEV AT | Colores Cat A",
                motor: "1.5 TSI mHEV",
                fuel: "Híbrido",
                transmission: "DSG 7",
                consumptionMixed: "17.7 km/l",
                power: "150 HP",
                torque: "250 Nm",
                traction: "4x2",
                airbags: 10,
                listPrice: 31490000,
                brandBonus: 1000000,
                financingBonus: 2500000,
                bonusPrice: 27990000,
            },
            {
                name: "Cupra Leon 1.5 TSI mHEV AT | Colores Cat B",
                motor: "1.5 TSI mHEV",
                fuel: "Híbrido",
                transmission: "DSG 7",
                consumptionMixed: "17.7 km/l",
                power: "150 HP",
                torque: "250 Nm",
                traction: "4x2",
                airbags: 10,
                listPrice: 31490000,
                brandBonus: 300000,
                financingBonus: 2500000,
                bonusPrice: 28690000,
            },
            {
                name: "Cupra Leon VZ 2.0 TSI AT",
                motor: "2.0 TSI",
                fuel: "Gasolina",
                transmission: "DSG 7",
                consumptionMixed: "14.0 km/l",
                power: "300 HP",
                torque: "400 Nm",
                traction: "4x2",
                airbags: 10,
                listPrice: 40490000,
                brandBonus: 700000,
                financingBonus: 1900000,
                bonusPrice: 37890000,
            },
            {
                name: "Cupra Leon VZ 2.0 TSI AT | Pintura Mate + Llantas Cobre",
                motor: "2.0 TSI",
                fuel: "Gasolina",
                transmission: "DSG 7",
                consumptionMixed: "14.0 km/l",
                power: "300 HP",
                torque: "400 Nm",
                traction: "4x2",
                airbags: 10,
                listPrice: 43490000,
                brandBonus: 700000,
                financingBonus: 1900000,
                bonusPrice: 40890000,
            },
        ],
        slogan: "MAGNETISMO A PRIMERA VISTA",
        videoUrl: "CARACTERÍSTICAS:",
        features: [
            {
                title: "Pantalla táctil de 12,9\"",
                desc: "Radio touchscreen de 12.9 pulgadas con sistema de navegación y conectividad Full Link inalámbrico (Android Auto & CarPlay).",
                image: "/images/cupra/Leon/caracteristicas/cargador-inalambrico.webp",
            },
            {
                title: "Asientos Bucket",
                desc: "Deportividad en cada viaje con asientos delanteros calefaccionados, ajuste lumbar eléctrico y climatizador automático de 3 zonas.",
                image: "/images/cupra/Leon/caracteristicas/asientos-bucket.webp",
            },
            {
                title: "Máxima Seguridad",
                desc: "Equipado con 10 airbags, incluyendo airbag central delantero y de rodilla para el conductor, además de Intelligent Park Assist y detector de punto ciego.",
                image: "/images/cupra/Leon/caracteristicas/placa-iluminada.webp",
            },
        ],
        gallery: [
            "/images/cupra/Leon/galeria/CUPRA-LEON-PA-011.webp",
            "/images/cupra/Leon/galeria/CUPRA-LEON-PA-031-copy1.webp",
            "/images/cupra/Leon/galeria/CUPRA-LEON-PA-031.webp",
            "/images/cupra/Leon/galeria/CUPRA-LEON-PA-037.webp",
            "/images/cupra/Leon/galeria/CUPRA-LEON-PA-102.webp",
            "/images/cupra/Leon/galeria/cupra-leon-2025-obsession-por-la-ciudad.webp",
        ],
        desktopBanner: "/images/cupra/Leon/banner/banner.webp",
    },
    {
        id: "tavascan",
        brand: "cupra",
        name: "Tavascan",
        category: "Eléctrico, SUV",
        price: 47990000,
        image: "/images/cupra/Tavascan/tavascan.webp",
        vehicleType: "liviano",
        ivaIncluded: true,
        isHybrid: false,
        isElectric: true,
        isNew: false,
        versions: [
            {
                name: "Tavascan Adrenaline 82 kWh",
                motor: "Motor Eléctrico",
                fuel: "Eléctrico",
                transmission: "Automática",
                consumptionMixed: "16.8 kWh/100km",
                electricRange: "569 km",
                power: "286 HP",
                torque: "545 Nm",
                traction: "4x2",
                airbags: 7,
                listPrice: 50990000,
                brandBonus: 1000000,
                financingBonus: 2000000,
                bonusPrice: 47990000,
            },
            {
                name: "Tavascan Extreme 82 kWh",
                motor: "Motor Eléctrico",
                fuel: "Eléctrico",
                transmission: "Automática",
                consumptionMixed: "17.2 kWh/100km",
                electricRange: "569 km",
                power: "286 HP",
                torque: "545 Nm",
                traction: "4x2",
                airbags: 7,
                listPrice: 53990000,
                brandBonus: 1000000,
                financingBonus: 2000000,
                bonusPrice: 50990000,
            },
            {
                name: "Tavascan Extreme 82 kWh | Pintura Mate",
                motor: "Motor Eléctrico",
                fuel: "Eléctrico",
                transmission: "Automática",
                consumptionMixed: "17.2 kWh/100km",
                electricRange: "569 km",
                power: "286 HP",
                torque: "545 Nm",
                traction: "4x2",
                airbags: 7,
                listPrice: 55490000,
                brandBonus: 1000000,
                financingBonus: 2000000,
                bonusPrice: 52490000,
            },
        ],
        slogan: "La tribu se enciende",
        videoUrl: "CARACTERÍSTICAS:",
        features: [
            {
                title: "Asientos Bucket",
                desc: "Disfruta de los asientos con ajuste eléctrico de altura y lumbar ergonómicos, diseñados para ofrecer un soporte y confort superior. Cada trayecto se convierte en una experiencia única, con el ajuste perfecto para tu cuerpo.",
                image: "/images/cupra/Tavascan/caracteristicas/asientos.webp",
            },
            {
                title: "Atmósfera cálida",
                desc: "Al entrar al CUPRA Tavascan, la luz brilla a través de los paneles perforados retroiluminados de las puertas. El resplandor se extiende por el panel frontal, donde se suman detalles en las luces de los portavasos y otros espacios del habitáculo.",
                image: "/images/cupra/Tavascan/caracteristicas/atmosfera.webp",
            },
            {
                title: "El centro de todo",
                desc: "Acabada con refinados toques de cobre, cada contorno de la columna central es ejemplo de una meticulosa artesanía. El diseño se extiende a la pantalla central centrada en el conductor, lo cual garantiza que se pueda controlar fácilmente para un rendimiento potente.",
                image: "/images/cupra/Tavascan/caracteristicas/centro-de-todo.webp",
            },
        ],
        gallery: [
            "/images/cupra/Tavascan/galeria/CUPRA-TAVASCAN-015.webp",
            "/images/cupra/Tavascan/galeria/CUPRA-TAVASCAN-019.webp",
            "/images/cupra/Tavascan/galeria/CUPRA-TAVASCAN-074.webp",
            "/images/cupra/Tavascan/galeria/CUPRA-TAVASCAN-133-copy1.webp",
            "/images/cupra/Tavascan/galeria/cupra-tavascan-2024-black-and-copper-wheel.webp",
            "/images/cupra/Tavascan/galeria/new-electric-cupra-rear-lighting-2024.webp",
        ],
        desktopBanner: "/images/cupra/Tavascan/banner/Ajuste-CUPRA-TAVASCAN-052.webp",
    },
    {
        id: "terramar",
        brand: "cupra",
        name: "Terramar",
        category: "Híbrido, SUV",
        price: 37390000,
        image: "/images/cupra/Terramar/terramar.webp",
        vehicleType: "liviano",
        ivaIncluded: true,
        isHybrid: true,
        isElectric: false,
        isNew: false,
        versions: [
            {
                name: "Terramar 1.5 TSI mHEV AT",
                motor: "1.5 TSI mHEV",
                fuel: "Híbrido",
                transmission: "DCT / DSG",
                consumptionMixed: "14.2 km/l",
                electricRange: "1078 km",
                power: "150 HP",
                torque: "250 Nm",
                traction: "4x2",
                airbags: 6,
                listPrice: 39990000,
                brandBonus: 800000,
                financingBonus: 1800000,
                bonusPrice: 37390000,
            },
            {
                name: "Terramar High 1.5 TSI mHEV AT",
                motor: "1.5 TSI mHEV",
                fuel: "Híbrido",
                transmission: "DCT / DSG",
                consumptionMixed: "14.2 km/l",
                electricRange: "1078 km",
                power: "150 HP",
                torque: "250 Nm",
                traction: "4x2",
                airbags: 6,
                listPrice: 43990000,
                brandBonus: 800000,
                financingBonus: 1300000,
                bonusPrice: 41890000,
            },
            {
                name: "Terramar High 1.5 TSI mHEV AT | Pintura Mate",
                motor: "1.5 TSI mHEV",
                fuel: "Híbrido",
                transmission: "DCT / DSG",
                consumptionMixed: "14.2 km/l",
                electricRange: "1078 km",
                power: "150 HP",
                torque: "250 Nm",
                traction: "4x2",
                airbags: 6,
                listPrice: 45490000,
                brandBonus: 800000,
                financingBonus: 1300000,
                bonusPrice: 43390000,
            },
        ],
        slogan: "ser segundo no es opción",
        videoUrl: "CARACTERÍSTICAS:",
        features: [
            {
                title: "Asientos delanteros tipo bucket con ajuste eléctrico",
                desc: "Disfruta de los asientos con ajuste eléctrico de altura y lumbar ergonómicos, diseñados para ofrecer un soporte y confort superior. Cada trayecto se convierte en una experiencia única, con el ajuste perfecto para tu cuerpo.",
                image: "/images/cupra/Terramar/caracteristicas/asientos.webp",
            },
            {
                title: "Perfección en cada detalle",
                desc: "Interior envolvente, pensado para el conductor. Materiales premium, iluminación ambiental y formas que inspiran. Cada línea fluye como una ola, cada detalle respira precisión.",
                image: "/images/cupra/Terramar/caracteristicas/perfeccion.webp",
            },
            {
                title: "Radio touchscreen de 12,9\"",
                desc: "Compatibilidad Full Link inalámbrica con Android Auto y Apple Carplay.",
                image: "/images/cupra/Terramar/caracteristicas/radio.webp",
            },
        ],
        gallery: [
            "/images/cupra/Terramar/galeria/1.webp",
            "/images/cupra/Terramar/galeria/2.jpeg",
            "/images/cupra/Terramar/galeria/3.webp",
            "/images/cupra/Terramar/galeria/4.jpeg",
            "/images/cupra/Terramar/galeria/5.webp",
            "/images/cupra/Terramar/galeria/6.webp",
        ],
        desktopBanner: "/images/cupra/Terramar/banner/CUPRA-TERRAMAR-114.webp",
    },
];