import { Vehicle } from './types';

export const CUPRA_MODELS: Vehicle[] = [
    {
        id: "formentor",
        brand: "cupra",
        name: "Formentor",
        category: "SUV",
        price: 33490000,
        image: "/images/cupra/Formentor/formentor.webp",
        vehicleType: "liviano",
        ivaIncluded: true,
        isHybrid: false,
        isElectric: false,
        isNew: false,
        versions: [
            {
                name: "Formentor 2.0 TSI 204hp 4Drive",
                motor: "2.0 TSI",
                fuel: "Gasolina",
                transmission: "DCT / DSG",
                consumptionMixed: "10.4 km/l",
                power: "204 HP",
                torque: "320 Nm",
                traction: "AWD",
                listPrice: 36990000,
                brandBonus: 1300000,
                financingBonus: 2200000,
                bonusPrice: 33490000,
            },
            {
                name: "Formentor VZ 2.0 TSI AT 4Drive",
                motor: "2.0 TSI",
                fuel: "Gasolina",
                transmission: "DCT / DSG",
                consumptionMixed: "9.5 km/l",
                power: "333 HP",
                torque: "420 Nm",
                traction: "AWD",
                listPrice: 44990000,
                brandBonus: 800000,
                financingBonus: 1700000,
                bonusPrice: 42490000,
            },
            {
                name: "Formentor VZ 2.0 TSI AT 4Drive | Pintura Mate + Llantas Cobre",
                motor: "2.0 TSI",
                fuel: "Gasolina",
                transmission: "DCT / DSG",
                consumptionMixed: "9.5 km/l",
                power: "333 HP",
                torque: "420 Nm",
                traction: "AWD",
                listPrice: 47990000,
                brandBonus: 800000,
                financingBonus: 1700000,
                bonusPrice: 45490000,
            },
            {
                name: "Formentor VZ Black Rebel 2.0 TSI AT 4Drive",
                motor: "2.0 TSI",
                fuel: "Gasolina",
                transmission: "DCT / DSG",
                consumptionMixed: "9.5 km/l",
                power: "333 HP",
                torque: "420 Nm",
                traction: "AWD",
                listPrice: 47990000,
                brandBonus: 800000,
                financingBonus: 1700000,
                bonusPrice: 45490000,
            },
        ],
        slogan: "Nacido para Desafiar.",
        videoUrl: "CARACTER\u00cdSTICAS:",
        features: [
            {
                title: "Dise\u00f1o Din\u00e1mico",
                desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
                image: "/images/cupra/Formentor/caracteristicas/sonido-inmersivo.webp",
            },
            {
                title: "Conducci\u00f3n Eficiente",
                desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
                image: "/images/cupra/Formentor/caracteristicas/radio-touch.webp",
            },
            {
                title: "Tecnolog\u00edas Innovadoras",
                desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
                image: "/images/cupra/Formentor/caracteristicas/digital-cockpit.webp",
            },
        ],
        gallery: [
            "/images/cupra/Formentor/galeria/CUPRA-FORMENTOR-PA-001.webp",
            "/images/cupra/Formentor/galeria/CUPRA-FORMENTOR-PA-009.webp",
            "/images/cupra/Formentor/galeria/CUPRA-FORMENTOR-PA-035.webp",
            "/images/cupra/Formentor/galeria/CUPRA-FORMENTOR-PA-153.webp",
            "/images/cupra/Formentor/galeria/CUPRA-Formentor-2025-fascias-deportivas.webp",
            "/images/cupra/Formentor/galeria/CUPRA-Formentor-2025-luz-trasera-infinita.webp",
            "/images/cupra/Formentor/galeria/CUPRA-Formentor-2025-obsesion-por-el-control.webp",
        ],
        desktopBanner: "/images/cupra/Formentor/banner/banner.webp",
    },
    {
        id: "formentor-e-hybrid",
        brand: "cupra",
        name: "Formentor e-Hybrid",
        category: "Híbrido, SUV",
        price: 35490000,
        image: "/images/cupra/Formentor e-Hybrid/formentor e-hybrid.webp",
        vehicleType: "liviano",
        ivaIncluded: true,
        isHybrid: false,
        isElectric: false,
        isNew: false,
        versions: [
            {
                name: "Formentor 1.5 TSI e-Hybrid",
                motor: "1.5 TSI e-Hybrid",
                fuel: "Plug-in Hybrid",
                transmission: "DCT / DSG",
                consumptionMixed: "17.8 km/l",
                electricRange: "126 km",
                power: "204 HP",
                torque: "350 Nm",
                traction: "4x2",
                airbags: 10,
                listPrice: 40990000,
                brandBonus: 1500000,
                financingBonus: 4000000,
                bonusPrice: 35490000,
            },
        ],
        slogan: "Forget about refuelling",
        videoUrl: "CARACTER\u00cdSTICAS:",
        features: [
            {
                title: "Dise\u00f1o Din\u00e1mico",
                desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
                image: "/images/cupra/Formentor e-Hybrid/caracteristicas/asientos.webp",
            },
            {
                title: "Conducci\u00f3n Eficiente",
                desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
                image: "/images/cupra/Formentor e-Hybrid/caracteristicas/llantas.webp",
            },
            {
                title: "Tecnolog\u00edas Innovadoras",
                desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
                image: "/images/cupra/Formentor e-Hybrid/caracteristicas/limunicaion-led.webp",
            },
        ],
        gallery: [
            "/images/cupra/Formentor e-Hybrid/galeria/CUPRA-FORMENTOR-PA-007-copy2.webp",
            "/images/cupra/Formentor e-Hybrid/galeria/CUPRA-FORMENTOR-PA-037-copy1.webp",
            "/images/cupra/Formentor e-Hybrid/galeria/CUPRA-FORMENTOR-PA-127-copy1.webp",
            "/images/cupra/Formentor e-Hybrid/galeria/CUPRA-FORMENTOR-PA-168-copy1.webp",
        ],
        desktopBanner: "/images/cupra/Formentor e-Hybrid/banner/banner.webp",
    },
    //     {
    //         id: "le\u00f3n",
    //         brand: "cupra",
    //         name: "Le\u00f3n",
    //         category: "Hatchback, Híbrido",
    //         price: 27990000,
    //         image: "/images/cupra/Le\u00f3n/leon.webp",
    //         vehicleType: "liviano",
    //         ivaIncluded: true,
    //         isHybrid: true,
    //         isElectric: false,
    //         isNew: false,
    //         versions: [
    //             {
    //             name: "Cupra Leon 1.5 TSI mHEV AT | Colores Cat A",
    //             motor: "1.5 TSI mHEV",
    //             fuel: "H\u00edbrido",
    //             transmission: "DCT / DSG",
    //             consumptionMixed: "14.5 km/l",
    //             power: "150 HP",
    //             torque: "250 Nm",
    //             traction: "4x2",
    //             listPrice: 31490000,
    //             brandBonus: 1000000,
    //             financingBonus: 2500000,
    //             bonusPrice: 27990000,
    //         },
    //             {
    //             name: "Cupra Leon 1.5 TSI mHEV AT | Colores Cat B",
    //             motor: "1.5 TSI mHEV",
    //             fuel: "H\u00edbrido",
    //             transmission: "DCT / DSG",
    //             consumptionMixed: "14.5 km/l",
    //             power: "150 HP",
    //             torque: "250 Nm",
    //             traction: "4x2",
    //             listPrice: 31490000,
    //             brandBonus: 300000,
    //             financingBonus: 2500000,
    //             bonusPrice: 28690000,
    //         },
    //             {
    //             name: "Cupra Leon VZ 2.0 TSI AT",
    //             motor: "2.0 TSI",
    //             fuel: "Gasolina",
    //             transmission: "DCT / DSG",
    //             consumptionMixed: "12.5 km/l",
    //             power: "300 HP",
    //             torque: "400 Nm",
    //             traction: "4x2",
    //             listPrice: 40490000,
    //             brandBonus: 700000,
    //             financingBonus: 1900000,
    //             bonusPrice: 37890000,
    //         },
    //             {
    //             name: "Cupra Leon VZ 2.0 TSI AT | Pintura Mate + Llantas Cobre",
    //             motor: "2.0 TSI",
    //             fuel: "Gasolina",
    //             transmission: "DCT / DSG",
    //             consumptionMixed: "12.5 km/l",
    //             power: "300 HP",
    //             torque: "400 Nm",
    //             traction: "4x2",
    //             listPrice: 43490000,
    //             brandBonus: 700000,
    //             financingBonus: 1900000,
    //             bonusPrice: 40890000,
    //         },
    //         ],
    //         slogan: "Despierta tus sentidos",
    //         videoUrl: "CARACTER\u00cdSTICAS:",
    //         features: [
    //             {
    //             title: "Dise\u00f1o Din\u00e1mico",
    //             desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
    //             image: "/images/cupra/Le\u00f3n/caracteristicas/cargador-inalambrico.webp",
    //         },
    //             {
    //             title: "Conducci\u00f3n Eficiente",
    //             desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
    //             image: "/images/cupra/Le\u00f3n/caracteristicas/placa-iluminada.webp",
    //         },
    //             {
    //             title: "Tecnolog\u00edas Innovadoras",
    //             desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
    //             image: "/images/cupra/Le\u00f3n/caracteristicas/asientos-bucket.webp",
    //         },
    //         ],
    //         gallery: [
    //             "/images/cupra/Le\u00f3n/galeria/CUPRA-LEON-PA-011.webp",
    //             "/images/cupra/Le\u00f3n/galeria/CUPRA-LEON-PA-031-copy1.webp",
    //             "/images/cupra/Le\u00f3n/galeria/CUPRA-LEON-PA-031.webp",
    //             "/images/cupra/Le\u00f3n/galeria/CUPRA-LEON-PA-037.webp",
    //             "/images/cupra/Le\u00f3n/galeria/CUPRA-LEON-PA-102.webp",
    //             "/images/cupra/Le\u00f3n/galeria/cupra-leon-2025-obsession-por-la-ciudad.webp",
    //         ],
    //         desktopBanner: "/images/cupra/Le\u00f3n/banner/banner.webp",
    //     },
    {
        id: "tavascan",
        brand: "cupra",
        name: "Tavascan",
        category: "Eléctrico, SUV",
        price: 47990000,
        image: "/images/cupra/Tavascan/tavascan.webp",
        vehicleType: "liviano",
        ivaIncluded: true,
        isHybrid: false,
        isElectric: true,
        isNew: false,
        versions: [
            {
                name: "Tavascan Adrenaline 82 kWh",
                motor: "Motor El\u00e9ctrico",
                fuel: "El\u00e9ctrico",
                transmission: "Autom\u00e1tica",
                consumptionMixed: "16.8 kWh/100km",
                electricRange: "569 km",
                power: "286 HP",
                torque: "545 Nm",
                traction: "4x2",
                airbags: 7,
                listPrice: 50990000,
                brandBonus: 1000000,
                financingBonus: 2000000,
                bonusPrice: 47990000,
            },
            {
                name: "Tavascan Extreme 82 kWh",
                motor: "Motor El\u00e9ctrico",
                fuel: "El\u00e9ctrico",
                transmission: "Autom\u00e1tica",
                consumptionMixed: "17.2 kWh/100km",
                electricRange: "569 km",
                power: "286 HP",
                torque: "545 Nm",
                traction: "4x2",
                airbags: 7,
                listPrice: 53990000,
                brandBonus: 1000000,
                financingBonus: 2000000,
                bonusPrice: 50990000,
            },
            {
                name: "Tavascan Extreme 82 kWh | Pintura Mate",
                motor: "Motor El\u00e9ctrico",
                fuel: "El\u00e9ctrico",
                transmission: "Autom\u00e1tica",
                consumptionMixed: "17.2 kWh/100km",
                electricRange: "569 km",
                power: "286 HP",
                torque: "545 Nm",
                traction: "4x2",
                airbags: 7,
                listPrice: 55490000,
                brandBonus: 1000000,
                financingBonus: 2000000,
                bonusPrice: 52490000,
            },
        ],
        slogan: "La tribu se enciende",
        videoUrl: "CARACTER\u00cdSTICAS:",
        features: [
            {
                title: "Dise\u00f1o Din\u00e1mico",
                desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
                image: "/images/cupra/Tavascan/caracteristicas/asientos.webp",
            },
            {
                title: "Conducci\u00f3n Eficiente",
                desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
                image: "/images/cupra/Tavascan/caracteristicas/atmosfera.webp",
            },
            {
                title: "Tecnolog\u00edas Innovadoras",
                desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
                image: "/images/cupra/Tavascan/caracteristicas/centro-de-todo.webp",
            },
        ],
        gallery: [
            "/images/cupra/Tavascan/galeria/CUPRA-TAVASCAN-015.webp",
            "/images/cupra/Tavascan/galeria/CUPRA-TAVASCAN-019.webp",
            "/images/cupra/Tavascan/galeria/CUPRA-TAVASCAN-074.webp",
            "/images/cupra/Tavascan/galeria/CUPRA-TAVASCAN-133-copy1.webp",
            "/images/cupra/Tavascan/galeria/cupra-tavascan-2024-black-and-copper-wheel.webp",
            "/images/cupra/Tavascan/galeria/new-electric-cupra-rear-lighting-2024.webp",
        ],
        desktopBanner: "/images/cupra/Tavascan/banner/Ajuste-CUPRA-TAVASCAN-052.webp",
    },
    {
        id: "terramar",
        brand: "cupra",
        name: "Terramar",
        category: "Híbrido, SUV",
        price: 37390000,
        image: "/images/cupra/Terramar/terramar.webp",
        vehicleType: "liviano",
        ivaIncluded: true,
        isHybrid: true,
        isElectric: false,
        isNew: false,
        versions: [
            {
                name: "Terramar 1.5 TSI mHEV AT",
                motor: "1.5 TSI mHEV",
                fuel: "H\u00edbrido",
                transmission: "DCT / DSG",
                consumptionMixed: "14.2 km/l",
                electricRange: "1078 km",
                power: "150 HP",
                torque: "250 Nm",
                traction: "4x2",
                airbags: 6,
                listPrice: 39990000,
                brandBonus: 800000,
                financingBonus: 1800000,
                bonusPrice: 37390000,
            },
            {
                name: "Terramar High 1.5 TSI mHEV AT",
                motor: "1.5 TSI mHEV",
                fuel: "H\u00edbrido",
                transmission: "DCT / DSG",
                consumptionMixed: "14.2 km/l",
                electricRange: "1078 km",
                power: "150 HP",
                torque: "250 Nm",
                traction: "4x2",
                airbags: 6,
                listPrice: 43990000,
                brandBonus: 800000,
                financingBonus: 1300000,
                bonusPrice: 41890000,
            },
            {
                name: "Terramar High 1.5 TSI mHEV AT | Pintura Mate",
                motor: "1.5 TSI mHEV",
                fuel: "H\u00edbrido",
                transmission: "DCT / DSG",
                consumptionMixed: "14.2 km/l",
                electricRange: "1078 km",
                power: "150 HP",
                torque: "250 Nm",
                traction: "4x2",
                airbags: 6,
                listPrice: 45490000,
                brandBonus: 800000,
                financingBonus: 1300000,
                bonusPrice: 43390000,
            },
        ],
        slogan: "ser segundo no es opci\u00f3n",
        videoUrl: "CARACTER\u00cdSTICAS:",
        features: [
            {
                title: "Dise\u00f1o Din\u00e1mico",
                desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
                image: "/images/cupra/Terramar/caracteristicas/asientos.webp",
            },
            {
                title: "Conducci\u00f3n Eficiente",
                desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
                image: "/images/cupra/Terramar/caracteristicas/perfeccion.webp",
            },
            {
                title: "Tecnolog\u00edas Innovadoras",
                desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
                image: "/images/cupra/Terramar/caracteristicas/radio.webp",
            },
        ],
        gallery: [
            "/images/cupra/Terramar/galeria/CUPRA-TERRAMAR-126-Normal.webp",
            "/images/cupra/Terramar/galeria/CUPRA-TERRAMAR-140.webp",
        ],
        desktopBanner: "/images/cupra/Terramar/banner/CUPRA-TERRAMAR-114.webp",
    },
];
