import { Vehicle } from './types';

export const CUPRA_MODELS: Vehicle[] = [
    {
        id: 'leon',
        brand: 'cupra',
        name: 'Leon',
        category: 'Hatchback',
        price: 26990000,
        image: '/images/cupra/leon.webp',
        isHybrid: false,
        isNew: false,
        slogan: 'El pulso de una nueva era',
    },
    {
        id: 'formentor',
        brand: 'cupra',
        name: 'Formentor',
        category: 'SUV',
        price: 29990000,
        image: '/images/cupra/formentor.webp',
        isHybrid: false,
        isNew: false,
        slogan: 'Pura adrenalina',
    },
    {
        id: 'formentor-ehybrid',
        brand: 'cupra',
        name: 'Formentor e-Hybrid',
        category: 'SUV',
        price: 35990000,
        image: '/images/cupra/formentor e-hybrid.webp',
        isHybrid: true,
        isNew: false,
        slogan: 'Potencia electrificada',
    },
    {
        id: 'terramar',
        brand: 'cupra',
        name: 'Terramar',
        category: 'SUV',
        price: 38990000,
        image: '/images/cupra/terramar.webp',
        isHybrid: true,
        isNew: true,
        slogan: 'El nuevo SUV de CUPRA',
    },
    {
        id: 'tavascan',
        brand: 'cupra',
        name: 'Tavascan',
        category: 'SUV',
        price: 45990000,
        image: '/images/cupra/tavascan.webp',
        isElectric: true,
        isNew: true,
        slogan: 'Un sueño hecho realidad',
    }
];
