import { Vehicle } from './types';

export const HONDA_MODELS: Vehicle[] = [
    {
        id: "civic",
        brand: "honda",
        name: "Civic",
        category: "Sedán",
        price: 29990000,
        image: "/images/honda/CIVIC/min.webp",
        vehicleType: "liviano",
        ivaIncluded: true,
        isHybrid: false,
        isElectric: false,
        isNew: false,
        versions: [
            {
                name: "TOURING CVT 1.5T",
                motor: "1.5T",
                fuel: "Gasolina",
                transmission: "CVT",
                power: "176 HP",
                traction: "4x2",
                listPrice: 31390000,
                brandBonus: 0,
                financingBonus: 1400000,
                bonusPrice: 29990000,
            },
        ],
        slogan: "El legado contin\u00faa",
        videoUrl: "CARACTER\u00cdSTICAS:",
        features: [
            {
                title: "Dise\u00f1o Din\u00e1mico",
                desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
                image: "/images/honda/CIVIC/caracteristicas/vsa.jpg",
            },
            {
                title: "Conducci\u00f3n Eficiente",
                desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
                image: "/images/honda/CIVIC/caracteristicas/motor.webp",
            },
            {
                title: "Tecnolog\u00edas Innovadoras",
                desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
                image: "/images/honda/CIVIC/caracteristicas/pantalla-tactil.jpg",
            },
        ],
        gallery: [
            "/images/honda/CIVIC/galeria/1.webp",
            "/images/honda/CIVIC/galeria/2.jpg",
            "/images/honda/CIVIC/galeria/3.webp",
            "/images/honda/CIVIC/galeria/4.jpg",
            "/images/honda/CIVIC/galeria/5.webp",
        ],
        desktopBanner: "/images/honda/CIVIC/banner/desktop.webp",
    },
    {
        id: "cr-v",
        brand: "honda",
        name: "CR-V",
        category: "SUV",
        price: 39990000,
        image: "/images/honda/CR-V/min.webp",
        vehicleType: "liviano",
        ivaIncluded: true,
        isHybrid: false,
        isElectric: false,
        isNew: false,
        versions: [
            {
                name: "Touring 1.5 Turbo Aut. 4X4",
                motor: "1.5 Turbo VTEC",
                fuel: "Gasolina",
                transmission: "Autom\u00e1tica",
                power: "188 HP",
                traction: "4x4",
                listPrice: 42990000,
                brandBonus: 1000000,
                financingBonus: 2000000,
                bonusPrice: 39990000,
            },
        ],
        slogan: "Liderazgo en movimiento",
        videoUrl: "CARACTER\u00cdSTICAS:",
        features: [
            {
                title: "Dise\u00f1o Din\u00e1mico",
                desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
                image: "/images/honda/CR-V/caracteristicas/RENDIMIENTO.webp",
            },
            {
                title: "Conducci\u00f3n Eficiente",
                desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
                image: "/images/honda/CR-V/caracteristicas/AWD.webp",
            },
            {
                title: "Tecnolog\u00edas Innovadoras",
                desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
                image: "/images/honda/CR-V/caracteristicas/Civic-carrusel-motor-2.webp",
            },
        ],
        gallery: [
            "/images/honda/CR-V/galeria/1.webp",
            "/images/honda/CR-V/galeria/2.webp",
            "/images/honda/CR-V/galeria/3.webp",
            "/images/honda/CR-V/galeria/4.webp",
            "/images/honda/CR-V/galeria/5.jpg",
            "/images/honda/CR-V/galeria/6.webp",
            "/images/honda/CR-V/galeria/7.webp",
        ],
        desktopBanner: "/images/honda/CR-V/banner/desktop.webp",
    },
    {
        id: "cr-v-e-hev",
        brand: "honda",
        name: "CR-V e:HEV",
        category: "Híbrido, SUV",
        price: 46990000,
        image: "/images/honda/CR-V eHEV/min.webp",
        vehicleType: "liviano",
        ivaIncluded: true,
        isHybrid: true,
        isElectric: false,
        isNew: true,
        isFeatured: true,
        versions: [
            {
                name: "ADVANCE HYBRID Aut. 4X4",
                motor: "2.0L e:HEV",
                fuel: "H\u00edbrido",
                transmission: "CVT",
                power: "204 HP",
                traction: "AWD",
                listPrice: 49990000,
                brandBonus: 1000000,
                financingBonus: 2000000,
                bonusPrice: 46990000,
            },
        ],
        slogan: "Poder electrificado",
        videoUrl: "CARACTER\u00cdSTICAS:",
        features: [
            {
                title: "Dise\u00f1o Din\u00e1mico",
                desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
                image: "/images/honda/CR-V eHEV/caracteristicas/Feature_Interno_Head_UP_Display_CR_V_2024_1-copia.webp",
            },
            {
                title: "Conducci\u00f3n Eficiente",
                desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
                image: "/images/honda/CR-V eHEV/caracteristicas/Feature_Interno_Driver_Attetion_Monitor_CR_V_2024_1-copia-1.webp",
            },
            {
                title: "Tecnolog\u00edas Innovadoras",
                desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
                image: "/images/honda/CR-V eHEV/caracteristicas/Feature_Interno_Botao_Start_Stop_CR_V_2024_1-copia.webp",
            },
        ],
        gallery: [
            "/images/honda/CR-V eHEV/galeria/CRV-01.webp",
            "/images/honda/CR-V eHEV/galeria/Feature_Interno_360_interno_CR_V_2024-1-1.jpg",
            "/images/honda/CR-V eHEV/galeria/ehev-energia.webp",
            "/images/honda/CR-V eHEV/galeria/ehev-moto-electrico.webp",
            "/images/honda/CR-V eHEV/galeria/ehev-rendimiento.webp",
            "/images/honda/CR-V eHEV/galeria/ehev-unidad.webp",
        ],
        desktopBanner: "/images/honda/CR-V eHEV/banner/desktop.webp",
    },
    {
        id: "new-hr-v",
        brand: "honda",
        name: "New HR-V",
        category: "SUV",
        price: 25990000,
        image: "/images/honda/New HR-V/min.webp",
        vehicleType: "liviano",
        ivaIncluded: true,
        isHybrid: false,
        isElectric: false,
        isNew: false,
        versions: [
            {
                name: "TOURING 1.5 Aut. 4X2",
                motor: "1.5L i-VTEC",
                fuel: "Gasolina",
                transmission: "CVT",
                power: "119 HP",
                traction: "4x2",
                listPrice: 26990000,
                brandBonus: 0,
                financingBonus: 1000000,
                bonusPrice: 25990000,
            },
        ],
        slogan: "Sofisticaci\u00f3n en cada detalle",
        videoUrl: "CARACTER\u00cdSTICAS:",
        features: [
            {
                title: "Dise\u00f1o Din\u00e1mico",
                desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
            },
            {
                title: "Conducci\u00f3n Eficiente",
                desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
            },
            {
                title: "Tecnolog\u00edas Innovadoras",
                desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
            },
        ],
        gallery: [
            "/images/honda/New HR-V/galeria/1.webp",
            "/images/honda/New HR-V/galeria/2.webp",
            "/images/honda/New HR-V/galeria/3.webp",
            "/images/honda/New HR-V/galeria/4.webp",
            "/images/honda/New HR-V/galeria/5.webp",
            "/images/honda/New HR-V/galeria/6.webp",
            "/images/honda/New HR-V/galeria/7.webp",
            "/images/honda/New HR-V/galeria/8.jpg",
        ],
        desktopBanner: "/images/honda/New HR-V/banner/desktop.webp",
    },
    {
        id: "new-wr-v",
        brand: "honda",
        name: "New WR-V",
        category: "SUV",
        price: 21990000,
        image: "/images/honda/New WR-V/wrv-menu-1.webp",
        vehicleType: "liviano",
        ivaIncluded: true,
        isHybrid: false,
        isElectric: false,
        isNew: false,
        versions: [
            {
                name: "EX 1.5 Aut.",
                motor: "1.5 i-VTEC",
                fuel: "Gasolina",
                transmission: "CVT",
                power: "121 HP",
                traction: "4x2",
                listPrice: 23990000,
                brandBonus: 1000000,
                financingBonus: 1000000,
                bonusPrice: 21990000,
            },
            {
                name: "TOURING 1.5 Aut.",
                motor: "1.5 i-VTEC",
                fuel: "Gasolina",
                transmission: "CVT",
                power: "121 HP",
                traction: "4x2",
                listPrice: 24990000,
                brandBonus: 1000000,
                financingBonus: 1000000,
                bonusPrice: 22990000,
            },
        ],
        slogan: "Aventuras sin l\u00edmites",
        videoUrl: "CARACTER\u00cdSTICAS:",
        features: [
            {
                title: "Dise\u00f1o Din\u00e1mico",
                desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
                image: "/images/honda/New WR-V/caracteristicas/seguridad-1.webp",
            },
            {
                title: "Conducci\u00f3n Eficiente",
                desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
                image: "/images/honda/New WR-V/caracteristicas/sensores.webp",
            },
            {
                title: "Tecnolog\u00edas Innovadoras",
                desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
                image: "/images/honda/New WR-V/caracteristicas/hsa.webp",
            },
        ],
        gallery: [
            "/images/honda/New WR-V/galeria/perf-1.webp",
            "/images/honda/New WR-V/galeria/perf-2.webp",
            "/images/honda/New WR-V/galeria/perf-3.webp",
            "/images/honda/New WR-V/galeria/perf-4.webp",
        ],
        desktopBanner: "/images/honda/New WR-V/banner/Precio-_-Cuota-26-de-Marzo_WRV-Desktop-1-scaled.webp",
    },
    {
        id: "pilot",
        brand: "honda",
        name: "Pilot",
        category: "SUV",
        price: 56990000,
        image: "/images/honda/PILOT/min.webp",
        vehicleType: "liviano",
        ivaIncluded: true,
        isHybrid: false,
        isElectric: false,
        isNew: false,
        versions: [
            {
                name: "PILOT TOURING 3.5 (10) Aut. 4X4",
                motor: "V6 3.5L",
                fuel: "Gasolina",
                transmission: "Autom\u00e1tica",
                power: "285 HP",
                traction: "4x4",
                listPrice: 59990000,
                brandBonus: 2000000,
                financingBonus: 1000000,
                bonusPrice: 56990000,
            },
            {
                name: "PILOT ELITE 3.5 (10) Aut. 4X4",
                motor: "V6 3.5L",
                fuel: "Gasolina",
                transmission: "Autom\u00e1tica",
                power: "285 HP",
                traction: "4x4",
                listPrice: 61990000,
                brandBonus: 2000000,
                financingBonus: 1000000,
                bonusPrice: 58990000,
            },
        ],
        slogan: "Espacio para grandes momentos",
        videoUrl: "CARACTER\u00cdSTICAS:",
        features: [
            {
                title: "Dise\u00f1o Din\u00e1mico",
                desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
                image: "/images/honda/PILOT/caracteristicas/Pilot-carrusel-seguridad-web-1.jpg",
            },
            {
                title: "Conducci\u00f3n Eficiente",
                desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
                image: "/images/honda/PILOT/caracteristicas/monitor-transito.jpg",
            },
            {
                title: "Tecnolog\u00edas Innovadoras",
                desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
                image: "/images/honda/PILOT/caracteristicas/sistema-ciego.jpg",
            },
        ],
        gallery: [
            "/images/honda/PILOT/galeria/Pilot-carrusel-performance-web-1.jpg",
            "/images/honda/PILOT/galeria/Pilot-carrusel-performance-web-2.jpg",
            "/images/honda/PILOT/galeria/Pilot-carrusel-performance-web-3.jpg",
            "/images/honda/PILOT/galeria/Pilot-carrusel-performance-web-4.jpg",
            "/images/honda/PILOT/galeria/Pilot-carrusel-tecnologia-web-1.jpg",
            "/images/honda/PILOT/galeria/Pilot-carrusel-tecnologia-web-2.jpg",
            "/images/honda/PILOT/galeria/Pilot-carrusel-tecnologia-web-3.jpg",
        ],
        desktopBanner: "/images/honda/PILOT/banner/desktop.webp",
    },
    {
        id: "zr-v",
        brand: "honda",
        name: "ZR-V",
        category: "SUV",
        price: 29490000,
        image: "/images/honda/ZR-V/min.webp",
        vehicleType: "liviano",
        ivaIncluded: true,
        isHybrid: false,
        isElectric: false,
        isNew: false,
        versions: [
            {
                name: "EXL 2.0 Aut. 4X2",
                motor: "2.0L",
                fuel: "Gasolina",
                transmission: "CVT",
                power: "155 HP",
                traction: "4x2",
                listPrice: 31990000,
                brandBonus: 1000000,
                financingBonus: 1500000,
                bonusPrice: 29490000,
            },
            {
                name: "TOURING 2.0 Aut. 4X2",
                motor: "2.0L",
                fuel: "Gasolina",
                transmission: "CVT",
                power: "155 HP",
                traction: "4x2",
                listPrice: 33490000,
                brandBonus: 1500000,
                financingBonus: 1500000,
                bonusPrice: 30490000,
            },
        ],
        slogan: "Sofisticaci\u00f3n deportiva",
        videoUrl: "CARACTER\u00cdSTICAS:",
        features: [
            {
                title: "Dise\u00f1o Din\u00e1mico",
                desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
                image: "/images/honda/ZR-V/caracteristicas/asistencia-cambio-carril.jpg",
            },
            {
                title: "Conducci\u00f3n Eficiente",
                desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
                image: "/images/honda/ZR-V/caracteristicas/control-crucero.jpg",
            },
            {
                title: "Tecnolog\u00edas Innovadoras",
                desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
                image: "/images/honda/ZR-V/caracteristicas/salida-carril.jpg",
            },
        ],
        gallery: [
            "/images/honda/ZR-V/galeria/1.jpg",
            "/images/honda/ZR-V/galeria/2.jpg",
            "/images/honda/ZR-V/galeria/3.jpg",
            "/images/honda/ZR-V/galeria/4.jpg",
            "/images/honda/ZR-V/galeria/ZRV-carrusel-confort-2.jpg",
            "/images/honda/ZR-V/galeria/ZRV-carrusel-confort-3.jpg",
            "/images/honda/ZR-V/galeria/ZRV-carrusel-confort-web-4.jpg",
            "/images/honda/ZR-V/galeria/ZRV-carrusel-confort-web-verdadera4.jpg",
            "/images/honda/ZR-V/galeria/ZRV-carrusel-diseno-web-3.jpg",
            "/images/honda/ZR-V/galeria/ZRV-carrusel-diseno-web-4.jpg",
            "/images/honda/ZR-V/galeria/ZRV-carrusel-diseno-web-6.jpg",
        ],
        desktopBanner: "/images/honda/ZR-V/banner/desktop.webp",
    },
];
