import { Vehicle } from './types';

export const HONDA_MODELS: Vehicle[] = [
    {
        id: "civic",
        brand: "honda",
        name: "Civic",
        category: "Sedán",
        price: 29990000,
        image: "/images/honda/CIVIC/min.webp",
        vehicleType: "liviano",
        ivaIncluded: true,
        isHybrid: false,
        isElectric: false,
        isNew: false,
        versions: [
            {
                name: "TOURING CVT 1.5T",
                motor: "1.5T",
                fuel: "Gasolina",
                transmission: "CVT",
                power: "176 HP",
                traction: "4x2",
                listPrice: 31390000,
                brandBonus: 0,
                financingBonus: 1400000,
                bonusPrice: 29990000,
            },
        ],
        slogan: "El legado continúa",
        videoUrl: "CARACTERÍSTICAS:",
        features: [
            {
                title: "Estabilizador VSA",
                desc: "El Civic está equipado con un sistema estabilizador de Vehículo (VSA), control de tracción, que equilibra automáticamente la atracción y el frenado de forma dinámica e independiente, lo que optimiza una seguridad absoluta en cualquier situación.",
                image: "/images/honda/CIVIC/caracteristicas/vsa.jpg",
            },
            {
                title: "Motor DOHC I-VTEC ®",
                desc: "La nueva generación de Civic posee un motor TURBO de 1.5L en aleación de aluminio y 16 válvulas DOHC I-VTEC en todas sus versiones.",
                image: "/images/honda/CIVIC/caracteristicas/motor.webp",
            },
            {
                title: "Diseño del panel interior minimalista",
                desc: "Acá se cumple la premisa de “menos es más” cuidando el exceso de elementos con la simpleza del diseño, con mayores funciones para aumentar la comodidad y seguridad del conductor y los pasajeros. *Disponible en versión Touring.",
                image: "/images/honda/CIVIC/caracteristicas/pantalla-tactil.jpg",
            },
        ],
        gallery: [
            "/images/honda/CIVIC/galeria/1.webp",
            "/images/honda/CIVIC/galeria/2.jpg",
            "/images/honda/CIVIC/galeria/3.webp",
            "/images/honda/CIVIC/galeria/4.jpg",
            "/images/honda/CIVIC/galeria/5.webp",
        ],
        desktopBanner: "/images/honda/CIVIC/banner/desktop.webp",
    },
    {
        id: "cr-v",
        brand: "honda",
        name: "CR-V",
        category: "SUV",
        price: 39990000,
        image: "/images/honda/CR-V/min.webp",
        vehicleType: "liviano",
        ivaIncluded: true,
        isHybrid: false,
        isElectric: false,
        isNew: false,
        versions: [
            {
                name: "Touring 1.5 Turbo Aut. 4X4",
                motor: "1.5 Turbo VTEC",
                fuel: "Gasolina",
                transmission: "Automática",
                power: "188 HP",
                traction: "4x4",
                listPrice: 42990000,
                brandBonus: 1000000,
                financingBonus: 2000000,
                bonusPrice: 39990000,
            },
        ],
        slogan: "Liderazgo en movimiento",
        videoUrl: "CARACTERÍSTICAS:",
        features: [
            {
                title: "Una experiencia renovada para una mejor aventura",
                desc: "El diseño minimalista e inteligente de la consola central más grande del CR-V permite una mejor distribución del espacio en el interior del vehículo, lo que se traduce en una experiencia de manejo más cómoda y agradable.",
                image: "/images/honda/CR-V/caracteristicas/RENDIMIENTO.webp",
            },
            {
                title: "Desafía nuevos caminos",
                desc: "¿Quieres un vehículo que pueda superar cualquier obstáculo? El sistema Honda Real Time All-Wheel Drive (AWD) es la respuesta. Con su tecnología innovadora, te brinda una tracción, control y rendimiento sin igual.",
                image: "/images/honda/CR-V/caracteristicas/AWD.webp",
            },
            {
                title: "Motor 1.5 Turbo VTEC",
                desc: "El equilibrio justo entre potencia y eficiencia del motor, lo encontrarás en este eficiente motor 1.5 Turbo VTEC.",
                image: "/images/honda/CR-V/caracteristicas/Civic-carrusel-motor-2.webp",
            },
        ],
        gallery: [
            "/images/honda/CR-V/galeria/1.webp",
            "/images/honda/CR-V/galeria/2.webp",
            "/images/honda/CR-V/galeria/3.webp",
            "/images/honda/CR-V/galeria/4.webp",
            "/images/honda/CR-V/galeria/5.jpg",
            "/images/honda/CR-V/galeria/6.webp",
            "/images/honda/CR-V/galeria/7.webp",
        ],
        desktopBanner: "/images/honda/CR-V/banner/desktop.webp",
    },
    {
        id: "cr-v-e-hev",
        brand: "honda",
        name: "CR-V e:HEV",
        category: "Híbrido, SUV",
        price: 46990000,
        image: "/images/honda/CR-V eHEV/min.webp",
        vehicleType: "liviano",
        ivaIncluded: true,
        isHybrid: true,
        isElectric: false,
        isNew: true,
        isFeatured: false,
        versions: [
            {
                name: "ADVANCE HYBRID Aut. 4X4",
                motor: "2.0L e:HEV",
                fuel: "Híbrido",
                transmission: "CVT",
                power: "204 HP",
                traction: "AWD",
                listPrice: 49990000,
                brandBonus: 1000000,
                financingBonus: 2000000,
                bonusPrice: 46990000,
            },
        ],
        slogan: "Poder electrificado",
        videoUrl: "CARACTERÍSTICAS:",
        features: [
            {
                title: "HEAD UP DISPLAY",
                desc: "Proyección de información en el parabrisas, brindando mayor comodidad, agilidad y seguridad al leer las principales informaciones del panel",
                image: "/images/honda/CR-V eHEV/caracteristicas/1.webp",
            },
            {
                title: "PANEL DIGITAL TFT DE 10,2\"",
                desc: "El panel digital de 10,2″ de alta definición , garantiza una lectura de información ágil y sencilla.",
                image: "/images/honda/CR-V eHEV/caracteristicas/2.webp",
            },
            {
                title: "START / STOP",
                desc: "El encendido del motor se realiza con un simple toque en el botón Start/Stop, requiriendo únicamente la presencia de las llaves.",
                image: "/images/honda/CR-V eHEV/caracteristicas/3.webp",
            },
            {
                title: "PANTALLA MULTIMEDIA DE 9”",
                desc: "Pantalla táctil de 9´´, con Android auto y Apple CarPlay, para una navegación amigable e intuitiva.",
                image: "/images/honda/CR-V eHEV/caracteristicas/4.webp",
            },
        ],
        gallery: [
            "/images/honda/CR-V eHEV/galeria/CRV-01.webp",
            "/images/honda/CR-V eHEV/galeria/Feature_Interno_360_interno_CR_V_2024-1-1.jpg",
            "/images/honda/CR-V eHEV/galeria/ehev-energia.webp",
            "/images/honda/CR-V eHEV/galeria/ehev-moto-electrico.webp",
            "/images/honda/CR-V eHEV/galeria/ehev-rendimiento.webp",
            "/images/honda/CR-V eHEV/galeria/ehev-unidad.webp",
        ],
        desktopBanner: "/images/honda/CR-V eHEV/banner/desktop.webp",
    },
    {
        id: "new-hr-v",
        brand: "honda",
        name: "New HR-V",
        category: "SUV",
        price: 25990000,
        image: "/images/honda/New HR-V/min.webp",
        vehicleType: "liviano",
        ivaIncluded: true,
        isHybrid: false,
        isElectric: false,
        isNew: false,
        versions: [
            {
                name: "TOURING 1.5 Aut. 4X2",
                motor: "1.5L i-VTEC",
                fuel: "Gasolina",
                transmission: "CVT",
                power: "119 HP",
                traction: "4x2",
                listPrice: 26990000,
                brandBonus: 0,
                financingBonus: 1000000,
                bonusPrice: 25990000,
            },
        ],
        slogan: "Sofisticación en cada detalle",
        videoUrl: "CARACTERÍSTICAS:",
        features: [
            {
                title: "Más comodidad",
                desc: "El Nuevo Honda HR-V integra avanzadas prestaciones de innovación y tecnología, junto con un espacio interior líder en su segmento, que redefine la comodidad a bordo.",
                image: "/images/honda/New HR-V/caracteristicas/1.webp",
            },
            {
                title: "Apoya brazos central",
                desc: "El apoya brazos central de los asientos delanteros no solo reduce la fatiga en viajes largos, sino que también proporciona una mayor comodidad, estabilidad y ergonomía.",
                image: "/images/honda/New HR-V/caracteristicas/2.jpg",
            },
            {
                title: "Cámara trasera con multivista",
                desc: "La cámara de marcha atrás multivista tiene guías de referencia dinámicas para ayudarte mejor durante las maniobras y garantizar la seguridad.",
                image: "/images/honda/New HR-V/caracteristicas/3.webp",
            },
        ],
        gallery: [
            "/images/honda/New HR-V/galeria/1.webp",
            "/images/honda/New HR-V/galeria/2.webp",
            "/images/honda/New HR-V/galeria/3.webp",
            "/images/honda/New HR-V/galeria/4.webp",
            "/images/honda/New HR-V/galeria/5.webp",
            "/images/honda/New HR-V/galeria/6.webp",
            "/images/honda/New HR-V/galeria/7.webp",
            "/images/honda/New HR-V/galeria/8.jpg",
        ],
        desktopBanner: "/images/honda/New HR-V/banner/desktop.webp",
    },
    {
        id: "new-wr-v",
        brand: "honda",
        name: "New WR-V",
        category: "SUV",
        price: 21990000,
        image: "/images/honda/New WR-V/wrv-menu-1.webp",
        vehicleType: "liviano",
        ivaIncluded: true,
        isHybrid: false,
        isElectric: false,
        isNew: false,
        versions: [
            {
                name: "EX 1.5 Aut.",
                motor: "1.5 i-VTEC",
                fuel: "Gasolina",
                transmission: "CVT",
                power: "121 HP",
                traction: "4x2",
                listPrice: 23990000,
                brandBonus: 1000000,
                financingBonus: 1000000,
                bonusPrice: 21990000,
            },
            {
                name: "TOURING 1.5 Aut.",
                motor: "1.5 i-VTEC",
                fuel: "Gasolina",
                transmission: "CVT",
                power: "121 HP",
                traction: "4x2",
                listPrice: 24990000,
                brandBonus: 1000000,
                financingBonus: 1000000,
                bonusPrice: 22990000,
            },
        ],
        slogan: "Aventuras sin límites",
        videoUrl: "CARACTERÍSTICAS:",
        features: [
            {
                title: "6 Airbags",
                desc: "El WR-V incorpora 6 airbags distribuidos estratégicamente para proteger a todos los ocupantes: frontales, laterales y de cortina. Un sistema pensado para brindar mayor seguridad en diferentes tipos de impacto y acompañarte con tranquilidad en cada viaje.",
                image: "/images/honda/New WR-V/caracteristicas/1.webp",
            },
            {
                title: "Asistente en Pendiente HSA",
                desc: "El sistema HSA ayuda a mantener el vehículo detenido por algunos segundos al arrancar en una pendiente, evitando que retroceda y dándote mayor control y confianza al maniobrar.",
                image: "/images/honda/New WR-V/caracteristicas/2.webp",
            },
            {
                title: "Sensores de estacionamiento",
                desc: "Los sensores traseros facilitan maniobras en espacios reducidos, alertando sobre obstáculos y ayudando a estacionar con mayor seguridad y precisión.",
                image: "/images/honda/New WR-V/caracteristicas/3.webp",
            },
        ],
        gallery: [
            "/images/honda/New WR-V/galeria/1.webp",
            "/images/honda/New WR-V/galeria/2.webp",
            "/images/honda/New WR-V/galeria/4.webp",
            "/images/honda/New WR-V/galeria/5.webp",
            "/images/honda/New WR-V/galeria/6.webp",
            "/images/honda/New WR-V/galeria/7.webp",
            "/images/honda/New WR-V/galeria/8.webp",
        ],
        desktopBanner: "/images/honda/New WR-V/banner/Precio-_-Cuota-26-de-Marzo_WRV-Desktop-1-scaled.webp",
    },
    {
        id: "pilot",
        brand: "honda",
        name: "Pilot",
        category: "SUV",
        price: 56990000,
        image: "/images/honda/PILOT/min.webp",
        vehicleType: "liviano",
        ivaIncluded: true,
        isHybrid: false,
        isElectric: false,
        isNew: false,
        versions: [
            {
                name: "PILOT TOURING 3.5 (10) Aut. 4X4",
                motor: "V6 3.5L",
                fuel: "Gasolina",
                transmission: "Automática",
                power: "285 HP",
                traction: "4x4",
                listPrice: 59990000,
                brandBonus: 2000000,
                financingBonus: 1000000,
                bonusPrice: 56990000,
            },
            {
                name: "PILOT ELITE 3.5 (10) Aut. 4X4",
                motor: "V6 3.5L",
                fuel: "Gasolina",
                transmission: "Automática",
                power: "285 HP",
                traction: "4x4",
                listPrice: 61990000,
                brandBonus: 2000000,
                financingBonus: 1000000,
                bonusPrice: 58990000,
            },
        ],
        slogan: "Espacio para grandes momentos",
        videoUrl: "CARACTERÍSTICAS:",
        features: [
            {
                title: "Estructura de la carrocería con tecnología ACE",
                desc: "La carrocería, con ingeniería de compatibilidad avanzada (Advanced Compatibility Engineering™, ACE™), consiste en un diseño exclusivo de Honda que mejora la protección a los pasajeros. El diseño ACE utiliza una red de elementos estructurales conectados que distribuye la energía de un choque frontal de manera más uniforme.",
                image: "/images/honda/PILOT/caracteristicas/1.jpg",
            },
            {
                title: "Monitor de transito cruzado",
                desc: "El sistema de información de puntos ciegos también incluye el monitor de tránsito cruzado, que usa sensores en la parte trasera del vehículo puede ayudar a alertarlo respecto de vehículos detectados que se aproximan cuando retrocede. *Imágenes referenciales, colores y versiones pueden variar.",
                image: "/images/honda/PILOT/caracteristicas/2.jpg",
            },
            {
                title: "Sistema de información de puntos ciegos",
                desc: "El sistema de información de puntos ciegos usa sensores de radar para detectar la presencia de vehículos a los lados y detrás de su vehículo, para ayudarlo durante los cambios de carril. Los indicadores de advertencia en los espejos laterales te avisan si el sistema detecta un vehículo.",
                image: "/images/honda/PILOT/caracteristicas/3.jpg",
            },
        ],
        gallery: [
            "/images/honda/PILOT/galeria/1.jpg",
            "/images/honda/PILOT/galeria/2.jpg",
            "/images/honda/PILOT/galeria/3.jpg",
            "/images/honda/PILOT/galeria/4.jpg",
            "/images/honda/PILOT/galeria/5.jpg",
            "/images/honda/PILOT/galeria/6.jpg",
            "/images/honda/PILOT/galeria/7.jpg",
        ],
        desktopBanner: "/images/honda/PILOT/banner/desktop.webp",
    },
    {
        id: "zr-v",
        brand: "honda",
        name: "ZR-V",
        category: "SUV",
        price: 29490000,
        image: "/images/honda/ZR-V/min.webp",
        vehicleType: "liviano",
        ivaIncluded: true,
        isHybrid: false,
        isElectric: false,
        isNew: false,
        versions: [
            {
                name: "EXL 2.0 Aut. 4X2",
                motor: "2.0L",
                fuel: "Gasolina",
                transmission: "CVT",
                power: "155 HP",
                traction: "4x2",
                listPrice: 31990000,
                brandBonus: 1000000,
                financingBonus: 1500000,
                bonusPrice: 29490000,
            },
            {
                name: "TOURING 2.0 Aut. 4X2",
                motor: "2.0L",
                fuel: "Gasolina",
                transmission: "CVT",
                power: "155 HP",
                traction: "4x2",
                listPrice: 33490000,
                brandBonus: 1500000,
                financingBonus: 1500000,
                bonusPrice: 30490000,
            },
        ],
        slogan: "Sofisticación deportiva",
        videoUrl: "CARACTERÍSTICAS:",
        features: [
            {
                title: "Sistema de asistencia para mantenerse en el carril",
                desc: "El Sistema de Asistencia para Mantenerse en el Carril ayuda a facilitar la conducción de carretera, ya sea que se encuentre en medio del tráfico o circulando por una carretera abierta.",
                image: "/images/honda/ZR-V/caracteristicas/1.webp",
            },
            {
                title: "Control automático de crucero adaptable ACC",
                desc: "Control Automático de Crucero Adaptable es un sistema de crucero inteligente que se adapta a la velocidad de los vehículos detectados delante para que tu no tengas que hacerlo.",
                image: "/images/honda/ZR-V/caracteristicas/2.webp",
            },
            {
                title: "Sistema de mitigación de salida de carril RDM",
                desc: "Mitigacion de salida de carril cuando el vehiculo cruza el limite de la vía sin utilizar la señal de giro, el volante vibra y se muestra una señal de alerta en el tablero.",
                image: "/images/honda/ZR-V/caracteristicas/3.webp",
            },
        ],
        gallery: [
            "/images/honda/ZR-V/galeria/1.jpg",
            "/images/honda/ZR-V/galeria/2.jpg",
            "/images/honda/ZR-V/galeria/3.jpg",
            "/images/honda/ZR-V/galeria/4.jpg",
            "/images/honda/ZR-V/galeria/ZRV-carrusel-confort-2.jpg",
            "/images/honda/ZR-V/galeria/ZRV-carrusel-confort-3.jpg",
            "/images/honda/ZR-V/galeria/ZRV-carrusel-confort-web-4.jpg",
            "/images/honda/ZR-V/galeria/ZRV-carrusel-confort-web-verdadera4.jpg",
            "/images/honda/ZR-V/galeria/ZRV-carrusel-diseno-web-3.jpg",
            "/images/honda/ZR-V/galeria/ZRV-carrusel-diseno-web-4.jpg",
            "/images/honda/ZR-V/galeria/ZRV-carrusel-diseno-web-6.jpg",
        ],
        desktopBanner: "/images/honda/ZR-V/banner/desktop.webp",
    },
];