import { Vehicle } from './types';

export const HONDA_MODELS: Vehicle[] = [
    {
        id: 'civic',
        brand: 'honda',
        name: 'Honda Civic',
        category: 'Sedán',
        price: 24990000,
        image: '/images/honda/civic.webp',
        isHybrid: false,
        isNew: false,
        slogan: 'El legado continúa',
    },
    {
        id: 'wr-v',
        brand: 'honda',
        name: 'New Honda WR-V',
        category: 'SUV',
        price: 15490000,
        image: '/images/honda/New-WRV.webp',
        isHybrid: false,
        isNew: true,
        slogan: 'Aventuras sin límites',
    },
    {
        id: 'hr-v',
        brand: 'honda',
        name: 'New Honda HR-V',
        category: 'SUV',
        price: 19990000,
        image: '/images/honda/new-hr-v.webp',
        isHybrid: false,
        isNew: true,
        slogan: 'Sofisticación en cada detalle',
    },
    {
        id: 'zr-v',
        brand: 'honda',
        name: 'Honda ZR-V',
        category: 'SUV',
        price: 26990000,
        image: '/images/honda/zr-v.webp',
        isHybrid: false,
        isNew: false,
    },
    {
        id: 'cr-v',
        brand: 'honda',
        name: 'Honda CR-V',
        category: 'SUV',
        price: 31990000,
        image: '/images/honda/CR-V.webp',
        isHybrid: false,
        isNew: false,
        slogan: 'Liderazgo en movimiento',
    },
    {
        id: 'cr-v-hybrid',
        brand: 'honda',
        name: 'Honda CR-V e:HEV',
        category: 'SUV',
        price: 43990000,
        image: '/images/honda/CR-V_ehev.webp',
        isHybrid: true,
        isNew: true,
        slogan: 'Poder electrificado',
    },
    {
        id: 'pilot',
        brand: 'honda',
        name: 'Honda Pilot',
        category: 'SUV',
        price: 48990000,
        image: '/images/honda/Pilot.webp',
        isHybrid: false,
        isNew: false,
        slogan: 'Espacio para grandes momentos',
    }
];
