import { Vehicle } from './types';

export const JETOUR_MODELS: Vehicle[] = [
//     {
//         id: "dashing",
//         brand: "jetour",
//         name: "Dashing",
//         category: "SUV",
//         price: 13490000,
//         vehicleType: "liviano",
//         ivaIncluded: true,
//         isHybrid: false,
//         isElectric: false,
//         isNew: false,
//         versions: [
//             {
//             name: "6MT 1.5L Turbo Special Edition FL",
//             motor: "1.5L Turbo",
//             fuel: "Gasolina",
//             transmission: "Mec\u00e1nica",
//             power: "145 HP",
//             traction: "4x2",
//             airbags: 2,
//             listPrice: 16490000,
//             brandBonus: 2000000,
//             financingBonus: 1000000,
//             bonusPrice: 13490000,
//         },
//             {
//             name: "1.5L 6MT Turbo Lux FL",
//             motor: "1.5L Turbo",
//             fuel: "Gasolina",
//             transmission: "Mec\u00e1nica",
//             power: "145 HP",
//             traction: "4x2",
//             airbags: 4,
//             listPrice: 17490000,
//             brandBonus: 2500000,
//             financingBonus: 1000000,
//             bonusPrice: 13990000,
//         },
//             {
//             name: "6DCT 1.5L Turbo Special Edition FL",
//             motor: "1.5L Turbo",
//             fuel: "Gasolina",
//             transmission: "DCT / DSG",
//             power: "145 HP",
//             traction: "4x2",
//             airbags: 4,
//             listPrice: 18490000,
//             brandBonus: 3500000,
//             financingBonus: 1000000,
//             bonusPrice: 13990000,
//         },
//             {
//             name: "6DCT 1.5L Turbo Lux",
//             motor: "1.5L Turbo",
//             fuel: "Gasolina",
//             transmission: "DCT / DSG",
//             power: "145 HP",
//             traction: "4x2",
//             airbags: 6,
//             listPrice: 19490000,
//             brandBonus: 2500000,
//             financingBonus: 1000000,
//             bonusPrice: 15990000,
//         },
//             {
//             name: "7DCT 1.6L Turbo GDI Limited",
//             motor: "1.6L Turbo",
//             fuel: "Gasolina",
//             transmission: "DCT / DSG",
//             power: "188 HP",
//             traction: "4x2",
//             airbags: 6,
//             listPrice: 21990000,
//             brandBonus: 2500000,
//             financingBonus: 1000000,
//             bonusPrice: 18490000,
//         },
//         ],
//         slogan: "\u00daNICAMENTE DISTINGUIDO",
//         videoUrl: "CARACTER\u00cdSTICAS:",
//         features: [
//             {
//             title: "Dise\u00f1o Din\u00e1mico",
//             desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
//         },
//             {
//             title: "Conducci\u00f3n Eficiente",
//             desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
//         },
//             {
//             title: "Tecnolog\u00edas Innovadoras",
//             desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
//         },
//         ],
//     },
//     {
//         id: "t1",
//         brand: "jetour",
//         name: "T1",
//         category: "SUV",
//         price: 18990000,
//         vehicleType: "liviano",
//         ivaIncluded: true,
//         isHybrid: false,
//         isElectric: false,
//         isNew: false,
//         versions: [
//             {
//             name: "1.5T 7DCT LUXURY",
//             motor: "1.5T",
//             fuel: "Gasolina",
//             transmission: "DCT / DSG",
//             power: "167 HP",
//             traction: "4x2",
//             airbags: 6,
//             listPrice: 22990000,
//             brandBonus: 2500000,
//             financingBonus: 1500000,
//             bonusPrice: 18990000,
//         },
//             {
//             name: "1.5T 7DCT LUXURY MATE",
//             motor: "1.5T",
//             fuel: "Gasolina",
//             transmission: "DCT / DSG",
//             power: "167 HP",
//             traction: "4x2",
//             airbags: 6,
//             listPrice: 23490000,
//             brandBonus: 2500000,
//             financingBonus: 1500000,
//             bonusPrice: 19490000,
//         },
//             {
//             name: "2.0T 8AT XWD LIMITED",
//             motor: "2.0T",
//             fuel: "Gasolina",
//             transmission: "Autom\u00e1tica",
//             power: "241 HP",
//             traction: "AWD",
//             airbags: 6,
//             listPrice: 26990000,
//             brandBonus: 1500000,
//             financingBonus: 1500000,
//             bonusPrice: 23990000,
//         },
//             {
//             name: "2.0T 8AT XWD LIMITED MATE",
//             motor: "2.0T",
//             fuel: "Gasolina",
//             transmission: "Autom\u00e1tica",
//             power: "241 HP",
//             traction: "AWD",
//             airbags: 6,
//             listPrice: 27490000,
//             brandBonus: 1500000,
//             financingBonus: 1500000,
//             bonusPrice: 24490000,
//         },
//         ],
//         slogan: "Despierta tu aventura",
//         videoUrl: "CARACTER\u00cdSTICAS:",
//         features: [
//             {
//             title: "Dise\u00f1o Din\u00e1mico",
//             desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
//         },
//             {
//             title: "Conducci\u00f3n Eficiente",
//             desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
//         },
//             {
//             title: "Tecnolog\u00edas Innovadoras",
//             desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
//         },
//         ],
//     },
//     {
//         id: "t1-phev",
//         brand: "jetour",
//         name: "T1 PHEV",
//         category: "Híbrido, SUV",
//         price: 26990000,
//         vehicleType: "liviano",
//         ivaIncluded: true,
//         isHybrid: true,
//         isElectric: false,
//         isNew: false,
//         versions: [
//             {
//             name: "1.5T PHEV LIMITED",
//             motor: "1.5T PHEV",
//             fuel: "H\u00edbrido",
//             transmission: "Autom\u00e1tica",
//             electricRange: "1000 km",
//             power: "341 HP",
//             traction: "4x2",
//             airbags: 6,
//             listPrice: 29990000,
//             brandBonus: 1000000,
//             financingBonus: 2000000,
//             bonusPrice: 26990000,
//         },
//             {
//             name: "1.5T PHEV LIMITED MATE",
//             motor: "1.5T PHEV",
//             fuel: "H\u00edbrido",
//             transmission: "Autom\u00e1tica",
//             electricRange: "1000 km",
//             power: "341 HP",
//             traction: "4x2",
//             airbags: 6,
//             listPrice: 30490000,
//             brandBonus: 1000000,
//             financingBonus: 2000000,
//             bonusPrice: 27490000,
//         },
//         ],
//         slogan: "Confort, tecnolog\u00eda y seguridad",
//         videoUrl: "CARACTER\u00cdSTICAS:",
//         features: [
//             {
//             title: "Dise\u00f1o Din\u00e1mico",
//             desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
//         },
//             {
//             title: "Conducci\u00f3n Eficiente",
//             desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
//         },
//             {
//             title: "Tecnolog\u00edas Innovadoras",
//             desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
//         },
//         ],
//     },
//     {
//         id: "t2",
//         brand: "jetour",
//         name: "T2",
//         category: "SUV",
//         price: 26990000,
//         vehicleType: "liviano",
//         ivaIncluded: true,
//         isHybrid: false,
//         isElectric: false,
//         isNew: false,
//         versions: [
//             {
//             name: "2.0T GDI AWD 7DCT LIMITED",
//             motor: "2.0T",
//             fuel: "Gasolina",
//             transmission: "DCT / DSG",
//             power: "241 HP",
//             traction: "AWD",
//             airbags: 6,
//             listPrice: 29990000,
//             brandBonus: 1500000,
//             financingBonus: 1500000,
//             bonusPrice: 26990000,
//         },
//             {
//             name: "2.0T GDI AWD 7DCT LIMITED MATE",
//             motor: "2.0T",
//             fuel: "Gasolina",
//             transmission: "DCT / DSG",
//             power: "241 HP",
//             traction: "AWD",
//             airbags: 6,
//             listPrice: 30490000,
//             brandBonus: 1500000,
//             financingBonus: 1500000,
//             bonusPrice: 27490000,
//         },
//         ],
//         slogan: "VERSATILIDAD, COMODIDAD Y TECNOLOG\u00cdA",
//         videoUrl: "CARACTER\u00cdSTICAS:",
//         features: [
//             {
//             title: "Dise\u00f1o Din\u00e1mico",
//             desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
//         },
//             {
//             title: "Conducci\u00f3n Eficiente",
//             desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
//         },
//             {
//             title: "Tecnolog\u00edas Innovadoras",
//             desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
//         },
//         ],
//     },
//     {
//         id: "t2-phev",
//         brand: "jetour",
//         name: "T2 PHEV",
//         category: "Híbrido, SUV",
//         price: 34990000,
//         vehicleType: "liviano",
//         ivaIncluded: true,
//         isHybrid: true,
//         isElectric: false,
//         isNew: false,
//         versions: [
//             {
//             name: "1.5T PHEV LIMITED",
//             motor: "1.5T PHEV",
//             fuel: "H\u00edbrido",
//             transmission: "Autom\u00e1tica",
//             electricRange: "1000 km",
//             power: "375 HP",
//             traction: "4x2",
//             airbags: 6,
//             listPrice: 36990000,
//             brandBonus: 0,
//             financingBonus: 2000000,
//             bonusPrice: 34990000,
//         },
//             {
//             name: "1.5T PHEV LIMITED MATE",
//             motor: "1.5T PHEV",
//             fuel: "H\u00edbrido",
//             transmission: "Autom\u00e1tica",
//             electricRange: "1000 km",
//             power: "375 HP",
//             traction: "4x2",
//             airbags: 6,
//             listPrice: 37490000,
//             brandBonus: 0,
//             financingBonus: 2000000,
//             bonusPrice: 35490000,
//         },
//         ],
//         slogan: "Libertad, tecnolog\u00eda y seguridad",
//         videoUrl: "CARACTER\u00cdSTICAS:",
//         features: [
//             {
//             title: "Dise\u00f1o Din\u00e1mico",
//             desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
//         },
//             {
//             title: "Conducci\u00f3n Eficiente",
//             desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
//         },
//             {
//             title: "Tecnolog\u00edas Innovadoras",
//             desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
//         },
//         ],
//     },
//     {
//         id: "x50",
//         brand: "jetour",
//         name: "X50",
//         category: "SUV",
//         price: 9990000,
//         vehicleType: "liviano",
//         ivaIncluded: true,
//         isHybrid: false,
//         isElectric: false,
//         isNew: false,
//         versions: [
//             {
//             name: "1.5L MT LUX",
//             motor: "1.5L",
//             fuel: "Gasolina",
//             transmission: "Mec\u00e1nica",
//             power: "145 HP",
//             traction: "4x2",
//             airbags: 2,
//             listPrice: 12490000,
//             brandBonus: 1000000,
//             financingBonus: 1500000,
//             bonusPrice: 9990000,
//         },
//             {
//             name: "1.5T 6DCT TURBO LUX",
//             motor: "1.5T",
//             fuel: "Gasolina",
//             transmission: "DCT / DSG",
//             power: "145 HP",
//             traction: "4x2",
//             airbags: 4,
//             listPrice: 15490000,
//             brandBonus: 2000000,
//             financingBonus: 1000000,
//             bonusPrice: 12490000,
//         },
//         ],
//         slogan: "La diversi\u00f3n pasa por ti",
//         videoUrl: "CARACTER\u00cdSTICAS:",
//         features: [
//             {
//             title: "Dise\u00f1o Din\u00e1mico",
//             desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
//         },
//             {
//             title: "Conducci\u00f3n Eficiente",
//             desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
//         },
//             {
//             title: "Tecnolog\u00edas Innovadoras",
//             desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
//         },
//         ],
//     },
//     {
//         id: "x70",
//         brand: "jetour",
//         name: "X70",
//         category: "SUV",
//         price: 12490000,
//         vehicleType: "liviano",
//         ivaIncluded: true,
//         isHybrid: false,
//         isElectric: false,
//         isNew: false,
//         versions: [
//             {
//             name: "1.5T 6MT TURBO FL",
//             motor: "1.5T",
//             fuel: "Gasolina",
//             transmission: "Mec\u00e1nica",
//             power: "145 HP",
//             traction: "4x2",
//             seats: 7,
//             airbags: 6,
//             listPrice: 17490000,
//             brandBonus: 4000000,
//             financingBonus: 1000000,
//             bonusPrice: 12490000,
//         },
//             {
//             name: "1.5T 6DCT TURBO FL",
//             motor: "1.5T",
//             fuel: "Gasolina",
//             transmission: "DCT / DSG",
//             power: "145 HP",
//             traction: "4x2",
//             seats: 7,
//             airbags: 6,
//             listPrice: 19490000,
//             brandBonus: 4500000,
//             financingBonus: 1000000,
//             bonusPrice: 13990000,
//         },
//         ],
//         slogan: "SUV para 7 pasajeros",
//         videoUrl: "CARACTER\u00cdSTICAS:",
//         features: [
//             {
//             title: "Dise\u00f1o Din\u00e1mico",
//             desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
//         },
//             {
//             title: "Conducci\u00f3n Eficiente",
//             desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
//         },
//             {
//             title: "Tecnolog\u00edas Innovadoras",
//             desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
//         },
//         ],
//     },
//     {
//         id: "x70-plus",
//         brand: "jetour",
//         name: "X70 PLUS",
//         category: "SUV",
//         price: 16990000,
//         vehicleType: "liviano",
//         ivaIncluded: true,
//         isHybrid: false,
//         isElectric: false,
//         isNew: false,
//         versions: [
//             {
//             name: "1.5T 6DCT FL",
//             motor: "1.5T",
//             fuel: "Gasolina",
//             transmission: "DCT / DSG",
//             power: "145 HP",
//             traction: "4x2",
//             seats: 7,
//             airbags: 4,
//             listPrice: 20990000,
//             brandBonus: 3000000,
//             financingBonus: 1000000,
//             bonusPrice: 16990000,
//         },
//             {
//             name: "1.6T GDI 7DCT LUX FL",
//             motor: "1.6T",
//             fuel: "Gasolina",
//             transmission: "DCT / DSG",
//             power: "188 HP",
//             traction: "4x2",
//             seats: 7,
//             airbags: 6,
//             listPrice: 22490000,
//             brandBonus: 3500000,
//             financingBonus: 1000000,
//             bonusPrice: 17990000,
//         },
//         ],
//         slogan: "Disfruta en familia: SUV para 7 pasajeros",
//         videoUrl: "CARACTER\u00cdSTICAS:",
//         features: [
//             {
//             title: "Dise\u00f1o Din\u00e1mico",
//             desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
//         },
//             {
//             title: "Conducci\u00f3n Eficiente",
//             desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
//         },
//             {
//             title: "Tecnolog\u00edas Innovadoras",
//             desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
//         },
//         ],
//     },
//     {
//         id: "x90-plus",
//         brand: "jetour",
//         name: "X90 Plus",
//         category: "SUV",
//         price: 22990000,
//         vehicleType: "liviano",
//         ivaIncluded: true,
//         isHybrid: false,
//         isElectric: false,
//         isNew: false,
//         versions: [
//             {
//             name: "2.0T GDI 7DCT",
//             motor: "2.0T",
//             fuel: "Gasolina",
//             transmission: "DCT / DSG",
//             power: "241 HP",
//             traction: "4x2",
//             seats: 7,
//             airbags: 6,
//             listPrice: 27490000,
//             brandBonus: 3000000,
//             financingBonus: 1500000,
//             bonusPrice: 22990000,
//         },
//         ],
//         slogan: "SUV para 7 pasajeros",
//         videoUrl: "CARACTER\u00cdSTICAS:",
//         features: [
//             {
//             title: "Dise\u00f1o Din\u00e1mico",
//             desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
//         },
//             {
//             title: "Conducci\u00f3n Eficiente",
//             desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
//         },
//             {
//             title: "Tecnolog\u00edas Innovadoras",
//             desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
//         },
//         ],
//     },
];
