import { Vehicle } from './types';

export const KAIYI_MODELS: Vehicle[] = [
    {
        id: "kye5",
        brand: "kaiyi",
        name: "KYE5",
        category: "Sedán",
        image: "/images/kaiyi/KYE5/min.webp",
        desktopBanner: "/images/kaiyi/KYE5/banner/desktop.webp",
        gallery: [
            "/images/kaiyi/KYE5/galeria/1.webp",
            "/images/kaiyi/KYE5/galeria/2.webp",
            "/images/kaiyi/KYE5/galeria/3.webp",
            "/images/kaiyi/KYE5/galeria/4.webp",
            "/images/kaiyi/KYE5/galeria/5.webp",
            "/images/kaiyi/KYE5/galeria/6.webp"
        ],
        price: 8990000,
        vehicleType: "liviano",
        ivaIncluded: true,
        isHybrid: false,
        isElectric: false,
        isNew: false,
        versions: [
            {
            name: "1.5T MT LUX",
            motor: "1.5L Turbo",
            fuel: "Gasolina",
            transmission: "Mec\u00e1nica",
            consumptionMixed: "13.5 km/l",
            power: "145 HP",
            torque: "230 Nm",
            traction: "4x2",
            seats: 5,
            airbags: 2,
            listPrice: 14990000,
            brandBonus: 5000000,
            financingBonus: 1000000,
            bonusPrice: 8990000,
        },
            {
            name: "1.5T CVT LUX",
            motor: "1.5L Turbo",
            fuel: "Gasolina",
            transmission: "CVT",
            consumptionMixed: "13.1 km/l",
            power: "145 HP",
            torque: "230 Nm",
            traction: "4x2",
            seats: 5,
            airbags: 2,
            listPrice: 15690000,
            brandBonus: 4700000,
            financingBonus: 1000000,
            bonusPrice: 9990000,
        },
        ],
        slogan: "EL PLACER DE CONDUCIR UN SED\u00c1N",
        videoUrl: "CARACTER\u00cdSTICAS:",
        features: [
            {
            title: "Dise\u00f1o Din\u00e1mico",
            desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
            image: "/images/kaiyi/KYE5/caracteristicas/1.webp",
        },
            {
            title: "Conducci\u00f3n Eficiente",
            desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
            image: "/images/kaiyi/KYE5/caracteristicas/2.webp",
        },
            {
            title: "Tecnolog\u00edas Innovadoras",
            desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
            image: "/images/kaiyi/KYE5/caracteristicas/3.webp",
        },
        ],
    },
    {
        id: "kyx3",
        brand: "kaiyi",
        name: "KYX3",
        category: "SUV",
        image: "/images/kaiyi/KYX3/min.webp",
        desktopBanner: "/images/kaiyi/KYX3/banner/desktop.webp",
        gallery: [
            "/images/kaiyi/KYX3/galeria/2.webp",
            "/images/kaiyi/KYX3/galeria/3.webp",
            "/images/kaiyi/KYX3/galeria/4.webp",
            "/images/kaiyi/KYX3/galeria/5.png",
            "/images/kaiyi/KYX3/galeria/6.webp",
            "/images/kaiyi/KYX3/galeria/7.webp"
        ],
        price: 8990000,
        vehicleType: "liviano",
        ivaIncluded: true,
        isHybrid: false,
        isElectric: false,
        isNew: false,
        versions: [
            {
            name: "1.5L MT STD",
            motor: "1.5L",
            fuel: "Gasolina",
            transmission: "Mec\u00e1nica",
            consumptionMixed: "13.9 km/l",
            power: "111 HP",
            torque: "143 Nm",
            traction: "4x2",
            seats: 5,
            airbags: 2,
            listPrice: 12990000,
            brandBonus: 3000000,
            financingBonus: 1000000,
            bonusPrice: 8990000,
        },
            {
            name: "1.5L MT LUX",
            motor: "1.5L",
            fuel: "Gasolina",
            transmission: "Mec\u00e1nica",
            consumptionMixed: "13.6 km/l",
            power: "111 HP",
            torque: "143 Nm",
            traction: "4x2",
            seats: 5,
            airbags: 2,
            listPrice: 13990000,
            brandBonus: 3000000,
            financingBonus: 1000000,
            bonusPrice: 9990000,
        },
            {
            name: "1.5L CVT LUX",
            motor: "1.5L",
            fuel: "Gasolina",
            transmission: "CVT",
            consumptionMixed: "13.6 km/l",
            power: "111 HP",
            torque: "143 Nm",
            traction: "4x2",
            seats: 5,
            airbags: 2,
            listPrice: 14990000,
            brandBonus: 3700000,
            financingBonus: 1000000,
            bonusPrice: 10290000,
        },
        ],
        slogan: "SUV joven y aut\u00e9ntico",
        videoUrl: "CARACTER\u00cdSTICAS:",
        features: [
            {
            title: "Dise\u00f1o Din\u00e1mico",
            desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
            image: "/images/kaiyi/KYX3/caracteristicas/1.webp",
        },
            {
            title: "Conducci\u00f3n Eficiente",
            desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
            image: "/images/kaiyi/KYX3/caracteristicas/2.webp",
        },
            {
            title: "Tecnolog\u00edas Innovadoras",
            desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
            image: "/images/kaiyi/KYX3/caracteristicas/3.webp",
        },
        ],
    },
    {
        id: "kyx3-pro",
        brand: "kaiyi",
        name: "KYX3 Pro",
        category: "SUV",
        image: "/images/kaiyi/KYX3 Pro/min.webp",
        desktopBanner: "/images/kaiyi/KYX3 Pro/banner/desktop.webp",
        gallery: [
            "/images/kaiyi/KYX3 Pro/galeria/1.webp",
            "/images/kaiyi/KYX3 Pro/galeria/2.webp",
            "/images/kaiyi/KYX3 Pro/galeria/3.webp",
            "/images/kaiyi/KYX3 Pro/galeria/4.webp",
            "/images/kaiyi/KYX3 Pro/galeria/5.webp"
        ],
        price: 11490000,
        vehicleType: "liviano",
        ivaIncluded: true,
        isHybrid: false,
        isElectric: false,
        isNew: false,
        versions: [
            {
            name: "1.5L Turbo CVT",
            motor: "1.5L Turbo",
            fuel: "Gasolina",
            transmission: "CVT",
            consumptionMixed: "12.9 km/l",
            power: "145 HP",
            torque: "230 Nm",
            traction: "4x2",
            seats: 5,
            airbags: 4,
            listPrice: 15990000,
            brandBonus: 3500000,
            financingBonus: 1000000,
            bonusPrice: 11490000,
        },
        ],
        slogan: "SUV POTENTE, ESTABLE Y CONFIABLE",
        videoUrl: "CARACTER\u00cdSTICAS:",
        features: [
            {
            title: "Dise\u00f1o Din\u00e1mico",
            desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
            image: "/images/kaiyi/KYX3 Pro/caracteristicas/1.webp",
        },
            {
            title: "Conducci\u00f3n Eficiente",
            desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
            image: "/images/kaiyi/KYX3 Pro/caracteristicas/2.webp",
        },
            {
            title: "Tecnolog\u00edas Innovadoras",
            desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
            image: "/images/kaiyi/KYX3 Pro/caracteristicas/3.webp",
        },
        ],
    },
    {
        id: "kyx7",
        brand: "kaiyi",
        name: "KYX7",
        category: "SUV",
        image: "/images/kaiyi/KYX7/min.webp",
        desktopBanner: "/images/kaiyi/KYX7/banner/desktop.webp",
        gallery: [
            "/images/kaiyi/KYX7/galeria/1.webp",
            "/images/kaiyi/KYX7/galeria/2.webp",
            "/images/kaiyi/KYX7/galeria/3.webp",
            "/images/kaiyi/KYX7/galeria/4.webp",
            "/images/kaiyi/KYX7/galeria/5.webp"
        ],
        price: 14990000,
        vehicleType: "liviano",
        ivaIncluded: true,
        isHybrid: false,
        isElectric: false,
        isNew: false,
        versions: [
            {
            name: "1.6T 7DCT STD",
            motor: "1.6L Turbo",
            fuel: "Gasolina",
            transmission: "DCT / DSG",
            consumptionMixed: "12.9 km/l",
            power: "183 HP",
            torque: "275 Nm",
            traction: "4x2",
            seats: 7,
            airbags: 4,
            listPrice: 19990000,
            brandBonus: 3500000,
            financingBonus: 1500000,
            bonusPrice: 14990000,
        },
            {
            name: "1.6T 7DCT LUX",
            motor: "1.6L Turbo",
            fuel: "Gasolina",
            transmission: "DCT / DSG",
            consumptionMixed: "12.9 km/l",
            power: "183 HP",
            torque: "275 Nm",
            traction: "4x2",
            seats: 7,
            airbags: 4,
            listPrice: 20990000,
            brandBonus: 3500000,
            financingBonus: 1500000,
            bonusPrice: 15990000,
        },
            {
            name: "2.0T 7DCT LUX",
            motor: "2.0L Turbo",
            fuel: "Gasolina",
            transmission: "DCT / DSG",
            consumptionMixed: "11.5 km/l",
            power: "234 HP",
            torque: "375 Nm",
            traction: "4x2",
            seats: 7,
            airbags: 6,
            listPrice: 22990000,
            brandBonus: 4500000,
            financingBonus: 1500000,
            bonusPrice: 16990000,
        },
        ],
        slogan: "Moderno, Potente y Versatil",
        videoUrl: "CARACTER\u00cdSTICAS:",
        features: [
            {
            title: "Dise\u00f1o Din\u00e1mico",
            desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
            image: "/images/kaiyi/KYX7/caracteristicas/1.webp",
        },
            {
            title: "Conducci\u00f3n Eficiente",
            desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
            image: "/images/kaiyi/KYX7/caracteristicas/2.webp",
        },
            {
            title: "Tecnolog\u00edas Innovadoras",
            desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
            image: "/images/kaiyi/KYX7/caracteristicas/3.webp",
        },
        ],
    },
];
