import { Vehicle } from './types';

export const MAXUS_MODELS: Vehicle[] = [
//     {
//         id: "all-new-t90-ev",
//         brand: "maxus",
//         name: "T90 EV",
//         category: "Eléctrico, Pick-Up",
//         price: 27990000,
//         vehicleType: "liviano",
//         ivaIncluded: false,
//         isHybrid: false,
//         isElectric: true,
//         isNew: false,
//         versions: [
//             {
//             name: "T90 EV 4X2 AT",
//             motor: "Motor El\u00e9ctrico",
//             fuel: "El\u00e9ctrico",
//             transmission: "Autom\u00e1tica",
//             electricRange: "471 km",
//             power: "174 HP",
//             torque: "310 Nm",
//             traction: "4x2",
//             doors: 4,
//             seats: 5,
//             airbags: 6,
//             listPrice: 27990000,
//             brandBonus: 0,
//             financingBonus: 0,
//             bonusPrice: 27990000,
//         },
//         ],
//         slogan: "Pick up el\u00e9ctrica con 1.000 kg de capacidad de carga",
//         videoUrl: "CARACTER\u00cdSTICAS:",
//         features: [
//             {
//             title: "Dise\u00f1o Din\u00e1mico",
//             desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
//         },
//             {
//             title: "Conducci\u00f3n Eficiente",
//             desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
//         },
//             {
//             title: "Tecnolog\u00edas Innovadoras",
//             desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
//         },
//         ],
//     },
    {
        id: "all-new-t90ev",
        brand: "maxus",
        name: "ALL NEW T90",
        category: "Pick-Up",
        price: 25990000,
        image: "/images/maxus/ALL-NEW-T90EV/NEW T90 EV GLX - Banner mobile (1314\u200a\u00d7\u200a2300).webp",
        vehicleType: "liviano",
        ivaIncluded: false,
        isHybrid: false,
        isElectric: false,
        isNew: false,
        versions: [
            {
            name: "ALL NEW T90 4X4 GL 8AT E6",
            motor: "2.5L Turbo Di\u00e9sel",
            fuel: "Di\u00e9sel",
            transmission: "Autom\u00e1tica",
            power: "221 HP",
            torque: "520 Nm",
            traction: "4x4",
            doors: 4,
            seats: 5,
            airbags: 7,
            listPrice: 30990000,
            brandBonus: 4000000,
            financingBonus: 1000000,
            bonusPrice: 25990000,
        },
            {
            name: "ALL NEW T90 4X4 GLX 8AT E6",
            motor: "2.5L Turbo Di\u00e9sel",
            fuel: "Di\u00e9sel",
            transmission: "Autom\u00e1tica",
            power: "221 HP",
            torque: "520 Nm",
            traction: "4x4",
            doors: 4,
            seats: 5,
            airbags: 7,
            listPrice: 33990000,
            brandBonus: 1000000,
            financingBonus: 1000000,
            bonusPrice: 31990000,
        },
        ],
        slogan: "Seguridad, innovaci\u00f3n y potencia en cualquier camino",
        videoUrl: "CARACTER\u00cdSTICAS:",
        features: [
            {
            title: "Dise\u00f1o Din\u00e1mico",
            desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
        },
            {
            title: "Conducci\u00f3n Eficiente",
            desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
        },
            {
            title: "Tecnolog\u00edas Innovadoras",
            desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
        },
        ],
    },
    {
        id: "all_new_t90",
        brand: "maxus",
        name: "T90",
        category: "Pick-Up",
        price: 22990000,
        image: "/images/maxus/All_New_T90/miniatura_all_new_t90.webp",
        vehicleType: "liviano",
        ivaIncluded: false,
        isHybrid: false,
        isElectric: false,
        isNew: false,
        versions: [
            {
            name: "T90 4X4 AT E6",
            motor: "2.0L Bi-Turbo Di\u00e9sel",
            fuel: "Di\u00e9sel",
            transmission: "Autom\u00e1tica",
            consumptionMixed: "9.1 km/l",
            power: "215 HP",
            torque: "500 Nm",
            traction: "4x4",
            doors: 4,
            seats: 5,
            airbags: 6,
            listPrice: 29690000,
            brandBonus: 5700000,
            financingBonus: 1000000,
            bonusPrice: 22990000,
        },
            {
            name: "T90 ADVENTURE 4X4 AT E6",
            motor: "2.0L Bi-Turbo Di\u00e9sel",
            fuel: "Di\u00e9sel",
            transmission: "Autom\u00e1tica",
            consumptionMixed: "9.1 km/l",
            power: "215 HP",
            torque: "500 Nm",
            traction: "4x4",
            doors: 4,
            seats: 5,
            airbags: 6,
            listPrice: 34990000,
            brandBonus: 4000000,
            financingBonus: 1000000,
            bonusPrice: 29990000,
        },
        ],
        slogan: "Eficiente, segura, resistente. Una 4x4 que supera todos los obst\u00e1culos",
        videoUrl: "CARACTER\u00cdSTICAS:",
        features: [
            {
            title: "Dise\u00f1o Din\u00e1mico",
            desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
            image: "/images/maxus/All_New_T90/caracteristicas/motor.webp",
        },
            {
            title: "Conducci\u00f3n Eficiente",
            desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
            image: "/images/maxus/All_New_T90/caracteristicas/Seguridad - Camara 360 (696x696) (1).webp",
        },
            {
            title: "Tecnolog\u00edas Innovadoras",
            desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
            image: "/images/maxus/All_New_T90/caracteristicas/Seguridad - Sensores (696x696).webp",
        },
        ],
        gallery: [
            "/images/maxus/All_New_T90/galeria/1108X414 DESKTOP (2).webp",
            "/images/maxus/All_New_T90/galeria/NEW T90 GLX - Galeria Desktop 01 (1200x600) copia 2.webp",
            "/images/maxus/All_New_T90/galeria/NEW T90 GLX - Galeria Desktop 02 (1200x600) copia 2.webp",
            "/images/maxus/All_New_T90/galeria/NEW T90 GLX - Galeria Desktop 03 (1200x600).webp",
        ],
    },
//     {
//         id: "c35",
//         brand: "maxus",
//         name: "C35",
//         category: "Furgón",
//         price: 14990000,
//         vehicleType: "liviano",
//         ivaIncluded: false,
//         isHybrid: false,
//         isElectric: false,
//         isNew: false,
//         versions: [
//             {
//             name: "C35 E6",
//             motor: "2.0L Turbo Di\u00e9sel",
//             fuel: "Di\u00e9sel",
//             transmission: "Mec\u00e1nica",
//             power: "129 HP",
//             torque: "350 Nm",
//             traction: "4x2",
//             seats: 2,
//             airbags: 2,
//             listPrice: 18990000,
//             brandBonus: 3400000,
//             financingBonus: 600000,
//             bonusPrice: 14990000,
//         },
//             {
//             name: "C35 C/PLANA E6",
//             motor: "2.0L Turbo Di\u00e9sel",
//             fuel: "Di\u00e9sel",
//             transmission: "Mec\u00e1nica",
//             power: "129 HP",
//             torque: "350 Nm",
//             traction: "4x2",
//             seats: 2,
//             airbags: 2,
//             listPrice: 19990000,
//             brandBonus: 3400000,
//             financingBonus: 600000,
//             bonusPrice: 15990000,
//         },
//             {
//             name: "C35 L E6",
//             motor: "2.0L Turbo Di\u00e9sel",
//             fuel: "Di\u00e9sel",
//             transmission: "Mec\u00e1nica",
//             consumptionMixed: "11.4 km/l",
//             power: "129 HP",
//             torque: "350 Nm",
//             traction: "4x2",
//             seats: 2,
//             airbags: 2,
//             listPrice: 19990000,
//             brandBonus: 3400000,
//             financingBonus: 600000,
//             bonusPrice: 15990000,
//         },
//             {
//             name: "C35 L C/PLANA E6",
//             motor: "2.0L Turbo Di\u00e9sel",
//             fuel: "Di\u00e9sel",
//             transmission: "Mec\u00e1nica",
//             power: "129 HP",
//             torque: "350 Nm",
//             traction: "4x2",
//             seats: 2,
//             airbags: 2,
//             listPrice: 20990000,
//             brandBonus: 3400000,
//             financingBonus: 600000,
//             bonusPrice: 16990000,
//         },
//             {
//             name: "C35 DC C/PLANA E6",
//             motor: "2.0L Turbo Di\u00e9sel",
//             fuel: "Di\u00e9sel",
//             transmission: "Mec\u00e1nica",
//             power: "129 HP",
//             torque: "350 Nm",
//             traction: "4x2",
//             seats: 5,
//             airbags: 2,
//             listPrice: 21990000,
//             brandBonus: 4400000,
//             financingBonus: 600000,
//             bonusPrice: 16990000,
//         },
//         ],
//         slogan: "El compa\u00f1ero m\u00e1s fiel para tu trabajo",
//         videoUrl: "CARACTER\u00cdSTICAS:",
//         features: [
//             {
//             title: "Dise\u00f1o Din\u00e1mico",
//             desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
//         },
//             {
//             title: "Conducci\u00f3n Eficiente",
//             desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
//         },
//             {
//             title: "Tecnolog\u00edas Innovadoras",
//             desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
//         },
//         ],
//     },
//     {
//         id: "d60",
//         brand: "maxus",
//         name: "D60",
//         category: "SUV",
//         price: 14990000,
//         vehicleType: "liviano",
//         ivaIncluded: true,
//         isHybrid: false,
//         isElectric: false,
//         isNew: false,
//         versions: [
//             {
//             name: "D60 4X2 ELITE 7DCT",
//             motor: "1.5 T",
//             fuel: "Gasolina",
//             transmission: "DCT / DSG",
//             power: "180 HP",
//             torque: "285 Nm",
//             traction: "4x2",
//             seats: 7,
//             airbags: 4,
//             listPrice: 20990000,
//             brandBonus: 4000000,
//             financingBonus: 2000000,
//             bonusPrice: 14990000,
//         },
//             {
//             name: "D60 4X2 LUXURY 7DCT",
//             motor: "1.5 T",
//             fuel: "Gasolina",
//             transmission: "DCT / DSG",
//             power: "180 HP",
//             torque: "285 Nm",
//             traction: "4x2",
//             seats: 7,
//             airbags: 6,
//             listPrice: 22990000,
//             brandBonus: 3000000,
//             financingBonus: 2000000,
//             bonusPrice: 17990000,
//         },
//         ],
//         slogan: "Tecnolog\u00eda que cuida, inspira y conecta",
//         videoUrl: "CARACTER\u00cdSTICAS:",
//         features: [
//             {
//             title: "Dise\u00f1o Din\u00e1mico",
//             desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
//         },
//             {
//             title: "Conducci\u00f3n Eficiente",
//             desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
//         },
//             {
//             title: "Tecnolog\u00edas Innovadoras",
//             desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
//         },
//         ],
//     },
//     {
//         id: "d90",
//         brand: "maxus",
//         name: "D90",
//         category: "Híbrido, SUV",
//         price: 26490000,
//         vehicleType: "liviano",
//         ivaIncluded: true,
//         isHybrid: true,
//         isElectric: false,
//         isNew: false,
//         versions: [
//             {
//             name: "D90 4X4 ELITE 8AT",
//             motor: "2.0 Bi-Turbo",
//             fuel: "H\u00edbrido",
//             transmission: "Autom\u00e1tica",
//             power: "215 HP",
//             torque: "500 Nm",
//             traction: "4x4",
//             seats: 7,
//             airbags: 6,
//             listPrice: 36490000,
//             brandBonus: 9000000,
//             financingBonus: 1000000,
//             bonusPrice: 26490000,
//         },
//             {
//             name: "D90 4X4 LUXURY 8AT",
//             motor: "2.0 Bi-Turbo",
//             fuel: "H\u00edbrido",
//             transmission: "Autom\u00e1tica",
//             power: "215 HP",
//             torque: "500 Nm",
//             traction: "4x4",
//             seats: 7,
//             airbags: 6,
//             listPrice: 39490000,
//             brandBonus: 8500000,
//             financingBonus: 1000000,
//             bonusPrice: 29990000,
//         },
//             {
//             name: "D90 4X4 FLAGSHIP 8AT",
//             motor: "2.0 Bi-Turbo",
//             fuel: "H\u00edbrido",
//             transmission: "Autom\u00e1tica",
//             power: "215 HP",
//             torque: "500 Nm",
//             traction: "4x4",
//             seats: 7,
//             airbags: 6,
//             listPrice: 41490000,
//             brandBonus: 5000000,
//             financingBonus: 1000000,
//             bonusPrice: 35490000,
//         },
//         ],
//         slogan: "Tecnolog\u00eda que cuida, inspira y conecta",
//         videoUrl: "CARACTER\u00cdSTICAS:",
//         features: [
//             {
//             title: "Dise\u00f1o Din\u00e1mico",
//             desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
//         },
//             {
//             title: "Conducci\u00f3n Eficiente",
//             desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
//         },
//             {
//             title: "Tecnolog\u00edas Innovadoras",
//             desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
//         },
//         ],
//     },
//     {
//         id: "deliver-9-cargo",
//         brand: "maxus",
//         name: "Deliver 9 Cargo",
//         category: "Furgón",
//         price: 22490000,
//         vehicleType: "liviano",
//         ivaIncluded: false,
//         isHybrid: false,
//         isElectric: false,
//         isNew: false,
//         versions: [
//             {
//             name: "DELIVER 9 CARGO L2H2",
//             motor: "2.0L Turbo Di\u00e9sel",
//             fuel: "Di\u00e9sel",
//             transmission: "Mec\u00e1nica",
//             consumptionMixed: "9.2 km/l",
//             power: "163 HP",
//             torque: "375 Nm",
//             traction: "4x2",
//             seats: 3,
//             airbags: 2,
//             listPrice: 24690000,
//             brandBonus: 1600000,
//             financingBonus: 600000,
//             bonusPrice: 22490000,
//         },
//             {
//             name: "DELIVER 9 CARGO L3H2",
//             motor: "2.0L Turbo Di\u00e9sel",
//             fuel: "Di\u00e9sel",
//             transmission: "Mec\u00e1nica",
//             consumptionMixed: "9.2 km/l",
//             power: "163 HP",
//             torque: "375 Nm",
//             traction: "4x2",
//             seats: 3,
//             airbags: 2,
//             listPrice: 25490000,
//             brandBonus: 0,
//             financingBonus: 600000,
//             bonusPrice: 24890000,
//         },
//             {
//             name: "DELIVER 9 CARGO L3H3",
//             motor: "2.0L Turbo Di\u00e9sel",
//             fuel: "Di\u00e9sel",
//             transmission: "Mec\u00e1nica",
//             power: "163 HP",
//             torque: "375 Nm",
//             traction: "4x2",
//             seats: 3,
//             airbags: 2,
//             listPrice: 25990000,
//             brandBonus: 0,
//             financingBonus: 600000,
//             bonusPrice: 25390000,
//         },
//             {
//             name: "DELIVER 9 CARGO L3H3 RWD GLX",
//             motor: "2.0L Turbo Di\u00e9sel",
//             fuel: "Di\u00e9sel",
//             transmission: "Mec\u00e1nica",
//             consumptionMixed: "9.2 km/l",
//             power: "163 HP",
//             torque: "375 Nm",
//             traction: "4x2",
//             seats: 3,
//             airbags: 6,
//             listPrice: 31990000,
//             brandBonus: 0,
//             financingBonus: 600000,
//             bonusPrice: 31390000,
//         },
//         ],
//         slogan: "El nuevo compa\u00f1ero de trabajo para los m\u00e1s exigentes",
//         videoUrl: "CARACTER\u00cdSTICAS:",
//         features: [
//             {
//             title: "Dise\u00f1o Din\u00e1mico",
//             desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
//         },
//             {
//             title: "Conducci\u00f3n Eficiente",
//             desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
//         },
//             {
//             title: "Tecnolog\u00edas Innovadoras",
//             desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
//         },
//         ],
//     },
//     {
//         id: "deliver-9-escolar",
//         brand: "maxus",
//         name: "Deliver 9 Escolar",
//         category: "Escolares, Minibús",
//         price: 35390000,
//         vehicleType: "liviano",
//         ivaIncluded: false,
//         isHybrid: false,
//         isElectric: false,
//         isNew: false,
//         versions: [
//             {
//             name: "DELIVER 9 ESCOLAR 26+1 (color blanco)",
//             motor: "2.0L Turbo Di\u00e9sel",
//             fuel: "Di\u00e9sel",
//             transmission: "Mec\u00e1nica",
//             power: "148 HP",
//             torque: "375 Nm",
//             traction: "4x2",
//             seats: 27,
//             airbags: 2,
//             listPrice: 35990000,
//             brandBonus: 0,
//             financingBonus: 600000,
//             bonusPrice: 35390000,
//         },
//         ],
//         slogan: "Eficiente, segura y resistente en todos los ambientes",
//         videoUrl: "CARACTER\u00cdSTICAS:",
//         features: [
//             {
//             title: "Dise\u00f1o Din\u00e1mico",
//             desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
//         },
//             {
//             title: "Conducci\u00f3n Eficiente",
//             desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
//         },
//             {
//             title: "Tecnolog\u00edas Innovadoras",
//             desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
//         },
//         ],
//     },
//     {
//         id: "deliver-9-pasajeros",
//         brand: "maxus",
//         name: "Deliver 9 Pasajeros",
//         category: "Minibús",
//         price: 34390000,
//         vehicleType: "liviano",
//         ivaIncluded: false,
//         isHybrid: false,
//         isElectric: false,
//         isNew: false,
//         versions: [
//             {
//             name: "DELIVER 9 MINIBUS 15+1 L3H2 E6",
//             motor: "2.0L Turbo Di\u00e9sel",
//             fuel: "Di\u00e9sel",
//             transmission: "Mec\u00e1nica",
//             power: "148 HP",
//             torque: "375 Nm",
//             traction: "4x2",
//             seats: 16,
//             airbags: 2,
//             listPrice: 34990000,
//             brandBonus: 0,
//             financingBonus: 600000,
//             bonusPrice: 34390000,
//         },
//             {
//             name: "DELIVER 9 MINIBUS 15+1 L3H2 8AT E6",
//             motor: "2.0L Turbo Di\u00e9sel",
//             fuel: "Di\u00e9sel",
//             transmission: "Autom\u00e1tica",
//             power: "148 HP",
//             torque: "375 Nm",
//             traction: "4x2",
//             seats: 16,
//             airbags: 2,
//             listPrice: 37090000,
//             brandBonus: 0,
//             financingBonus: 600000,
//             bonusPrice: 36490000,
//         },
//         ],
//         slogan: "Van de pasajeros o viajes ejecutivos",
//         videoUrl: "CARACTER\u00cdSTICAS:",
//         features: [
//             {
//             title: "Dise\u00f1o Din\u00e1mico",
//             desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
//         },
//             {
//             title: "Conducci\u00f3n Eficiente",
//             desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
//         },
//             {
//             title: "Tecnolog\u00edas Innovadoras",
//             desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
//         },
//         ],
//     },
//     {
//         id: "et-1825",
//         brand: "maxus",
//         name: "ET-1825",
//         category: "Camión, Eléctrico",
//         price: 149000,
//         vehicleType: "cami\u00f3n",
//         ivaIncluded: false,
//         isHybrid: false,
//         isElectric: true,
//         isNew: false,
//         versions: [
//             {
//             name: "ET-1825",
//             motor: "Motor El\u00e9ctrico",
//             fuel: "El\u00e9ctrico",
//             transmission: "Autom\u00e1tica",
//             electricRange: "400 km",
//             power: "134 HP",
//             traction: "4x2",
//             doors: 2,
//             airbags: 2,
//             listPrice: 149000,
//             brandBonus: 0,
//             financingBonus: 0,
//             bonusPrice: 149000,
//         },
//         ],
//         slogan: "Cami\u00f3n el\u00e9ctrico vers\u00e1til que permite llevar tu carga sin emitir CO2",
//         videoUrl: "CARACTER\u00cdSTICAS:",
//         features: [
//             {
//             title: "Dise\u00f1o Din\u00e1mico",
//             desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
//         },
//             {
//             title: "Conducci\u00f3n Eficiente",
//             desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
//         },
//             {
//             title: "Tecnolog\u00edas Innovadoras",
//             desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
//         },
//         ],
//     },
//     {
//         id: "et-1849",
//         brand: "maxus",
//         name: "ET-1849",
//         category: "Eléctrico, Tractocamión",
//         price: 110000,
//         vehicleType: "cami\u00f3n",
//         ivaIncluded: false,
//         isHybrid: false,
//         isElectric: true,
//         isNew: false,
//         versions: [
//             {
//             name: "ET-1849",
//             motor: "Motor El\u00e9ctrico",
//             fuel: "El\u00e9ctrico",
//             transmission: "Autom\u00e1tica",
//             electricRange: "150 km",
//             power: "490 HP",
//             traction: "4x2",
//             doors: 2,
//             airbags: 2,
//             listPrice: 110000,
//             brandBonus: 0,
//             financingBonus: 0,
//             bonusPrice: 110000,
//         },
//         ],
//         slogan: "Cami\u00f3n el\u00e9ctrico vers\u00e1til que permite llevar tu carga sin emitir CO2",
//         videoUrl: "CARACTER\u00cdSTICAS:",
//         features: [
//             {
//             title: "Dise\u00f1o Din\u00e1mico",
//             desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
//         },
//             {
//             title: "Conducci\u00f3n Eficiente",
//             desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
//         },
//             {
//             title: "Tecnolog\u00edas Innovadoras",
//             desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
//         },
//         ],
//     },
//     {
//         id: "et-2549",
//         brand: "maxus",
//         name: "ET-2549",
//         category: "Eléctrico, Tractocamión",
//         price: 120000,
//         vehicleType: "cami\u00f3n",
//         ivaIncluded: false,
//         isHybrid: false,
//         isElectric: true,
//         isNew: false,
//         versions: [
//             {
//             name: "ET-2549",
//             motor: "Motor El\u00e9ctrico",
//             fuel: "El\u00e9ctrico",
//             transmission: "Autom\u00e1tica",
//             electricRange: "150 km",
//             power: "490 HP",
//             traction: "AWD",
//             doors: 2,
//             airbags: 2,
//             listPrice: 120000,
//             brandBonus: 0,
//             financingBonus: 0,
//             bonusPrice: 120000,
//         },
//         ],
//         slogan: "Cami\u00f3n el\u00e9ctrico vers\u00e1til que permite llevar tu carga sin emitir CO2",
//         videoUrl: "CARACTER\u00cdSTICAS:",
//         features: [
//             {
//             title: "Dise\u00f1o Din\u00e1mico",
//             desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
//         },
//             {
//             title: "Conducci\u00f3n Eficiente",
//             desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
//         },
//             {
//             title: "Tecnolog\u00edas Innovadoras",
//             desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
//         },
//         ],
//     },
//     {
//         id: "et-516",
//         brand: "maxus",
//         name: "ET-516",
//         category: "Camión, Eléctrico",
//         price: 29900,
//         vehicleType: "cami\u00f3n",
//         ivaIncluded: false,
//         isHybrid: false,
//         isElectric: true,
//         isNew: false,
//         versions: [
//             {
//             name: "ET-516",
//             motor: "Motor El\u00e9ctrico",
//             fuel: "El\u00e9ctrico",
//             transmission: "Autom\u00e1tica",
//             electricRange: "240 km",
//             power: "160 HP",
//             traction: "4x2",
//             doors: 2,
//             airbags: 2,
//             listPrice: 29900,
//             brandBonus: 0,
//             financingBonus: 0,
//             bonusPrice: 29900,
//         },
//         ],
//         slogan: "Cami\u00f3n el\u00e9ctrico vers\u00e1til que permite llevar tu carga sin emitir CO2",
//         videoUrl: "CARACTER\u00cdSTICAS:",
//         features: [
//             {
//             title: "Dise\u00f1o Din\u00e1mico",
//             desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
//         },
//             {
//             title: "Conducci\u00f3n Eficiente",
//             desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
//         },
//             {
//             title: "Tecnolog\u00edas Innovadoras",
//             desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
//         },
//         ],
//     },
//     {
//         id: "et-916",
//         brand: "maxus",
//         name: "ET-916",
//         category: "Camión, Eléctrico",
//         price: 60000,
//         vehicleType: "cami\u00f3n",
//         ivaIncluded: false,
//         isHybrid: false,
//         isElectric: true,
//         isNew: false,
//         versions: [
//             {
//             name: "ET-916",
//             motor: "Motor El\u00e9ctrico",
//             fuel: "El\u00e9ctrico",
//             transmission: "Autom\u00e1tica",
//             electricRange: "300 km",
//             power: "163 HP",
//             traction: "4x2",
//             doors: 2,
//             airbags: 6,
//             listPrice: 60000,
//             brandBonus: 0,
//             financingBonus: 0,
//             bonusPrice: 60000,
//         },
//         ],
//         slogan: "Cami\u00f3n el\u00e9ctrico vers\u00e1til que permite llevar tu carga sin emitir CO2",
//         videoUrl: "CARACTER\u00cdSTICAS:",
//         features: [
//             {
//             title: "Dise\u00f1o Din\u00e1mico",
//             desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
//         },
//             {
//             title: "Conducci\u00f3n Eficiente",
//             desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
//         },
//             {
//             title: "Tecnolog\u00edas Innovadoras",
//             desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
//         },
//         ],
//     },
//     {
//         id: "euniq-5",
//         brand: "maxus",
//         name: "EUNIQ 5",
//         category: "Eléctrico, SUV",
//         price: 27251000,
//         vehicleType: "liviano",
//         ivaIncluded: true,
//         isHybrid: false,
//         isElectric: true,
//         isNew: false,
//         versions: [
//             {
//             name: "Euniq 5",
//             motor: "Motor El\u00e9ctrico",
//             fuel: "El\u00e9ctrico",
//             transmission: "Autom\u00e1tica",
//             consumptionMixed: "3.9 km/kWh",
//             electricRange: "437 km",
//             power: "174 HP",
//             torque: "310 Nm",
//             traction: "4x2",
//             seats: 7,
//             airbags: 4,
//             listPrice: 27251000,
//             brandBonus: 0,
//             financingBonus: 0,
//             bonusPrice: 27251000,
//         },
//         ],
//         slogan: "La nueva EUNIQ 5 es una SUV \u00fanica y 100% el\u00e9ctrica.",
//         videoUrl: "CARACTER\u00cdSTICAS:",
//         features: [
//             {
//             title: "Dise\u00f1o Din\u00e1mico",
//             desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
//         },
//             {
//             title: "Conducci\u00f3n Eficiente",
//             desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
//         },
//             {
//             title: "Tecnolog\u00edas Innovadoras",
//             desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
//         },
//         ],
//     },
//     {
//         id: "g10-cargo",
//         brand: "maxus",
//         name: "G10 Cargo",
//         category: "Furgón",
//         price: 19990000,
//         vehicleType: "liviano",
//         ivaIncluded: false,
//         isHybrid: false,
//         isElectric: false,
//         isNew: false,
//         versions: [
//             {
//             name: "G10 CARGO MT E6",
//             motor: "2.0L Turbo Di\u00e9sel",
//             fuel: "Di\u00e9sel",
//             transmission: "Mec\u00e1nica",
//             consumptionMixed: "8.9 km/l",
//             power: "160 HP",
//             torque: "390 Nm",
//             traction: "4x2",
//             doors: 5,
//             seats: 2,
//             airbags: 2,
//             listPrice: 20990000,
//             brandBonus: 400000,
//             financingBonus: 600000,
//             bonusPrice: 19990000,
//         },
//         ],
//         slogan: "La m\u00e1s vers\u00e1til de su categor\u00eda",
//         videoUrl: "CARACTER\u00cdSTICAS:",
//         features: [
//             {
//             title: "Dise\u00f1o Din\u00e1mico",
//             desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
//         },
//             {
//             title: "Conducci\u00f3n Eficiente",
//             desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
//         },
//             {
//             title: "Tecnolog\u00edas Innovadoras",
//             desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
//         },
//         ],
//     },
//     {
//         id: "g10-minib\u00fas",
//         brand: "maxus",
//         name: "G10 Minib\u00fas",
//         category: "Minibús",
//         price: 22990000,
//         vehicleType: "liviano",
//         ivaIncluded: false,
//         isHybrid: false,
//         isElectric: false,
//         isNew: false,
//         versions: [
//             {
//             name: "G10 MINIBUS 9+1 MT E6",
//             motor: "2.0L Turbo Di\u00e9sel",
//             fuel: "Di\u00e9sel",
//             transmission: "Mec\u00e1nica",
//             consumptionMixed: "12.7 km/l",
//             power: "163 HP",
//             torque: "375 Nm",
//             traction: "4x2",
//             doors: 5,
//             seats: 10,
//             airbags: 2,
//             listPrice: 25390000,
//             brandBonus: 1800000,
//             financingBonus: 600000,
//             bonusPrice: 22990000,
//         },
//             {
//             name: "G10 MINIBUS 6+1 MT E6",
//             motor: "2.0L Turbo Di\u00e9sel",
//             fuel: "Di\u00e9sel",
//             transmission: "Mec\u00e1nica",
//             consumptionMixed: "12.7 km/l",
//             power: "163 HP",
//             torque: "375 Nm",
//             traction: "4x2",
//             doors: 5,
//             seats: 7,
//             airbags: 2,
//             listPrice: 25390000,
//             brandBonus: 0,
//             financingBonus: 600000,
//             bonusPrice: 24790000,
//         },
//         ],
//         slogan: "Minib\u00fas para 9+1 pasajeros",
//         videoUrl: "CARACTER\u00cdSTICAS:",
//         features: [
//             {
//             title: "Dise\u00f1o Din\u00e1mico",
//             desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
//         },
//             {
//             title: "Conducci\u00f3n Eficiente",
//             desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
//         },
//             {
//             title: "Tecnolog\u00edas Innovadoras",
//             desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
//         },
//         ],
//     },
//     {
//         id: "g90-minib\u00fas",
//         brand: "maxus",
//         name: "G90 Minib\u00fas",
//         category: "Minibús",
//         price: 25990000,
//         vehicleType: "liviano",
//         ivaIncluded: false,
//         isHybrid: false,
//         isElectric: false,
//         isNew: false,
//         versions: [
//             {
//             name: "G90 MINIBUS ELITE 6+1 AT",
//             motor: "2.0L Turbo Di\u00e9sel",
//             fuel: "Di\u00e9sel",
//             transmission: "Autom\u00e1tica",
//             consumptionMixed: "13.3 km/l",
//             power: "159 HP",
//             torque: "390 Nm",
//             traction: "4x2",
//             doors: 5,
//             seats: 7,
//             airbags: 4,
//             listPrice: 28990000,
//             brandBonus: 2400000,
//             financingBonus: 600000,
//             bonusPrice: 25990000,
//         },
//             {
//             name: "G90 MINIBUS LUXURY 6+1 AT",
//             motor: "2.0L Turbo Di\u00e9sel",
//             fuel: "Di\u00e9sel",
//             transmission: "Autom\u00e1tica",
//             consumptionMixed: "13.3 km/l",
//             power: "159 HP",
//             torque: "390 Nm",
//             traction: "4x2",
//             doors: 5,
//             seats: 7,
//             airbags: 6,
//             listPrice: 35990000,
//             brandBonus: 1000000,
//             financingBonus: 500000,
//             bonusPrice: 34490000,
//         },
//         ],
//         slogan: "Una van segura y c\u00f3moda para el transporte de pasajeros",
//         videoUrl: "CARACTER\u00cdSTICAS:",
//         features: [
//             {
//             title: "Dise\u00f1o Din\u00e1mico",
//             desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
//         },
//             {
//             title: "Conducci\u00f3n Eficiente",
//             desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
//         },
//             {
//             title: "Tecnolog\u00edas Innovadoras",
//             desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
//         },
//         ],
//     },
//     {
//         id: "mifa-9",
//         brand: "maxus",
//         name: "MIFA 9",
//         category: "Eléctrico, Minibús",
//         price: 54590000,
//         vehicleType: "liviano",
//         ivaIncluded: true,
//         isHybrid: false,
//         isElectric: true,
//         isNew: false,
//         versions: [
//             {
//             name: "MIFA 9",
//             motor: "Motor El\u00e9ctrico",
//             fuel: "El\u00e9ctrico",
//             transmission: "Autom\u00e1tica",
//             electricRange: "580 km",
//             power: "242 HP",
//             torque: "350 Nm",
//             traction: "4x2",
//             doors: 5,
//             seats: 7,
//             airbags: 6,
//             listPrice: 54590000,
//             brandBonus: 0,
//             financingBonus: 0,
//             bonusPrice: 54590000,
//         },
//         ],
//         slogan: "VAN 100% el\u00e9ctrica",
//         videoUrl: "CARACTER\u00cdSTICAS:",
//         features: [
//             {
//             title: "Dise\u00f1o Din\u00e1mico",
//             desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
//         },
//             {
//             title: "Conducci\u00f3n Eficiente",
//             desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
//         },
//             {
//             title: "Tecnolog\u00edas Innovadoras",
//             desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
//         },
//         ],
//     },
//     {
//         id: "t60-dx",
//         brand: "maxus",
//         name: "T60 DX",
//         category: "Pick-Up",
//         price: 11990000,
//         vehicleType: "liviano",
//         ivaIncluded: false,
//         isHybrid: false,
//         isElectric: false,
//         isNew: false,
//         versions: [
//             {
//             name: "T60 4X2 DX MT E6 GASOLINA",
//             motor: "2.4L",
//             fuel: "Gasolina",
//             transmission: "Mec\u00e1nica",
//             power: "158 HP",
//             torque: "225 Nm",
//             traction: "4x2",
//             airbags: 2,
//             listPrice: 14990000,
//             brandBonus: 2000000,
//             financingBonus: 1000000,
//             bonusPrice: 11990000,
//         },
//             {
//             name: "T60 SC 4X2 DX PLUS 6MT E6",
//             motor: "2.0L Turbo Di\u00e9sel",
//             fuel: "Di\u00e9sel",
//             transmission: "Mec\u00e1nica",
//             power: "163 HP",
//             torque: "400 Nm",
//             traction: "4x2",
//             doors: 2,
//             seats: 2,
//             airbags: 2,
//             listPrice: 19690000,
//             brandBonus: 2700000,
//             financingBonus: 1000000,
//             bonusPrice: 15990000,
//         },
//             {
//             name: "T60 4X2 DX MT E6",
//             motor: "2.0L Turbo Di\u00e9sel",
//             fuel: "Di\u00e9sel",
//             transmission: "Mec\u00e1nica",
//             power: "163 HP",
//             torque: "400 Nm",
//             traction: "4x2",
//             doors: 4,
//             seats: 5,
//             airbags: 2,
//             listPrice: 19990000,
//             brandBonus: 5000000,
//             financingBonus: 1000000,
//             bonusPrice: 13990000,
//         },
//             {
//             name: "T60 4X2 DX PLUS 6MT E6",
//             motor: "2.0L Turbo Di\u00e9sel",
//             fuel: "Di\u00e9sel",
//             transmission: "Mec\u00e1nica",
//             power: "163 HP",
//             torque: "400 Nm",
//             traction: "4x2",
//             doors: 4,
//             seats: 5,
//             airbags: 2,
//             listPrice: 19990000,
//             brandBonus: 3000000,
//             financingBonus: 1000000,
//             bonusPrice: 15990000,
//         },
//             {
//             name: "T60 SC 4X4 DX PLUS 6MT E6",
//             motor: "2.0L Turbo Di\u00e9sel",
//             fuel: "Di\u00e9sel",
//             transmission: "Mec\u00e1nica",
//             power: "163 HP",
//             torque: "400 Nm",
//             traction: "4x4",
//             doors: 2,
//             seats: 2,
//             airbags: 2,
//             listPrice: 20590000,
//             brandBonus: 1600000,
//             financingBonus: 1000000,
//             bonusPrice: 17990000,
//         },
//             {
//             name: "T60 4X4 DX MT E6",
//             motor: "2.0L Turbo Di\u00e9sel",
//             fuel: "Di\u00e9sel",
//             transmission: "Mec\u00e1nica",
//             power: "163 HP",
//             torque: "400 Nm",
//             traction: "4x4",
//             doors: 4,
//             seats: 5,
//             airbags: 2,
//             listPrice: 21490000,
//             brandBonus: 3200000,
//             financingBonus: 1000000,
//             bonusPrice: 17290000,
//         },
//             {
//             name: "T60 4X4 DX PLUS 6MT E6",
//             motor: "2.0L Turbo Di\u00e9sel",
//             fuel: "Di\u00e9sel",
//             transmission: "Mec\u00e1nica",
//             power: "163 HP",
//             torque: "400 Nm",
//             traction: "4x4",
//             doors: 4,
//             seats: 5,
//             airbags: 2,
//             listPrice: 21490000,
//             brandBonus: 2600000,
//             financingBonus: 1000000,
//             bonusPrice: 17890000,
//         },
//             {
//             name: "T60 4X4 ANCAP MT E6",
//             motor: "2.0L Turbo Di\u00e9sel",
//             fuel: "Di\u00e9sel",
//             transmission: "Mec\u00e1nica",
//             power: "163 HP",
//             torque: "400 Nm",
//             traction: "4x4",
//             doors: 4,
//             seats: 5,
//             airbags: 6,
//             listPrice: 24190000,
//             brandBonus: 3200000,
//             financingBonus: 1000000,
//             bonusPrice: 19990000,
//         },
//         ],
//         slogan: "Perfecta para todos tus trabajos",
//         videoUrl: "CARACTER\u00cdSTICAS:",
//         features: [
//             {
//             title: "Dise\u00f1o Din\u00e1mico",
//             desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
//         },
//             {
//             title: "Conducci\u00f3n Eficiente",
//             desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
//         },
//             {
//             title: "Tecnolog\u00edas Innovadoras",
//             desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
//         },
//         ],
//     },
//     {
//         id: "t60-gl-glx",
//         brand: "maxus",
//         name: "T60 GL-GLX",
//         category: "Pick-Up",
//         price: 16990000,
//         vehicleType: "liviano",
//         ivaIncluded: false,
//         isHybrid: false,
//         isElectric: false,
//         isNew: false,
//         versions: [
//             {
//             name: "T60 4X2 GL MT E6",
//             motor: "2.0L Turbo Di\u00e9sel",
//             fuel: "Di\u00e9sel",
//             transmission: "Mec\u00e1nica",
//             power: "163 HP",
//             torque: "400 Nm",
//             traction: "4x2",
//             doors: 4,
//             seats: 5,
//             airbags: 2,
//             listPrice: 20990000,
//             brandBonus: 3000000,
//             financingBonus: 1000000,
//             bonusPrice: 16990000,
//         },
//             {
//             name: "T60 4X2 GL 6MT E6 4AB",
//             motor: "2.0L Turbo Di\u00e9sel",
//             fuel: "Di\u00e9sel",
//             transmission: "Mec\u00e1nica",
//             power: "163 HP",
//             torque: "400 Nm",
//             traction: "4x2",
//             doors: 4,
//             seats: 5,
//             airbags: 4,
//             listPrice: 20990000,
//             brandBonus: 3000000,
//             financingBonus: 1000000,
//             bonusPrice: 16990000,
//         },
//             {
//             name: "T60 4X2 GL AT E6",
//             motor: "2.0L Turbo Di\u00e9sel",
//             fuel: "Di\u00e9sel",
//             transmission: "Autom\u00e1tica",
//             power: "163 HP",
//             torque: "400 Nm",
//             traction: "4x2",
//             doors: 4,
//             seats: 5,
//             airbags: 2,
//             listPrice: 21590000,
//             brandBonus: 2600000,
//             financingBonus: 1000000,
//             bonusPrice: 17990000,
//         },
//             {
//             name: "T60 4X2 GL 8AT E6 4AB",
//             motor: "2.0L Turbo Di\u00e9sel",
//             fuel: "Di\u00e9sel",
//             transmission: "Autom\u00e1tica",
//             power: "163 HP",
//             torque: "400 Nm",
//             traction: "4x2",
//             doors: 4,
//             seats: 5,
//             airbags: 4,
//             listPrice: 21590000,
//             brandBonus: 1600000,
//             financingBonus: 1000000,
//             bonusPrice: 18990000,
//         },
//             {
//             name: "T60 4X4 GL MT E6",
//             motor: "2.0L Turbo Di\u00e9sel",
//             fuel: "Di\u00e9sel",
//             transmission: "Mec\u00e1nica",
//             power: "163 HP",
//             torque: "400 Nm",
//             traction: "4x4",
//             doors: 4,
//             seats: 5,
//             airbags: 2,
//             listPrice: 22590000,
//             brandBonus: 3100000,
//             financingBonus: 1000000,
//             bonusPrice: 18490000,
//         },
//             {
//             name: "T60 4X4 GL 6MT E6 4AB",
//             motor: "2.0L Turbo Di\u00e9sel",
//             fuel: "Di\u00e9sel",
//             transmission: "Mec\u00e1nica",
//             power: "163 HP",
//             torque: "400 Nm",
//             traction: "4x4",
//             doors: 4,
//             seats: 5,
//             airbags: 4,
//             listPrice: 22590000,
//             brandBonus: 2600000,
//             financingBonus: 1000000,
//             bonusPrice: 18990000,
//         },
//             {
//             name: "T60 4X4 GLX AT E6",
//             motor: "2.0L Turbo Di\u00e9sel",
//             fuel: "Di\u00e9sel",
//             transmission: "Autom\u00e1tica",
//             power: "163 HP",
//             torque: "400 Nm",
//             traction: "4x4",
//             doors: 4,
//             seats: 5,
//             airbags: 6,
//             listPrice: 26690000,
//             brandBonus: 4200000,
//             financingBonus: 1000000,
//             bonusPrice: 21490000,
//         },
//         ],
//         slogan: "Perfecta para todos tus trabajos",
//         videoUrl: "CARACTER\u00cdSTICAS:",
//         features: [
//             {
//             title: "Dise\u00f1o Din\u00e1mico",
//             desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
//         },
//             {
//             title: "Conducci\u00f3n Eficiente",
//             desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
//         },
//             {
//             title: "Tecnolog\u00edas Innovadoras",
//             desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
//         },
//         ],
//     },
//     {
//         id: "t60-max",
//         brand: "maxus",
//         name: "T60 MAX",
//         category: "Pick-Up",
//         price: 20590000,
//         vehicleType: "liviano",
//         ivaIncluded: false,
//         isHybrid: false,
//         isElectric: false,
//         isNew: false,
//         versions: [
//             {
//             name: "T60 MAX 4X4 GL 8AT E6",
//             motor: "2.0L Turbo Di\u00e9sel",
//             fuel: "Di\u00e9sel",
//             transmission: "Autom\u00e1tica",
//             power: "163 HP",
//             torque: "400 Nm",
//             traction: "4x4",
//             doors: 4,
//             seats: 5,
//             airbags: 6,
//             listPrice: 24990000,
//             brandBonus: 3400000,
//             financingBonus: 1000000,
//             bonusPrice: 20590000,
//         },
//             {
//             name: "T60 MAX 4X4 GLX 8AT E6",
//             motor: "2.0L Turbo Di\u00e9sel",
//             fuel: "Di\u00e9sel",
//             transmission: "Autom\u00e1tica",
//             power: "163 HP",
//             torque: "400 Nm",
//             traction: "4x4",
//             doors: 4,
//             seats: 5,
//             airbags: 6,
//             listPrice: 26990000,
//             brandBonus: 3000000,
//             financingBonus: 1000000,
//             bonusPrice: 22990000,
//         },
//         ],
//         slogan: "Potencia para rendir al m\u00e1ximo",
//         videoUrl: "CARACTER\u00cdSTICAS:",
//         features: [
//             {
//             title: "Dise\u00f1o Din\u00e1mico",
//             desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
//         },
//             {
//             title: "Conducci\u00f3n Eficiente",
//             desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
//         },
//             {
//             title: "Tecnolog\u00edas Innovadoras",
//             desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
//         },
//         ],
//     },
//     {
//         id: "edeliver-9-cargo",
//         brand: "maxus",
//         name: "eDeliver 9 Cargo",
//         category: "Eléctrico, Furgón",
//         price: 34990000,
//         vehicleType: "liviano",
//         ivaIncluded: false,
//         isHybrid: false,
//         isElectric: true,
//         isNew: false,
//         versions: [
//             {
//             name: "EDELIVER 9 CARGO L2H2",
//             motor: "Motor El\u00e9ctrico",
//             fuel: "El\u00e9ctrico",
//             transmission: "Autom\u00e1tica",
//             electricRange: "180 km",
//             power: "200 HP",
//             torque: "310 Nm",
//             traction: "4x2",
//             seats: 3,
//             airbags: 2,
//             listPrice: 34990000,
//             brandBonus: 0,
//             financingBonus: 0,
//             bonusPrice: 34990000,
//         },
//             {
//             name: "EDELIVER 9 CARGO L3H2",
//             motor: "Motor El\u00e9ctrico",
//             fuel: "El\u00e9ctrico",
//             transmission: "Autom\u00e1tica",
//             electricRange: "248 km",
//             power: "200 HP",
//             torque: "310 Nm",
//             traction: "4x2",
//             seats: 3,
//             airbags: 2,
//             listPrice: 41990000,
//             brandBonus: 0,
//             financingBonus: 0,
//             bonusPrice: 41990000,
//         },
//         ],
//         slogan: "Van el\u00e9ctrica cero emisiones con est\u00e1ndar de carga europeo",
//         videoUrl: "CARACTER\u00cdSTICAS:",
//         features: [
//             {
//             title: "Dise\u00f1o Din\u00e1mico",
//             desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
//         },
//             {
//             title: "Conducci\u00f3n Eficiente",
//             desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
//         },
//             {
//             title: "Tecnolog\u00edas Innovadoras",
//             desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
//         },
//         ],
//     },
];
