import { Vehicle } from './types';

export const MINI_MODELS: Vehicle[] = [
    {
        id: "aceman",
        brand: "mini",
        name: "Aceman",
        category: "Aceman, Eléctrico",
        price: 29990000,
        image: "/images/mini/aceman.png",
        vehicleType: "liviano",
        ivaIncluded: true,
        isHybrid: false,
        isElectric: true,
        isNew: false,
        versions: [
            {
            name: "ACEMAN E CLASSIC",
            motor: "Motor El\u00e9ctrico S\u00edncrono",
            fuel: "El\u00e9ctrico",
            transmission: "Autom\u00e1tica",
            consumptionMixed: "14,1 kWh/100km",
            electricRange: "300 km",
            torque: "290 Nm",
            traction: "4x2",
            listPrice: 36990000,
            brandBonus: 0,
            financingBonus: 7000000,
            bonusPrice: 29990000,
        },
            {
            name: "ACEMAN SE FAVOURED",
            motor: "Motor El\u00e9ctrico S\u00edncrono",
            fuel: "El\u00e9ctrico",
            transmission: "Autom\u00e1tica",
            consumptionMixed: "14,0 kWh/100km",
            electricRange: "400 km",
            torque: "330 Nm",
            traction: "4x2",
            listPrice: 41990000,
            brandBonus: 0,
            financingBonus: 5000000,
            bonusPrice: 36990000,
        },
        ],
        slogan: "Lado vanguardista",
        videoUrl: "CARACTER\u00cdSTICAS:",
        features: [
            {
            title: "Dise\u00f1o Din\u00e1mico",
            desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
            image: "/images/mini/ACEMAN/caracteristicas/MINI_MODES.jpg",
        },
            {
            title: "Conducci\u00f3n Eficiente",
            desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
            image: "/images/mini/ACEMAN/caracteristicas/P90546349_lowRes_mini-aceman-se-04-20.jpg",
        },
            {
            title: "Tecnolog\u00edas Innovadoras",
            desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
            image: "/images/mini/ACEMAN/caracteristicas/Componente_A.jpg",
        },
        ],
        gallery: [
            "/images/mini/ACEMAN/galeria/desktop.jpg",
        ],
        desktopBanner: "/images/mini/ACEMAN/banner/BANNER.png",
    },
    {
        id: "cooper-cabrio",
        brand: "mini",
        name: "Cooper Cabrio",
        category: "Convertibles",
        price: 43990000,
        image: "/images/mini/COOPER-CABRIO/Banner_MINI_CABRIO.png",
        vehicleType: "liviano",
        ivaIncluded: true,
        isHybrid: false,
        isElectric: false,
        isNew: false,
        versions: [
            {
            name: "COOPER S 2.0 CABRIO FAVOURED",
            motor: "2.0L Twin Power Turbo",
            fuel: "Gasolina",
            transmission: "DCT / DSG",
            consumptionMixed: "15,4 km/l",
            power: "204 HP",
            torque: "300 Nm",
            traction: "4x2",
            listPrice: 45990000,
            brandBonus: 0,
            financingBonus: 2000000,
            bonusPrice: 43990000,
        },
        ],
        slogan: "Lado sin l\u00edmites",
        videoUrl: "CARACTER\u00cdSTICAS:",
        features: [
            {
            title: "Dise\u00f1o Din\u00e1mico",
            desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
            image: "/images/mini/COOPER-CABRIO/caracteristicas/MINI_PDP_FMA_Hero_desktop.jpg.miniusaimg.cover.jpeg",
        },
            {
            title: "Conducci\u00f3n Eficiente",
            desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
            image: "/images/mini/COOPER-CABRIO/caracteristicas/Cabrio_Arriba.png",
        },
            {
            title: "Tecnolog\u00edas Innovadoras",
            desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
            image: "/images/mini/COOPER-CABRIO/caracteristicas/CABRIO_ATRAS.png",
        },
        ],
        gallery: [
            "/images/mini/COOPER-CABRIO/galeria/MINI_Cabrio_Exterior_11.png",
        ],
    },
//     {
//         id: "cooper-3-puertas",
//         brand: "mini",
//         name: "Cooper 3 Puertas",
//         category: "Cooper",
//         price: 28990000,
//         vehicleType: "liviano",
//         ivaIncluded: true,
//         isHybrid: false,
//         isElectric: false,
//         isNew: false,
//         versions: [
//             {
//             name: "COOPER C 1.5 HB 3P CLASSIC",
//             motor: "1.5L Twin Power Turbo",
//             fuel: "Gasolina",
//             transmission: "DCT / DSG",
//             consumptionMixed: "17,5 km/l",
//             power: "156 HP",
//             torque: "230 Nm",
//             traction: "4x2",
//             listPrice: 34990000,
//             brandBonus: 0,
//             financingBonus: 6000000,
//             bonusPrice: 28990000,
//         },
//             {
//             name: "COOPER C 1.5 HB 3P FAVOURED",
//             motor: "1.5L Twin Power Turbo",
//             fuel: "Gasolina",
//             transmission: "DCT / DSG",
//             consumptionMixed: "17,0 km/l",
//             power: "156 HP",
//             torque: "230 Nm",
//             traction: "4x2",
//             listPrice: 36990000,
//             brandBonus: 0,
//             financingBonus: 3000000,
//             bonusPrice: 33990000,
//         },
//             {
//             name: "COOPER S 2.0 HB 3P FAVOURED",
//             motor: "2.0L Twin Power Turbo",
//             fuel: "Gasolina",
//             transmission: "DCT / DSG",
//             consumptionMixed: "15,0 km/l",
//             power: "204 HP",
//             torque: "300 Nm",
//             traction: "4x2",
//             listPrice: 39990000,
//             brandBonus: 0,
//             financingBonus: 4000000,
//             bonusPrice: 35990000,
//         },
//         ],
//         slogan: "Lado urbano",
//         videoUrl: "CARACTER\u00cdSTICAS:",
//         features: [
//             {
//             title: "Dise\u00f1o Din\u00e1mico",
//             desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
//         },
//             {
//             title: "Conducci\u00f3n Eficiente",
//             desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
//         },
//             {
//             title: "Tecnolog\u00edas Innovadoras",
//             desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
//         },
//         ],
//     },
//     {
//         id: "cooper-5-puertas",
//         brand: "mini",
//         name: "Cooper 5 Puertas",
//         category: "Cooper",
//         price: 33990000,
//         vehicleType: "liviano",
//         ivaIncluded: true,
//         isHybrid: false,
//         isElectric: false,
//         isNew: false,
//         versions: [
//             {
//             name: "COOPER C 1.5 HB 5P CLASSIC",
//             motor: "1.5L Twin Power Turbo",
//             fuel: "Gasolina",
//             transmission: "DCT / DSG",
//             consumptionMixed: "15,8 km/l",
//             power: "156 HP",
//             torque: "230 Nm",
//             traction: "4x2",
//             listPrice: 35990000,
//             brandBonus: 0,
//             financingBonus: 2000000,
//             bonusPrice: 33990000,
//         },
//             {
//             name: "COOPER S 2.0 HB 5P FAVOURED",
//             motor: "2.0L Twin Power Turbo",
//             fuel: "Gasolina",
//             transmission: "DCT / DSG",
//             consumptionMixed: "15,3 km/l",
//             power: "204 HP",
//             torque: "300 Nm",
//             traction: "4x2",
//             listPrice: 40990000,
//             brandBonus: 0,
//             financingBonus: 5000000,
//             bonusPrice: 35990000,
//         },
//         ],
//         slogan: "Lado urbano",
//         videoUrl: "CARACTER\u00cdSTICAS:",
//         features: [
//             {
//             title: "Dise\u00f1o Din\u00e1mico",
//             desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
//         },
//             {
//             title: "Conducci\u00f3n Eficiente",
//             desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
//         },
//             {
//             title: "Tecnolog\u00edas Innovadoras",
//             desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
//         },
//         ],
//     },
//     {
//         id: "cooper-el\u00e9ctrico",
//         brand: "mini",
//         name: "Cooper El\u00e9ctrico",
//         category: "Cooper, Eléctrico",
//         price: 29990000,
//         vehicleType: "liviano",
//         ivaIncluded: true,
//         isHybrid: false,
//         isElectric: true,
//         isNew: false,
//         versions: [
//             {
//             name: "COOPER E CLASSIC",
//             motor: "Motor El\u00e9ctrico S\u00edncrono",
//             fuel: "El\u00e9ctrico",
//             transmission: "Autom\u00e1tica",
//             consumptionMixed: "5,5 km/kWh",
//             electricRange: "300 km",
//             power: "184 HP",
//             torque: "290 Nm",
//             traction: "4x2",
//             listPrice: 35990000,
//             brandBonus: 0,
//             financingBonus: 6000000,
//             bonusPrice: 29990000,
//         },
//             {
//             name: "COOPER SE FAVOURED",
//             motor: "Motor El\u00e9ctrico S\u00edncrono",
//             fuel: "El\u00e9ctrico",
//             transmission: "Autom\u00e1tica",
//             consumptionMixed: "6,3 km/kWh",
//             electricRange: "400 km",
//             power: "218 HP",
//             torque: "330 Nm",
//             traction: "4x2",
//             listPrice: 40990000,
//             brandBonus: 0,
//             financingBonus: 3000000,
//             bonusPrice: 37990000,
//         },
//         ],
//         slogan: "Lado innovador",
//         videoUrl: "CARACTER\u00cdSTICAS:",
//         features: [
//             {
//             title: "Dise\u00f1o Din\u00e1mico",
//             desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
//         },
//             {
//             title: "Conducci\u00f3n Eficiente",
//             desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
//         },
//             {
//             title: "Tecnolog\u00edas Innovadoras",
//             desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
//         },
//         ],
//     },
//     {
//         id: "countryman-el\u00e9ctrico",
//         brand: "mini",
//         name: "Countryman El\u00e9ctrico",
//         category: "Countryman, Eléctrico",
//         price: 48990000,
//         vehicleType: "liviano",
//         ivaIncluded: true,
//         isHybrid: false,
//         isElectric: true,
//         isNew: false,
//         versions: [
//             {
//             name: "COUNTRYMAN E CLASSIC",
//             motor: "Motor El\u00e9ctrico S\u00edncrono",
//             fuel: "El\u00e9ctrico",
//             transmission: "Autom\u00e1tica",
//             electricRange: "462 km",
//             power: "204 HP",
//             torque: "250 Nm",
//             traction: "4x2",
//             listPrice: 48990000,
//             brandBonus: 0,
//             financingBonus: 0,
//             bonusPrice: 48990000,
//         },
//         ],
//         slogan: "Lado innovador",
//         videoUrl: "CARACTER\u00cdSTICAS:",
//         features: [
//             {
//             title: "Dise\u00f1o Din\u00e1mico",
//             desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
//         },
//             {
//             title: "Conducci\u00f3n Eficiente",
//             desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
//         },
//             {
//             title: "Tecnolog\u00edas Innovadoras",
//             desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
//         },
//         ],
//     },
//     {
//         id: "jcw-3-puertas",
//         brand: "mini",
//         name: "JCW 3 Puertas",
//         category: "John Cooper Works",
//         price: 38990000,
//         vehicleType: "liviano",
//         ivaIncluded: true,
//         isHybrid: false,
//         isElectric: false,
//         isNew: false,
//         versions: [
//             {
//             name: "COOPER JCW SPITFIRE 2.0 HB 3P",
//             motor: "2.0L Twin Power Turbo",
//             fuel: "Gasolina",
//             transmission: "DCT / DSG",
//             consumptionMixed: "14,7 km/l",
//             power: "231 HP",
//             torque: "380 Nm",
//             traction: "4x2",
//             listPrice: 44990000,
//             brandBonus: 0,
//             financingBonus: 6000000,
//             bonusPrice: 38990000,
//         },
//             {
//             name: "COOPER JCW 2.0 HB 3P",
//             motor: "2.0L Twin Power Turbo",
//             fuel: "Gasolina",
//             transmission: "DCT / DSG",
//             consumptionMixed: "14,7 km/l",
//             power: "231 HP",
//             torque: "380 Nm",
//             traction: "4x2",
//             listPrice: 48990000,
//             brandBonus: 0,
//             financingBonus: 2000000,
//             bonusPrice: 46990000,
//         },
//             {
//             name: "COOPER JCW 2.0 HB 3P GP INSPIRED",
//             motor: "2.0L Twin Power Turbo",
//             fuel: "Gasolina",
//             transmission: "DCT / DSG",
//             consumptionMixed: "14,7 km/l",
//             power: "231 HP",
//             torque: "380 Nm",
//             traction: "4x2",
//             listPrice: 49990000,
//             brandBonus: 0,
//             financingBonus: 2000000,
//             bonusPrice: 47990000,
//         },
//         ],
//         slogan: "Lado deportivo",
//         videoUrl: "CARACTER\u00cdSTICAS:",
//         features: [
//             {
//             title: "Dise\u00f1o Din\u00e1mico",
//             desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
//         },
//             {
//             title: "Conducci\u00f3n Eficiente",
//             desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
//         },
//             {
//             title: "Tecnolog\u00edas Innovadoras",
//             desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
//         },
//         ],
//     },
//     {
//         id: "jcw-cabrio",
//         brand: "mini",
//         name: "JCW Cabrio",
//         category: "Convertibles, John Cooper Works",
//         price: 46490000,
//         vehicleType: "liviano",
//         ivaIncluded: true,
//         isHybrid: false,
//         isElectric: false,
//         isNew: false,
//         versions: [
//             {
//             name: "COOPER JCW SPITFIRE CABRIO 2.0",
//             motor: "2.0L Twin Power Turbo",
//             fuel: "Gasolina",
//             transmission: "DCT / DSG",
//             consumptionMixed: "14,7 km/l",
//             power: "231 HP",
//             torque: "380 Nm",
//             traction: "4x2",
//             listPrice: 47990000,
//             brandBonus: 0,
//             financingBonus: 1500000,
//             bonusPrice: 46490000,
//         },
//             {
//             name: "COOPER JCW CABRIO 2.0",
//             motor: "2.0L Twin Power Turbo",
//             fuel: "Gasolina",
//             transmission: "DCT / DSG",
//             consumptionMixed: "14,7 km/l",
//             power: "231 HP",
//             torque: "380 Nm",
//             traction: "4x2",
//             listPrice: 50990000,
//             brandBonus: 0,
//             financingBonus: 1500000,
//             bonusPrice: 49490000,
//         },
//         ],
//         slogan: "Lado deportivo",
//         videoUrl: "CARACTER\u00cdSTICAS:",
//         features: [
//             {
//             title: "Dise\u00f1o Din\u00e1mico",
//             desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
//         },
//             {
//             title: "Conducci\u00f3n Eficiente",
//             desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
//         },
//             {
//             title: "Tecnolog\u00edas Innovadoras",
//             desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
//         },
//         ],
//     },
//     {
//         id: "jcw-countryman-all4",
//         brand: "mini",
//         name: "JCW Countryman ALL4",
//         category: "John Cooper Works",
//         price: 53490000,
//         vehicleType: "liviano",
//         ivaIncluded: true,
//         isHybrid: false,
//         isElectric: false,
//         isNew: false,
//         versions: [
//             {
//             name: "COUNTRYMAN JCW ALL4 2.0",
//             motor: "2.0L Twin Power Turbo",
//             fuel: "Gasolina",
//             transmission: "DCT / DSG",
//             consumptionMixed: "12,8 km/l",
//             power: "300 HP",
//             torque: "400 Nm",
//             traction: "AWD",
//             listPrice: 54990000,
//             brandBonus: 0,
//             financingBonus: 1500000,
//             bonusPrice: 53490000,
//         },
//         ],
//         slogan: "Lado deportivo",
//         videoUrl: "CARACTER\u00cdSTICAS:",
//         features: [
//             {
//             title: "Dise\u00f1o Din\u00e1mico",
//             desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
//         },
//             {
//             title: "Conducci\u00f3n Eficiente",
//             desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
//         },
//             {
//             title: "Tecnolog\u00edas Innovadoras",
//             desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
//         },
//         ],
//     },
//     {
//         id: "jcw-el\u00e9ctrico",
//         brand: "mini",
//         name: "JCW El\u00e9ctrico",
//         category: "Eléctrico, John Cooper Works",
//         price: 43490000,
//         vehicleType: "liviano",
//         ivaIncluded: true,
//         isHybrid: false,
//         isElectric: true,
//         isNew: false,
//         versions: [
//             {
//             name: "COOPER JCW E HEA",
//             motor: "Motor El\u00e9ctrico S\u00edncrono",
//             fuel: "El\u00e9ctrico",
//             transmission: "Autom\u00e1tica",
//             consumptionMixed: "6,3 km/kWh",
//             power: "258 HP",
//             torque: "350 Nm",
//             traction: "4x2",
//             listPrice: 46990000,
//             brandBonus: 0,
//             financingBonus: 3500000,
//             bonusPrice: 43490000,
//         },
//             {
//             name: "COOPER JCW E",
//             motor: "Motor El\u00e9ctrico S\u00edncrono",
//             fuel: "El\u00e9ctrico",
//             transmission: "Autom\u00e1tica",
//             consumptionMixed: "6,3 km/kWh",
//             power: "258 HP",
//             torque: "350 Nm",
//             traction: "4x2",
//             listPrice: 47990000,
//             brandBonus: 0,
//             financingBonus: 2000000,
//             bonusPrice: 45990000,
//         },
//         ],
//         slogan: "Lado deportivo",
//         videoUrl: "CARACTER\u00cdSTICAS:",
//         features: [
//             {
//             title: "Dise\u00f1o Din\u00e1mico",
//             desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
//         },
//             {
//             title: "Conducci\u00f3n Eficiente",
//             desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
//         },
//             {
//             title: "Tecnolog\u00edas Innovadoras",
//             desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
//         },
//         ],
//     },
    {
        id: "jcw-aceman",
        brand: "mini",
        name: "JCW Aceman",
        category: "John Cooper Works",
        price: 46990000,
        image: "/images/mini/JCW-ACEMAN/MINI_Aceman_Banner.jpg",
        vehicleType: "liviano",
        ivaIncluded: true,
        isHybrid: false,
        isElectric: true,
        isNew: false,
        versions: [
            {
            name: "ACEMAN JCW E",
            motor: "Motor El\u00e9ctrico S\u00edncrono",
            fuel: "El\u00e9ctrico",
            transmission: "Autom\u00e1tica",
            consumptionMixed: "16,4 kWh/100km",
            electricRange: "355 km",
            power: "258 HP",
            torque: "350 Nm",
            traction: "4x2",
            listPrice: 48990000,
            brandBonus: 0,
            financingBonus: 2000000,
            bonusPrice: 46990000,
        },
        ],
        slogan: "Lado deportivo",
        videoUrl: "CARACTER\u00cdSTICAS:",
        features: [
            {
            title: "Dise\u00f1o Din\u00e1mico",
            desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
            image: "/images/mini/JCW-ACEMAN/caracteristicas/MINI_Aceman_3.jpg",
        },
            {
            title: "Conducci\u00f3n Eficiente",
            desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
            image: "/images/mini/JCW-ACEMAN/caracteristicas/MINI_ACEMAN_4.jpg",
        },
            {
            title: "Tecnolog\u00edas Innovadoras",
            desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
            image: "/images/mini/JCW-ACEMAN/caracteristicas/Llave_Digital_1.jpg",
        },
        ],
        gallery: [
            "/images/mini/JCW-ACEMAN/galeria/BANNER_2_JCW_Aceman.jpg",
        ],
    },
    {
        id: "jcw-countryman-4all",
        brand: "mini",
        name: "Countryman",
        category: "Countryman",
        price: 34990000,
        image: "/images/mini/JCW-COUNTRYMAN-4ALL/mini-U25-stage-superwide.webp",
        vehicleType: "liviano",
        ivaIncluded: true,
        isHybrid: false,
        isElectric: false,
        isNew: false,
        versions: [
            {
            name: "COUNTRYMAN C 1.5 CLASSIC",
            motor: "1.5L Twin Power Turbo",
            fuel: "Gasolina",
            transmission: "DCT / DSG",
            consumptionMixed: "16,4 km/l",
            power: "156 HP",
            torque: "280 Nm",
            traction: "4x2",
            listPrice: 37990000,
            brandBonus: 0,
            financingBonus: 3000000,
            bonusPrice: 34990000,
        },
            {
            name: "COUNTRYMAN C 1.5 FAVOURED",
            motor: "1.5L Twin Power Turbo",
            fuel: "Gasolina",
            transmission: "DCT / DSG",
            consumptionMixed: "15,4 km/l",
            power: "156 HP",
            torque: "230 Nm",
            traction: "4x2",
            listPrice: 41990000,
            brandBonus: 0,
            financingBonus: 0,
            bonusPrice: 41990000,
        },
            {
            name: "COUNTRYMAN S ALL4 2.0 FAVOURED",
            motor: "2.0L Twin Power Turbo",
            fuel: "Gasolina",
            transmission: "DCT / DSG",
            consumptionMixed: "13,5 km/l",
            power: "204 HP",
            torque: "300 Nm",
            traction: "AWD",
            listPrice: 48990000,
            brandBonus: 0,
            financingBonus: 1000000,
            bonusPrice: 47990000,
        },
            {
            name: "COUNTRYMAN D 2.0 FAVOURED",
            motor: "2.0L Twin Power Turbo",
            fuel: "Di\u00e9sel",
            transmission: "DCT / DSG",
            consumptionMixed: "15,4 km/l",
            power: "150 HP",
            torque: "360 Nm",
            traction: "4x2",
            listPrice: 43990000,
            brandBonus: 0,
            financingBonus: 5000000,
            bonusPrice: 38990000,
        },
        ],
        slogan: "Lado aventurero",
        videoUrl: "CARACTER\u00cdSTICAS:",
        features: [
            {
            title: "Dise\u00f1o Din\u00e1mico",
            desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
            image: "/images/mini/JCW-COUNTRYMAN-4ALL/caracteristicas/MINI_Countryman_--_Interior.png",
        },
            {
            title: "Conducci\u00f3n Eficiente",
            desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
            image: "/images/mini/JCW-COUNTRYMAN-4ALL/caracteristicas/MINI_Countryman_1.png",
        },
            {
            title: "Tecnolog\u00edas Innovadoras",
            desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
            image: "/images/mini/JCW-COUNTRYMAN-4ALL/caracteristicas/Llave_Digital_1.jpg",
        },
        ],
    },
];
