import { Vehicle } from './types';

export const SOUEAST_MODELS: Vehicle[] = [
//     {
//         id: "s06",
//         brand: "soueast",
//         name: "S06",
//         category: "SUV",
//         price: 14990000,
//         vehicleType: "liviano",
//         ivaIncluded: true,
//         isHybrid: false,
//         isElectric: false,
//         isNew: false,
//         versions: [
//             {
//             name: "1.5T 6DCT LUX",
//             motor: "1.5L Turbo",
//             fuel: "Gasolina",
//             transmission: "DCT / DSG",
//             power: "154 HP",
//             traction: "4x2",
//             seats: 5,
//             airbags: 6,
//             listPrice: 17990000,
//             brandBonus: 2000000,
//             financingBonus: 1000000,
//             bonusPrice: 14990000,
//         },
//             {
//             name: "1.6T 7DCT LUX",
//             motor: "1.6L Turbo",
//             fuel: "Gasolina",
//             transmission: "DCT / DSG",
//             power: "194 HP",
//             traction: "4x2",
//             seats: 5,
//             airbags: 6,
//             listPrice: 18990000,
//             brandBonus: 2000000,
//             financingBonus: 1000000,
//             bonusPrice: 15990000,
//         },
//             {
//             name: "1.6T 7DCT LIMITED",
//             motor: "1.6L Turbo",
//             fuel: "Gasolina",
//             transmission: "DCT / DSG",
//             power: "194 HP",
//             traction: "4x2",
//             seats: 5,
//             airbags: 6,
//             listPrice: 20490000,
//             brandBonus: 2000000,
//             financingBonus: 1000000,
//             bonusPrice: 17490000,
//         },
//         ],
//         slogan: "SUV Urbano, Seguro y Tecnol\u00f3gico",
//         videoUrl: "CARACTER\u00cdSTICAS:",
//         features: [
//             {
//             title: "Dise\u00f1o Din\u00e1mico",
//             desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
//         },
//             {
//             title: "Conducci\u00f3n Eficiente",
//             desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
//         },
//             {
//             title: "Tecnolog\u00edas Innovadoras",
//             desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
//         },
//         ],
//     },
//     {
//         id: "s06-phev",
//         brand: "soueast",
//         name: "S06 PHEV",
//         category: "Híbrido, SUV",
//         price: 21990000,
//         vehicleType: "liviano",
//         ivaIncluded: true,
//         isHybrid: true,
//         isElectric: false,
//         isNew: false,
//         versions: [
//             {
//             name: "S06 PHEV LIMITED",
//             motor: "1.5L Turbo",
//             fuel: "H\u00edbrido",
//             transmission: "Autom\u00e1tica",
//             electricRange: "1140 km",
//             power: "355 HP",
//             traction: "4x2",
//             seats: 5,
//             airbags: 6,
//             listPrice: 26990000,
//             brandBonus: 3000000,
//             financingBonus: 2000000,
//             bonusPrice: 21990000,
//         },
//         ],
//         slogan: "SUV H\u00edbrido Enchufable",
//         videoUrl: "CARACTER\u00cdSTICAS:",
//         features: [
//             {
//             title: "Dise\u00f1o Din\u00e1mico",
//             desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
//         },
//             {
//             title: "Conducci\u00f3n Eficiente",
//             desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
//         },
//             {
//             title: "Tecnolog\u00edas Innovadoras",
//             desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
//         },
//         ],
//     },
//     {
//         id: "s07",
//         brand: "soueast",
//         name: "S07",
//         category: "SUV",
//         price: 15990000,
//         vehicleType: "liviano",
//         ivaIncluded: true,
//         isHybrid: false,
//         isElectric: false,
//         isNew: false,
//         versions: [
//             {
//             name: "1.5T 6DCT",
//             motor: "1.5L Turbo",
//             fuel: "Gasolina",
//             transmission: "DCT / DSG",
//             power: "154 HP",
//             traction: "4x2",
//             seats: 7,
//             airbags: 6,
//             listPrice: 17990000,
//             brandBonus: 1000000,
//             financingBonus: 1000000,
//             bonusPrice: 15990000,
//         },
//             {
//             name: "1.6T 7DCT",
//             motor: "1.6L Turbo",
//             fuel: "Gasolina",
//             transmission: "DCT / DSG",
//             power: "194 HP",
//             traction: "4x2",
//             seats: 7,
//             airbags: 6,
//             listPrice: 19490000,
//             brandBonus: 1000000,
//             financingBonus: 1000000,
//             bonusPrice: 17490000,
//         },
//         ],
//         slogan: "SUV Familiar 7 pasajeros Espacioso y Tecnol\u00f3gico",
//         videoUrl: "CARACTER\u00cdSTICAS:",
//         features: [
//             {
//             title: "Dise\u00f1o Din\u00e1mico",
//             desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
//         },
//             {
//             title: "Conducci\u00f3n Eficiente",
//             desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
//         },
//             {
//             title: "Tecnolog\u00edas Innovadoras",
//             desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
//         },
//         ],
//     },
//     {
//         id: "s09",
//         brand: "soueast",
//         name: "S09",
//         category: "SUV",
//         price: 22990000,
//         vehicleType: "liviano",
//         ivaIncluded: true,
//         isHybrid: false,
//         isElectric: false,
//         isNew: false,
//         versions: [
//             {
//             name: "2.0T 7DCT",
//             motor: "2.0L Turbo",
//             fuel: "Gasolina",
//             transmission: "DCT / DSG",
//             power: "255 HP",
//             traction: "4x2",
//             seats: 7,
//             airbags: 6,
//             listPrice: 25990000,
//             brandBonus: 1500000,
//             financingBonus: 1500000,
//             bonusPrice: 22990000,
//         },
//         ],
//         slogan: "SUV Familiar 7 pasajeros Espacioso y Tecnol\u00f3gico",
//         videoUrl: "CARACTER\u00cdSTICAS:",
//         features: [
//             {
//             title: "Dise\u00f1o Din\u00e1mico",
//             desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
//         },
//             {
//             title: "Conducci\u00f3n Eficiente",
//             desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
//         },
//             {
//             title: "Tecnolog\u00edas Innovadoras",
//             desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
//         },
//         ],
//     },
];
