import { Vehicle } from './types';

export const TOYOTA_MODELS: Vehicle[] = [
    {
        id: "4runner",
        brand: "toyota",
        name: "4Runner",
        category: "SUV",
        price: 51490000,
        image: "/images/toyota/4runner/min-4runner.png",
        vehicleType: "liviano",
        ivaIncluded: true,
        isHybrid: false,
        isElectric: false,
        isNew: false,
        versions: [
            {
            name: "4Runner SR5 2.4 TA 4X4",
            motor: "2.4L Turbo",
            fuel: "Gasolina",
            transmission: "Autom\u00e1tica",
            traction: "4x4",
            airbags: 8,
            listPrice: 52990000,
            brandBonus: 0,
            financingBonus: 500000,
            bonusPrice: 52490000,
        },
            {
            name: "4Runner SR5 2.4 TA 4X4",
            motor: "2.4L Turbo",
            fuel: "Gasolina",
            transmission: "Autom\u00e1tica",
            traction: "4x4",
            airbags: 8,
            listPrice: 52990000,
            brandBonus: 1000000,
            financingBonus: 500000,
            bonusPrice: 51490000,
        },
            {
            name: "4Runner Limited 2.4 TA 4X4",
            motor: "2.4L Turbo",
            fuel: "Gasolina",
            transmission: "Autom\u00e1tica",
            traction: "4x4",
            airbags: 8,
            listPrice: 58990000,
            brandBonus: 1000000,
            financingBonus: 500000,
            bonusPrice: 57490000,
        },
        ],
        slogan: "El modelo que buscabas, ahora m\u00e1s cerca que nunca",
        videoUrl: "CARACTER\u00cdSTICAS:",
        features: [
            {
            title: "Dise\u00f1o Din\u00e1mico",
            desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
            image: "/images/toyota/4runner/caracteristicas/AIRBAGS.png",
        },
            {
            title: "Conducci\u00f3n Eficiente",
            desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
            image: "/images/toyota/4runner/caracteristicas/TECNO-SAFETY.jpg",
        },
            {
            title: "Tecnolog\u00edas Innovadoras",
            desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
            image: "/images/toyota/4runner/caracteristicas/TNGA.jpg",
        },
        ],
        gallery: [
            "/images/toyota/4runner/galeria/galeria_87532.png",
            "/images/toyota/4runner/galeria/galeria_87713.png",
            "/images/toyota/4runner/galeria/galeria_87819.png",
            "/images/toyota/4runner/galeria/galeria_87943.png",
            "/images/toyota/4runner/galeria/galeria_88106.png",
            "/images/toyota/4runner/galeria/galeria_88218.png",
            "/images/toyota/4runner/galeria/galeria_88361.png",
            "/images/toyota/4runner/galeria/galeria_88549.png",
            "/images/toyota/4runner/galeria/galeria_88700.png",
            "/images/toyota/4runner/galeria/galeria_88854.png",
            "/images/toyota/4runner/galeria/galeria_89022.png",
            "/images/toyota/4runner/galeria/galeria_89134.png",
        ],
        desktopBanner: "/images/toyota/4runner/banner/banner-web.jpg",
    },
    {
        id: "all-new-rav4-hybrid",
        brand: "toyota",
        name: "RAV4",
        category: "SUV",
        price: 26490000,
        image: "/images/toyota/All-New-RAV4-Hybrid/min-all-new-rav4-hibrida.webp",
        vehicleType: "liviano",
        ivaIncluded: true,
        isHybrid: false,
        isElectric: false,
        isNew: true,
        isFeatured: true,
        versions: [
            {
            name: "All New Rav4 LE 2.0 4x2 CVT",
            motor: "2.0L",
            fuel: "Gasolina",
            transmission: "CVT",
            consumptionMixed: "Mixto 14,3 km/l",
            power: "170 HP",
            torque: "203 NM",
            traction: "4x2",
            airbags: 7,
            listPrice: 27390000,
            brandBonus: 900000,
            financingBonus: 0,
            bonusPrice: 26490000,
        },
            {
            name: "All New Rav4 XLE 2.0 4x2 CVT",
            motor: "2.0L",
            fuel: "Gasolina",
            transmission: "CVT",
            consumptionMixed: "Mixto 14,3 km/l",
            power: "170 HP",
            torque: "203 NM",
            traction: "4x2",
            airbags: 7,
            listPrice: 30390000,
            brandBonus: 0,
            financingBonus: 0,
            bonusPrice: 30390000,
        },
            {
            name: "All New Rav4 LE 2.0 4x2 CVT",
            motor: "2.0L",
            fuel: "Gasolina",
            transmission: "CVT",
            consumptionMixed: "Mixto 14,3 km/l",
            power: "170 HP",
            torque: "203 NM",
            traction: "4x2",
            airbags: 7,
            listPrice: 28990000,
            brandBonus: 0,
            financingBonus: 1000000,
            bonusPrice: 27990000,
        },
            {
            name: "All New Rav4 LE 2.0 4x4 CVT",
            motor: "2.0L",
            fuel: "Gasolina",
            transmission: "CVT",
            consumptionMixed: "Mixto 13,8 km/l",
            power: "170 HP",
            torque: "203 NM",
            traction: "4x4",
            airbags: 7,
            listPrice: 29990000,
            brandBonus: 0,
            financingBonus: 1000000,
            bonusPrice: 28990000,
        },
            {
            name: "All New Rav4 XLE 2.0 4x2 CVT",
            motor: "2.0L",
            fuel: "Gasolina",
            transmission: "CVT",
            consumptionMixed: "Mixto 14,3 km/l",
            power: "170 HP",
            torque: "203 NM",
            traction: "4x2",
            airbags: 7,
            listPrice: 32490000,
            brandBonus: 0,
            financingBonus: 500000,
            bonusPrice: 31990000,
        },
        ],
        slogan: "RAV4 como nunca antes",
        videoUrl: "CARACTER\u00cdSTICAS:",
        features: [
            {
            title: "Dise\u00f1o Din\u00e1mico",
            desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
            image: "/images/toyota/All-New-RAV4-Hybrid/caracteristicas/RAV4_STATIC-16.2e16d0ba.fill-565x300.jpg",
        },
            {
            title: "Conducci\u00f3n Eficiente",
            desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
            image: "/images/toyota/All-New-RAV4-Hybrid/caracteristicas/RAV4_4-1.2e16d0ba.fill-565x300.jpg",
        },
            {
            title: "Tecnolog\u00edas Innovadoras",
            desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
            image: "/images/toyota/All-New-RAV4-Hybrid/caracteristicas/RAV4_1-3.2e16d0ba.fill-565x300.jpg",
        },
        ],
        gallery: [
            "/images/toyota/All-New-RAV4-Hybrid/galeria/RAV4_STATIC-26.original.jpg",
            "/images/toyota/All-New-RAV4-Hybrid/galeria/RAV4_STATIC-4.original.jpg",
        ],
        desktopBanner: "/images/toyota/All-New-RAV4-Hybrid/banner/1200X425.max-1200x425.jpg",
    },
//     {
//         id: "corolla-cross-h\u00edbrido",
//         brand: "toyota",
//         name: "Corolla Cross H\u00edbrido",
//         category: "Híbrido, SUV",
//         price: 25490000,
//         vehicleType: "liviano",
//         ivaIncluded: true,
//         isHybrid: true,
//         isElectric: false,
//         isNew: false,
//         versions: [
//             {
//             name: "Corolla Cross 1.8 XEI CVT HV",
//             motor: "1.8L H\u00edbrido",
//             fuel: "H\u00edbrido",
//             transmission: "CVT",
//             consumptionMixed: "Mixto 22,6 km/l",
//             power: "122 HP",
//             traction: "4x2",
//             airbags: 7,
//             listPrice: 27990000,
//             brandBonus: 2000000,
//             financingBonus: 500000,
//             bonusPrice: 25490000,
//         },
//             {
//             name: "Corolla Cross 1.8 SEG CVT HV",
//             motor: "1.8L H\u00edbrido",
//             fuel: "H\u00edbrido",
//             transmission: "CVT",
//             consumptionMixed: "Mixto 22,6 km/l",
//             power: "122 HP",
//             traction: "4x2",
//             airbags: 7,
//             listPrice: 29990000,
//             brandBonus: 0,
//             financingBonus: 0,
//             bonusPrice: 29990000,
//         },
//         ],
//         slogan: "La tradici\u00f3n de innovar",
//         videoUrl: "CARACTER\u00cdSTICAS:",
//         features: [
//             {
//             title: "Dise\u00f1o Din\u00e1mico",
//             desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
//         },
//             {
//             title: "Conducci\u00f3n Eficiente",
//             desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
//         },
//             {
//             title: "Tecnolog\u00edas Innovadoras",
//             desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
//         },
//         ],
//     },
//     {
//         id: "corolla-sedan-h\u00edbrido",
//         brand: "toyota",
//         name: "Corolla Sedan H\u00edbrido",
//         category: "Híbrido, Sedán",
//         price: 23290000,
//         vehicleType: "liviano",
//         ivaIncluded: true,
//         isHybrid: true,
//         isElectric: false,
//         isNew: false,
//         versions: [
//             {
//             name: "Corolla XLI 1.8 eCVT H\u00edbrido",
//             motor: "1.8L H\u00edbrido",
//             fuel: "H\u00edbrido",
//             transmission: "CVT",
//             consumptionMixed: "Mixto 21,8 km/l",
//             power: "122 HP",
//             torque: "142 Nm",
//             traction: "4x2",
//             airbags: 7,
//             listPrice: 24790000,
//             brandBonus: 900000,
//             financingBonus: 600000,
//             bonusPrice: 23290000,
//         },
//             {
//             name: "Corolla XEI 1.8 eCVT H\u00edbrido",
//             motor: "1.8L H\u00edbrido",
//             fuel: "H\u00edbrido",
//             transmission: "CVT",
//             consumptionMixed: "Mixto 21,8 km/l",
//             power: "122 HP",
//             torque: "142 Nm",
//             traction: "4x2",
//             airbags: 7,
//             listPrice: 25990000,
//             brandBonus: 200000,
//             financingBonus: 500000,
//             bonusPrice: 25290000,
//         },
//             {
//             name: "Corolla XEI 1.8 eCVT H\u00edbrido",
//             motor: "1.8L H\u00edbrido",
//             fuel: "H\u00edbrido",
//             transmission: "CVT",
//             consumptionMixed: "Mixto 21,8 km/l",
//             power: "122 HP",
//             torque: "142 Nm",
//             traction: "4x2",
//             airbags: 7,
//             listPrice: 25790000,
//             brandBonus: 200000,
//             financingBonus: 500000,
//             bonusPrice: 25090000,
//         },
//             {
//             name: "Corolla XEI 1.8 eCVT H\u00edbrido",
//             motor: "1.8L H\u00edbrido",
//             fuel: "H\u00edbrido",
//             transmission: "CVT",
//             consumptionMixed: "Mixto 21,8 km/l",
//             power: "122 HP",
//             torque: "142 Nm",
//             traction: "4x2",
//             airbags: 7,
//             listPrice: 25790000,
//             brandBonus: 400000,
//             financingBonus: 500000,
//             bonusPrice: 24890000,
//         },
//             {
//             name: "Corolla SEG 1.8 eCVT H\u00edbrido",
//             motor: "1.8L H\u00edbrido",
//             fuel: "H\u00edbrido",
//             transmission: "CVT",
//             consumptionMixed: "Mixto 21,8 km/l",
//             power: "122 HP",
//             torque: "142 Nm",
//             traction: "4x2",
//             airbags: 7,
//             listPrice: 28290000,
//             brandBonus: 500000,
//             financingBonus: 725000,
//             bonusPrice: 27065000,
//         },
//             {
//             name: "Corolla SEG 1.8 eCVT H\u00edbrido",
//             motor: "1.8L H\u00edbrido",
//             fuel: "H\u00edbrido",
//             transmission: "CVT",
//             consumptionMixed: "Mixto 21,8 km/l",
//             power: "122 HP",
//             torque: "142 Nm",
//             traction: "4x2",
//             airbags: 7,
//             listPrice: 28490000,
//             brandBonus: 500000,
//             financingBonus: 725000,
//             bonusPrice: 27265000,
//         },
//         ],
//         slogan: "El modelo que buscabas, ahora m\u00e1s cerca que nunca",
//         videoUrl: "CARACTER\u00cdSTICAS:",
//         features: [
//             {
//             title: "Dise\u00f1o Din\u00e1mico",
//             desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
//         },
//             {
//             title: "Conducci\u00f3n Eficiente",
//             desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
//         },
//             {
//             title: "Tecnolog\u00edas Innovadoras",
//             desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
//         },
//         ],
//     },
//     {
//         id: "rav4-h\u00edbrido",
//         brand: "toyota",
//         name: "RAV4 H\u00edbrido",
//         category: "Híbrido, SUV",
//         price: 32490000,
//         vehicleType: "liviano",
//         ivaIncluded: true,
//         isHybrid: true,
//         isElectric: false,
//         isNew: false,
//         versions: [
//             {
//             name: "Rav4 XLE HV 2.5 CVT",
//             motor: "2.5L H\u00edbrido",
//             fuel: "H\u00edbrido",
//             transmission: "CVT",
//             power: "219 HP",
//             traction: "4x2",
//             airbags: 7,
//             listPrice: 34690000,
//             brandBonus: 1700000,
//             financingBonus: 250000,
//             bonusPrice: 32740000,
//         },
//             {
//             name: "Rav4 XSE 2.5 4X2 CVT HV",
//             motor: "2.5L H\u00edbrido",
//             fuel: "H\u00edbrido",
//             transmission: "CVT",
//             power: "219 HP",
//             traction: "4x2",
//             airbags: 7,
//             listPrice: 40390000,
//             brandBonus: 1500000,
//             financingBonus: 0,
//             bonusPrice: 38890000,
//         },
//             {
//             name: "Rav4 LTD 2.5 4X4 CVT HV",
//             motor: "2.5L H\u00edbrido",
//             fuel: "H\u00edbrido",
//             transmission: "CVT",
//             consumptionMixed: "Mixto 21,4 km/l",
//             power: "219 HP",
//             traction: "4x4",
//             airbags: 7,
//             listPrice: 41890000,
//             brandBonus: 1000000,
//             financingBonus: 0,
//             bonusPrice: 40890000,
//         },
//             {
//             name: "Rav4 LE HEV 2.5 CVT",
//             motor: "2.5L H\u00edbrido",
//             fuel: "H\u00edbrido",
//             transmission: "CVT",
//             power: "219 HP",
//             traction: "4x2",
//             airbags: 7,
//             listPrice: 33490000,
//             brandBonus: 0,
//             financingBonus: 1000000,
//             bonusPrice: 32490000,
//         },
//             {
//             name: "All New Rav4 H\u00edbrido XLE HEV 2.5 4X2 CTV",
//             motor: "2.5L H\u00edbrido",
//             fuel: "H\u00edbrido",
//             transmission: "CVT",
//             power: "219 HP",
//             traction: "4x2",
//             airbags: 7,
//             listPrice: 36990000,
//             brandBonus: 0,
//             financingBonus: 0,
//             bonusPrice: 36990000,
//         },
//             {
//             name: "All New Rav4 H\u00edbrido XSE HEV 2.5 4X4 CTV",
//             motor: "2.5L H\u00edbrido",
//             fuel: "H\u00edbrido",
//             transmission: "CVT",
//             power: "219 HP",
//             traction: "4x4",
//             airbags: 7,
//             listPrice: 42990000,
//             brandBonus: 0,
//             financingBonus: 0,
//             bonusPrice: 42990000,
//         },
//         ],
//         slogan: "RAV4 como nunca antes",
//         videoUrl: "CARACTER\u00cdSTICAS:",
//         features: [
//             {
//             title: "Dise\u00f1o Din\u00e1mico",
//             desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
//         },
//             {
//             title: "Conducci\u00f3n Eficiente",
//             desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
//         },
//             {
//             title: "Tecnolog\u00edas Innovadoras",
//             desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
//         },
//         ],
//     },
//     {
//         id: "yaris-cross-h\u00edbrido",
//         brand: "toyota",
//         name: "Yaris Cross H\u00edbrido",
//         category: "Híbrido, SUV",
//         price: 21790000,
//         vehicleType: "liviano",
//         ivaIncluded: true,
//         isHybrid: true,
//         isElectric: false,
//         isNew: false,
//         versions: [
//             {
//             name: "Yaris Cross XI 1.5 H\u00edbrido CVT",
//             motor: "1.5L H\u00edbrido",
//             fuel: "H\u00edbrido",
//             transmission: "CVT",
//             power: "110 HP",
//             torque: "141 Nm",
//             traction: "4x2",
//             airbags: 6,
//             listPrice: 24590000,
//             brandBonus: 2000000,
//             financingBonus: 800000,
//             bonusPrice: 21790000,
//         },
//             {
//             name: "Yaris Cross XG 1.5 H\u00edbrido CVT",
//             motor: "1.5L H\u00edbrido",
//             fuel: "H\u00edbrido",
//             transmission: "CVT",
//             power: "110 HP",
//             torque: "141 Nm",
//             traction: "4x2",
//             airbags: 6,
//             listPrice: 25490000,
//             brandBonus: 0,
//             financingBonus: 600000,
//             bonusPrice: 24890000,
//         },
//         ],
//         slogan: "El modelo que buscabas, ahora m\u00e1s cerca que nunca",
//         videoUrl: "CARACTER\u00cdSTICAS:",
//         features: [
//             {
//             title: "Dise\u00f1o Din\u00e1mico",
//             desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
//         },
//             {
//             title: "Conducci\u00f3n Eficiente",
//             desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
//         },
//             {
//             title: "Tecnolog\u00edas Innovadoras",
//             desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
//         },
//         ],
//     },
//     {
//         id: "yaris-sedan-h\u00edbrido",
//         brand: "toyota",
//         name: "Yaris Sedan H\u00edbrido",
//         category: "Híbrido, Sedán",
//         price: 21390000,
//         vehicleType: "liviano",
//         ivaIncluded: true,
//         isHybrid: true,
//         isElectric: false,
//         isNew: false,
//         versions: [
//             {
//             name: "New Yaris Sedan HEV 1.5 AT G",
//             motor: "1.5L H\u00edbrido",
//             fuel: "H\u00edbrido",
//             transmission: "CVT",
//             consumptionMixed: "Mixto 21,3 km/L",
//             power: "101 HP",
//             traction: "4x2",
//             airbags: 6,
//             listPrice: 21990000,
//             brandBonus: 0,
//             financingBonus: 600000,
//             bonusPrice: 21390000,
//         },
//         ],
//         slogan: "El modelo que buscabas, ahora m\u00e1s cerca que nunca",
//         videoUrl: "CARACTER\u00cdSTICAS:",
//         features: [
//             {
//             title: "Dise\u00f1o Din\u00e1mico",
//             desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
//         },
//             {
//             title: "Conducci\u00f3n Eficiente",
//             desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
//         },
//             {
//             title: "Tecnolog\u00edas Innovadoras",
//             desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
//         },
//         ],
//     },
    {
        id: "bz4x",
        brand: "toyota",
        name: "bZ4X",
        category: "Eléctrico, SUV",
        price: 41990000,
        image: "/images/toyota/bz4x/min-bz4x.png",
        vehicleType: "liviano",
        ivaIncluded: true,
        isHybrid: false,
        isElectric: true,
        isNew: false,
        versions: [
            {
            name: "BZ4X LIMITED 4X2",
            motor: "Motor el\u00e9ctrico",
            fuel: "El\u00e9ctrico",
            transmission: "Autom\u00e1tica",
            electricRange: "478 km",
            power: "221 HP",
            torque: "269 Nm",
            traction: "4x2",
            airbags: 8,
            listPrice: 44990000,
            brandBonus: 0,
            financingBonus: 3000000,
            bonusPrice: 41990000,
        },
            {
            name: "BZ4X LIMITED AWD",
            motor: "2 Motores el\u00e9ctricos",
            fuel: "El\u00e9ctrico",
            transmission: "Autom\u00e1tica",
            electricRange: "453 km",
            power: "338 HP",
            torque: "338 Nm",
            traction: "AWD",
            airbags: 8,
            listPrice: 49990000,
            brandBonus: 0,
            financingBonus: 3000000,
            bonusPrice: 46990000,
        },
        ],
        slogan: "100% El\u00e9ctrico de Toyota",
        videoUrl: "CARACTER\u00cdSTICAS:",
        features: [
            {
            title: "Dise\u00f1o Din\u00e1mico",
            desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
            image: "/images/toyota/bz4x/caracteristicas/vsc.jpg",
        },
            {
            title: "Conducci\u00f3n Eficiente",
            desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
            image: "/images/toyota/bz4x/caracteristicas/tss.png",
        },
            {
            title: "Tecnolog\u00edas Innovadoras",
            desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
        },
        ],
        gallery: [
            "/images/toyota/bz4x/galeria/galeria_63622.jpg",
            "/images/toyota/bz4x/galeria/galeria_63737.jpg",
            "/images/toyota/bz4x/galeria/galeria_63792.jpg",
            "/images/toyota/bz4x/galeria/galeria_63860.jpg",
            "/images/toyota/bz4x/galeria/galeria_63918.jpg",
            "/images/toyota/bz4x/galeria/galeria_63959.jpg",
            "/images/toyota/bz4x/galeria/galeria_63999.jpg",
            "/images/toyota/bz4x/galeria/galeria_64144.png",
            "/images/toyota/bz4x/galeria/galeria_64289.png",
            "/images/toyota/bz4x/galeria/galeria_64360.png",
        ],
        desktopBanner: "/images/toyota/bz4x/banner/banner_63502.jpg",
    },
    {
        id: "corolla-cross-hybrid",
        brand: "toyota",
        name: "Corolla Cross H\u00edbrido",
        category: "Híbrido, SUV",
        price: 25490000,
        image: "/images/toyota/corolla-cross-hybrid/min-corolla-cross-hibrido.png",
        vehicleType: "liviano",
        ivaIncluded: true,
        isHybrid: true,
        isElectric: false,
        isNew: false,
        versions: [
            {
            name: "Corolla Cross 1.8 XEI CVT HV",
            motor: "1.8L H\u00edbrido",
            fuel: "H\u00edbrido",
            transmission: "CVT",
            consumptionMixed: "Mixto 22,6 km/l",
            power: "122 HP",
            traction: "4x2",
            airbags: 7,
            listPrice: 27990000,
            brandBonus: 2000000,
            financingBonus: 500000,
            bonusPrice: 25490000,
        },
            {
            name: "Corolla Cross 1.8 SEG CVT HV",
            motor: "1.8L H\u00edbrido",
            fuel: "H\u00edbrido",
            transmission: "CVT",
            consumptionMixed: "Mixto 22,6 km/l",
            power: "122 HP",
            traction: "4x2",
            airbags: 7,
            listPrice: 29990000,
            brandBonus: 0,
            financingBonus: 0,
            bonusPrice: 29990000,
        },
        ],
        slogan: "La tradici\u00f3n de innovar",
        videoUrl: "CARACTER\u00cdSTICAS:",
        features: [
            {
            title: "Dise\u00f1o Din\u00e1mico",
            desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
            image: "/images/toyota/corolla-cross-hybrid/caracteristicas/motores.jpg",
        },
            {
            title: "Conducci\u00f3n Eficiente",
            desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
            image: "/images/toyota/corolla-cross-hybrid/caracteristicas/toyota-safety.jpg",
        },
            {
            title: "Tecnolog\u00edas Innovadoras",
            desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
            image: "/images/toyota/corolla-cross-hybrid/caracteristicas/garantia-extendida.jpg",
        },
        ],
        gallery: [
            "/images/toyota/corolla-cross-hybrid/galeria/galeria_67189.jpg",
            "/images/toyota/corolla-cross-hybrid/galeria/galeria_68527.jpg",
            "/images/toyota/corolla-cross-hybrid/galeria/galeria_68596.jpg",
            "/images/toyota/corolla-cross-hybrid/galeria/galeria_68844.jpg",
            "/images/toyota/corolla-cross-hybrid/galeria/galeria_68913.jpg",
            "/images/toyota/corolla-cross-hybrid/galeria/galeria_69016.jpg",
            "/images/toyota/corolla-cross-hybrid/galeria/galeria_69072.jpg",
            "/images/toyota/corolla-cross-hybrid/galeria/galeria_69306.jpg",
            "/images/toyota/corolla-cross-hybrid/galeria/galeria_69424.png",
        ],
        desktopBanner: "/images/toyota/corolla-cross-hybrid/banner/banner_68478.jpg",
    },
    {
        id: "corolla-sedan-hibrido",
        brand: "toyota",
        name: "Corolla Sedan H\u00edbrido",
        category: "Híbrido, Sedán",
        price: 23290000,
        image: "/images/toyota/corolla-sedan-hibrido/min-corolla-sedan-hibrido.png",
        vehicleType: "liviano",
        ivaIncluded: true,
        isHybrid: true,
        isElectric: false,
        isNew: false,
        versions: [
            {
            name: "Corolla XLI 1.8 eCVT H\u00edbrido",
            motor: "1.8L H\u00edbrido",
            fuel: "H\u00edbrido",
            transmission: "CVT",
            consumptionMixed: "Mixto 21,8 km/l",
            power: "122 HP",
            torque: "142 Nm",
            traction: "4x2",
            airbags: 7,
            listPrice: 24790000,
            brandBonus: 900000,
            financingBonus: 600000,
            bonusPrice: 23290000,
        },
            {
            name: "Corolla XEI 1.8 eCVT H\u00edbrido",
            motor: "1.8L H\u00edbrido",
            fuel: "H\u00edbrido",
            transmission: "CVT",
            consumptionMixed: "Mixto 21,8 km/l",
            power: "122 HP",
            torque: "142 Nm",
            traction: "4x2",
            airbags: 7,
            listPrice: 25990000,
            brandBonus: 200000,
            financingBonus: 500000,
            bonusPrice: 25290000,
        },
            {
            name: "Corolla XEI 1.8 eCVT H\u00edbrido",
            motor: "1.8L H\u00edbrido",
            fuel: "H\u00edbrido",
            transmission: "CVT",
            consumptionMixed: "Mixto 21,8 km/l",
            power: "122 HP",
            torque: "142 Nm",
            traction: "4x2",
            airbags: 7,
            listPrice: 25790000,
            brandBonus: 200000,
            financingBonus: 500000,
            bonusPrice: 25090000,
        },
            {
            name: "Corolla XEI 1.8 eCVT H\u00edbrido",
            motor: "1.8L H\u00edbrido",
            fuel: "H\u00edbrido",
            transmission: "CVT",
            consumptionMixed: "Mixto 21,8 km/l",
            power: "122 HP",
            torque: "142 Nm",
            traction: "4x2",
            airbags: 7,
            listPrice: 25790000,
            brandBonus: 400000,
            financingBonus: 500000,
            bonusPrice: 24890000,
        },
            {
            name: "Corolla SEG 1.8 eCVT H\u00edbrido",
            motor: "1.8L H\u00edbrido",
            fuel: "H\u00edbrido",
            transmission: "CVT",
            consumptionMixed: "Mixto 21,8 km/l",
            power: "122 HP",
            torque: "142 Nm",
            traction: "4x2",
            airbags: 7,
            listPrice: 28290000,
            brandBonus: 500000,
            financingBonus: 725000,
            bonusPrice: 27065000,
        },
            {
            name: "Corolla SEG 1.8 eCVT H\u00edbrido",
            motor: "1.8L H\u00edbrido",
            fuel: "H\u00edbrido",
            transmission: "CVT",
            consumptionMixed: "Mixto 21,8 km/l",
            power: "122 HP",
            torque: "142 Nm",
            traction: "4x2",
            airbags: 7,
            listPrice: 28490000,
            brandBonus: 500000,
            financingBonus: 725000,
            bonusPrice: 27265000,
        },
        ],
        slogan: "El modelo que buscabas, ahora m\u00e1s cerca que nunca",
        videoUrl: "CARACTER\u00cdSTICAS:",
        features: [
            {
            title: "Dise\u00f1o Din\u00e1mico",
            desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
        },
            {
            title: "Conducci\u00f3n Eficiente",
            desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
        },
            {
            title: "Tecnolog\u00edas Innovadoras",
            desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
        },
        ],
        gallery: [
            "/images/toyota/corolla-sedan-hibrido/galeria/galeria_73510.jpg",
            "/images/toyota/corolla-sedan-hibrido/galeria/galeria_73547.jpg",
            "/images/toyota/corolla-sedan-hibrido/galeria/galeria_73603.jpg",
            "/images/toyota/corolla-sedan-hibrido/galeria/galeria_73655.jpg",
            "/images/toyota/corolla-sedan-hibrido/galeria/galeria_73708.jpg",
            "/images/toyota/corolla-sedan-hibrido/galeria/galeria_73782.jpg",
            "/images/toyota/corolla-sedan-hibrido/galeria/galeria_73877.jpg",
            "/images/toyota/corolla-sedan-hibrido/galeria/galeria_73958.jpg",
            "/images/toyota/corolla-sedan-hibrido/galeria/galeria_74049.jpg",
            "/images/toyota/corolla-sedan-hibrido/galeria/galeria_74098.jpg",
            "/images/toyota/corolla-sedan-hibrido/galeria/galeria_74156.jpg",
            "/images/toyota/corolla-sedan-hibrido/galeria/galeria_74237.jpg",
            "/images/toyota/corolla-sedan-hibrido/galeria/galeria_74294.jpg",
            "/images/toyota/corolla-sedan-hibrido/galeria/galeria_74389.jpg",
            "/images/toyota/corolla-sedan-hibrido/galeria/galeria_74473.jpg",
            "/images/toyota/corolla-sedan-hibrido/galeria/galeria_74566.jpg",
            "/images/toyota/corolla-sedan-hibrido/galeria/galeria_74734.jpg",
            "/images/toyota/corolla-sedan-hibrido/galeria/galeria_74841.jpg",
            "/images/toyota/corolla-sedan-hibrido/galeria/galeria_74966.jpg",
            "/images/toyota/corolla-sedan-hibrido/galeria/galeria_75093.jpg",
        ],
        desktopBanner: "/images/toyota/corolla-sedan-hibrido/banner/banner_73380.jpg",
    },
    {
        id: "fortuner",
        brand: "toyota",
        name: "Fortuner",
        category: "SUV",
        price: 39790000,
        image: "/images/toyota/fortuner/min-fortuner.png",
        vehicleType: "liviano",
        ivaIncluded: true,
        isHybrid: false,
        isElectric: false,
        isNew: false,
        versions: [
            {
            name: "Fortuner SR5 4x4 AT TDI 2.8L Diesel",
            motor: "2.8L Turbo Di\u00e9sel",
            fuel: "Di\u00e9sel",
            transmission: "Autom\u00e1tica",
            consumptionMixed: "Mixto 12,0 km/l",
            power: "201 HP",
            torque: "420 Nm",
            traction: "4x4",
            airbags: 7,
            listPrice: 44390000,
            brandBonus: 1000000,
            financingBonus: 1000000,
            bonusPrice: 42390000,
        },
            {
            name: "Fortuner SRX 4x4 AT TDI 2.8L Diesel",
            motor: "2.8L Turbo Di\u00e9sel",
            fuel: "Di\u00e9sel",
            transmission: "Autom\u00e1tica",
            consumptionMixed: "Mixto 12,0 km/l",
            power: "201 HP",
            torque: "500 Nm",
            traction: "4x4",
            airbags: 7,
            listPrice: 50890000,
            brandBonus: 1300000,
            financingBonus: 1000000,
            bonusPrice: 48590000,
        },
            {
            name: "Fortuner SRX 4x4 AT TDI 2.8L Diesel",
            motor: "2.8L Turbo Di\u00e9sel",
            fuel: "Di\u00e9sel",
            transmission: "Autom\u00e1tica",
            consumptionMixed: "Mixto 12,0 km/l",
            power: "201 HP",
            torque: "500 Nm",
            traction: "4x4",
            airbags: 7,
            listPrice: 50890000,
            brandBonus: 1300000,
            financingBonus: 1000000,
            bonusPrice: 48590000,
        },
            {
            name: "Fortuner SRX 4x4 AT TDI 2.8L Diesel",
            motor: "2.8L Turbo Di\u00e9sel",
            fuel: "Di\u00e9sel",
            transmission: "Autom\u00e1tica",
            consumptionMixed: "Mixto 12,0 km/l",
            power: "201 HP",
            torque: "500 Nm",
            traction: "4x4",
            airbags: 7,
            listPrice: 51090000,
            brandBonus: 1000000,
            financingBonus: 1000000,
            bonusPrice: 49090000,
        },
            {
            name: "Fortuner SR5 4x4 MT TDI 2.8L Diesel",
            motor: "2.8L Turbo Di\u00e9sel",
            fuel: "Di\u00e9sel",
            transmission: "Mec\u00e1nica",
            consumptionMixed: "Mixto 12,0 km/l",
            power: "201 HP",
            torque: "420 Nm",
            traction: "4x4",
            airbags: 7,
            listPrice: 42890000,
            brandBonus: 1800000,
            financingBonus: 1300000,
            bonusPrice: 39790000,
        },
        ],
        slogan: "El modelo que buscabas, ahora m\u00e1s cerca que nunca",
        videoUrl: "CARACTER\u00cdSTICAS:",
        features: [
            {
            title: "Dise\u00f1o Din\u00e1mico",
            desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
            image: "/images/toyota/fortuner/caracteristicas/motores.jpg",
        },
            {
            title: "Conducci\u00f3n Eficiente",
            desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
            image: "/images/toyota/fortuner/caracteristicas/control-balanceo.jpg",
        },
            {
            title: "Tecnolog\u00edas Innovadoras",
            desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
            image: "/images/toyota/fortuner/caracteristicas/airbags.jpg",
        },
        ],
        gallery: [
            "/images/toyota/fortuner/galeria/1.jpg",
            "/images/toyota/fortuner/galeria/2.jpg",
            "/images/toyota/fortuner/galeria/3.jpg",
            "/images/toyota/fortuner/galeria/galeria_84023.jpg",
            "/images/toyota/fortuner/galeria/galeria_84161.jpg",
            "/images/toyota/fortuner/galeria/galeria_84234.jpg",
            "/images/toyota/fortuner/galeria/galeria_84339.jpg",
            "/images/toyota/fortuner/galeria/galeria_84477.jpg",
            "/images/toyota/fortuner/galeria/galeria_84619.jpg",
            "/images/toyota/fortuner/galeria/galeria_84750.jpg",
            "/images/toyota/fortuner/galeria/galeria_84846.jpg",
            "/images/toyota/fortuner/galeria/galeria_84955.jpg",
            "/images/toyota/fortuner/galeria/galeria_85188.jpg",
            "/images/toyota/fortuner/galeria/galeria_85310.jpg",
            "/images/toyota/fortuner/galeria/galeria_85447.jpg",
            "/images/toyota/fortuner/galeria/galeria_85566.jpg",
            "/images/toyota/fortuner/galeria/galeria_85826.jpg",
        ],
        desktopBanner: "/images/toyota/fortuner/banner/banner-web.jpg",
    },
    {
        id: "fortuner-gr-s",
        brand: "toyota",
        name: "Fortuner GR-S",
        category: "Gazoo Racing, SUV",
        price: 52290000,
        image: "/images/toyota/fortuner-gr-s/min-fortuner.png",
        vehicleType: "liviano",
        ivaIncluded: true,
        isHybrid: false,
        isElectric: false,
        isNew: false,
        versions: [
            {
            name: "Fortuner GR-S 4x4 2.8 AT",
            motor: "2.8L Turbo Di\u00e9sel",
            fuel: "Di\u00e9sel",
            transmission: "Autom\u00e1tica",
            consumptionMixed: "Mixto 11,8 km/L",
            power: "221 HP",
            torque: "550 Nm",
            traction: "4x4",
            airbags: 7,
            listPrice: 52890000,
            brandBonus: 0,
            financingBonus: 600000,
            bonusPrice: 52290000,
        },
            {
            name: "Fortuner GR-S 4x4 2.8 AT",
            motor: "2.8L Turbo Di\u00e9sel",
            fuel: "Di\u00e9sel",
            transmission: "Autom\u00e1tica",
            consumptionMixed: "Mixto 11,8 km/L",
            power: "221 HP",
            torque: "550 Nm",
            traction: "4x4",
            airbags: 7,
            listPrice: 53090000,
            brandBonus: 0,
            financingBonus: 600000,
            bonusPrice: 52490000,
        },
        ],
        slogan: "La tradici\u00f3n de innovar",
        videoUrl: "CARACTER\u00cdSTICAS:",
        features: [
            {
            title: "Dise\u00f1o Din\u00e1mico",
            desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
            image: "/images/toyota/fortuner-gr-s/caracteristicas/diseno-interior.png",
        },
            {
            title: "Conducci\u00f3n Eficiente",
            desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
            image: "/images/toyota/fortuner-gr-s/caracteristicas/performance.png",
        },
            {
            title: "Tecnolog\u00edas Innovadoras",
            desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
            image: "/images/toyota/fortuner-gr-s/caracteristicas/diseno-exterior.png",
        },
        ],
        gallery: [
            "/images/toyota/fortuner-gr-s/galeria/galeria_8598.jpg",
            "/images/toyota/fortuner-gr-s/galeria/galeria_8766.jpg",
            "/images/toyota/fortuner-gr-s/galeria/galeria_8888.jpg",
            "/images/toyota/fortuner-gr-s/galeria/galeria_9034.jpg",
            "/images/toyota/fortuner-gr-s/galeria/galeria_9225.jpg",
            "/images/toyota/fortuner-gr-s/galeria/galeria_9424.jpg",
            "/images/toyota/fortuner-gr-s/galeria/galeria_9616.jpg",
        ],
        desktopBanner: "/images/toyota/fortuner-gr-s/banner/desktop.jpg",
    },
    {
        id: "hilux",
        brand: "toyota",
        name: "Hilux",
        category: "Pick-Up",
        price: 33090000,
        image: "/images/toyota/hilux/min-hilux.png",
        vehicleType: "liviano",
        ivaIncluded: false,
        isHybrid: false,
        isElectric: false,
        isNew: false,
        versions: [
            {
            name: "Hilux 4x2 2.4 MT DX Euro VI",
            motor: "2.4L Diesel",
            fuel: "Di\u00e9sel",
            transmission: "Mec\u00e1nica",
            consumptionMixed: "Mixto 12,3 km/L",
            power: "148 HP",
            torque: "400 Nm",
            traction: "4x2",
            airbags: 7,
            listPrice: 33990000,
            brandBonus: 0,
            financingBonus: 500000,
            bonusPrice: 33490000,
        },
            {
            name: "Hilux 4x2 2.4 MT DX Euro VI",
            motor: "2.4L Diesel",
            fuel: "Di\u00e9sel",
            transmission: "Mec\u00e1nica",
            consumptionMixed: "Mixto 12,3 km/L",
            power: "148 HP",
            torque: "400 Nm",
            traction: "4x2",
            airbags: 7,
            listPrice: 33990000,
            brandBonus: 0,
            financingBonus: 500000,
            bonusPrice: 33490000,
        },
            {
            name: "Hilux 4x2 2.4 MT DX Euro VI",
            motor: "2.4L Diesel",
            fuel: "Di\u00e9sel",
            transmission: "Mec\u00e1nica",
            consumptionMixed: "Mixto 12,3 km/L",
            power: "148 HP",
            torque: "400 Nm",
            traction: "4x2",
            airbags: 7,
            listPrice: 33990000,
            brandBonus: 0,
            financingBonus: 500000,
            bonusPrice: 33490000,
        },
            {
            name: "Hilux 4x2 2.4 MT DX Euro VI",
            motor: "2.4L Diesel",
            fuel: "Di\u00e9sel",
            transmission: "Mec\u00e1nica",
            consumptionMixed: "Mixto 12,3 km/L",
            power: "148 HP",
            torque: "400 Nm",
            traction: "4x2",
            airbags: 7,
            listPrice: 33990000,
            brandBonus: 0,
            financingBonus: 500000,
            bonusPrice: 33490000,
        },
            {
            name: "Hilux 4x2 2.4 MT DX Euro VI TSS",
            motor: "2.4L Diesel",
            fuel: "Di\u00e9sel",
            transmission: "Mec\u00e1nica",
            consumptionMixed: "Mixto 12,3 km/L",
            power: "148 HP",
            torque: "400 Nm",
            traction: "4x2",
            airbags: 7,
            listPrice: 35790000,
            brandBonus: 0,
            financingBonus: 0,
            bonusPrice: 35790000,
        },
            {
            name: "Hilux 4X2 2.4 MT SR Euro VI",
            motor: "2.4L Diesel",
            fuel: "Di\u00e9sel",
            transmission: "Mec\u00e1nica",
            consumptionMixed: "Mixto 12,3 km/L",
            power: "148 HP",
            torque: "400 Nm",
            traction: "4x2",
            airbags: 7,
            listPrice: 34790000,
            brandBonus: 1400000,
            financingBonus: 300000,
            bonusPrice: 33090000,
        },
            {
            name: "Hilux 4x4 2.4 MT DX Euro VI",
            motor: "2.4L Diesel",
            fuel: "Di\u00e9sel",
            transmission: "Mec\u00e1nica",
            consumptionMixed: "Mixto 12,3 km/L",
            power: "148 HP",
            torque: "400 Nm",
            traction: "4x4",
            airbags: 7,
            listPrice: 38690000,
            brandBonus: 1000000,
            financingBonus: 500000,
            bonusPrice: 37190000,
        },
            {
            name: "Hilux 4x4 2.4 MT DX Euro VI",
            motor: "2.4L Diesel",
            fuel: "Di\u00e9sel",
            transmission: "Mec\u00e1nica",
            consumptionMixed: "Mixto 12,3 km/L",
            power: "148 HP",
            torque: "400 Nm",
            traction: "4x4",
            airbags: 7,
            listPrice: 38690000,
            brandBonus: 1000000,
            financingBonus: 500000,
            bonusPrice: 37190000,
        },
            {
            name: "Hilux 4x4 2.4 MT DX Euro VI TSS",
            motor: "2.4L Diesel",
            fuel: "Di\u00e9sel",
            transmission: "Mec\u00e1nica",
            consumptionMixed: "Mixto 12,3 km/L",
            power: "148 HP",
            torque: "400 Nm",
            traction: "4x4",
            airbags: 7,
            listPrice: 40490000,
            brandBonus: 0,
            financingBonus: 0,
            bonusPrice: 40490000,
        },
            {
            name: "Hilux 4x4 2.4 MT DX Euro VI",
            motor: "2.4L Diesel",
            fuel: "Di\u00e9sel",
            transmission: "Mec\u00e1nica",
            consumptionMixed: "Mixto 12,3 km/L",
            power: "148 HP",
            torque: "400 Nm",
            traction: "4x4",
            airbags: 7,
            listPrice: 38690000,
            brandBonus: 1000000,
            financingBonus: 500000,
            bonusPrice: 37190000,
        },
            {
            name: "Hilux 4x4 2.4 MT DX Euro VI TSS",
            motor: "2.4L Diesel",
            fuel: "Di\u00e9sel",
            transmission: "Mec\u00e1nica",
            consumptionMixed: "Mixto 12,3 km/L",
            power: "148 HP",
            torque: "400 Nm",
            traction: "4x4",
            airbags: 7,
            listPrice: 40490000,
            brandBonus: 0,
            financingBonus: 0,
            bonusPrice: 40490000,
        },
            {
            name: "Hilux 4x4 2.4 MT SR Euro VI",
            motor: "2.4L Diesel",
            fuel: "Di\u00e9sel",
            transmission: "Mec\u00e1nica",
            consumptionMixed: "Mixto 12,3 km/L",
            power: "148 HP",
            torque: "400 Nm",
            traction: "4x4",
            airbags: 7,
            listPrice: 41290000,
            brandBonus: 1000000,
            financingBonus: 300000,
            bonusPrice: 39990000,
        },
            {
            name: "Hilux 4x4 2.4 MT SR Euro VI",
            motor: "2.4L Diesel",
            fuel: "Di\u00e9sel",
            transmission: "Mec\u00e1nica",
            consumptionMixed: "Mixto 12,3 km/L",
            power: "148 HP",
            torque: "400 Nm",
            traction: "4x4",
            airbags: 7,
            listPrice: 41290000,
            brandBonus: 1000000,
            financingBonus: 300000,
            bonusPrice: 39990000,
        },
            {
            name: "Hilux 4X4 2.8 MT SR Euro VI",
            motor: "2.8L Diesel",
            fuel: "Di\u00e9sel",
            transmission: "Mec\u00e1nica",
            consumptionMixed: "Mixto 10,6 km/L",
            power: "201 HP",
            torque: "420 Nm",
            traction: "4x4",
            airbags: 7,
            listPrice: 45290000,
            brandBonus: 0,
            financingBonus: 500000,
            bonusPrice: 44790000,
        },
            {
            name: "Hilux 4X4 2.8 AT SRV Euro VI",
            motor: "2.8L Diesel",
            fuel: "Di\u00e9sel",
            transmission: "Autom\u00e1tica",
            consumptionMixed: "Mixto 10,6 km/L",
            power: "201 HP",
            torque: "500 Nm",
            traction: "4x4",
            airbags: 7,
            listPrice: 48590000,
            brandBonus: 1000000,
            financingBonus: 800000,
            bonusPrice: 46790000,
        },
            {
            name: "Hilux 4X4 2.8 AT SRV Euro VI",
            motor: "2.8L Diesel",
            fuel: "Di\u00e9sel",
            transmission: "Autom\u00e1tica",
            consumptionMixed: "Mixto 10,6 km/L",
            power: "201 HP",
            torque: "500 Nm",
            traction: "4x4",
            airbags: 7,
            listPrice: 48590000,
            brandBonus: 0,
            financingBonus: 800000,
            bonusPrice: 47790000,
        },
        ],
        slogan: "El modelo que buscabas, ahora m\u00e1s cerca que nunca",
        videoUrl: "CARACTER\u00cdSTICAS:",
        features: [
            {
            title: "Dise\u00f1o Din\u00e1mico",
            desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
            image: "/images/toyota/hilux/caracteristicas/diseno-robusto.jpg",
        },
            {
            title: "Conducci\u00f3n Eficiente",
            desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
            image: "/images/toyota/hilux/caracteristicas/seguridad.jpg",
        },
            {
            title: "Tecnolog\u00edas Innovadoras",
            desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
            image: "/images/toyota/hilux/caracteristicas/capacidad-carga.jpg",
        },
        ],
        gallery: [
            "/images/toyota/hilux/galeria/1.jpg",
            "/images/toyota/hilux/galeria/2.jpg",
            "/images/toyota/hilux/galeria/3.jpg",
            "/images/toyota/hilux/galeria/galeria_1017.jpg",
            "/images/toyota/hilux/galeria/galeria_1110.jpg",
            "/images/toyota/hilux/galeria/galeria_1183.jpg",
            "/images/toyota/hilux/galeria/galeria_1331.jpg",
            "/images/toyota/hilux/galeria/galeria_1403.jpg",
            "/images/toyota/hilux/galeria/galeria_1516.jpg",
            "/images/toyota/hilux/galeria/galeria_1659.jpg",
            "/images/toyota/hilux/galeria/galeria_1835.jpg",
            "/images/toyota/hilux/galeria/galeria_2096.jpg",
            "/images/toyota/hilux/galeria/galeria_2282.jpg",
            "/images/toyota/hilux/galeria/galeria_470.jpg",
            "/images/toyota/hilux/galeria/galeria_583.jpg",
            "/images/toyota/hilux/galeria/galeria_677.jpg",
            "/images/toyota/hilux/galeria/galeria_810.jpg",
            "/images/toyota/hilux/galeria/galeria_932.jpg",
        ],
        desktopBanner: "/images/toyota/hilux/banner/banner_280.jpg",
    },
    {
        id: "hilux-gr-s",
        brand: "toyota",
        name: "Hilux GR-S",
        category: "Gazoo Racing, Pick-Up",
        price: 52590000,
        image: "/images/toyota/hilux-gr-s/min-hilux-gr.webp",
        vehicleType: "liviano",
        ivaIncluded: false,
        isHybrid: false,
        isElectric: false,
        isNew: false,
        versions: [
            {
            name: "Hilux GR-S 4x4 2.8 AT",
            motor: "2.8L Turbo Di\u00e9sel",
            fuel: "Di\u00e9sel",
            transmission: "Autom\u00e1tica",
            consumptionMixed: "Mixto 11,8 km/L",
            power: "221 HP",
            torque: "550 Nm",
            traction: "4x4",
            airbags: 7,
            listPrice: 53190000,
            brandBonus: 0,
            financingBonus: 400000,
            bonusPrice: 52790000,
        },
            {
            name: "Hilux GR-S 4x4 2.8 AT",
            motor: "2.8L Turbo Di\u00e9sel",
            fuel: "Di\u00e9sel",
            transmission: "Autom\u00e1tica",
            consumptionMixed: "Mixto 11,8 km/L",
            power: "221 HP",
            torque: "550 Nm",
            traction: "4x4",
            airbags: 7,
            listPrice: 52990000,
            brandBonus: 0,
            financingBonus: 400000,
            bonusPrice: 52590000,
        },
        ],
        slogan: "HILUX GR-S",
        videoUrl: "CARACTER\u00cdSTICAS:",
        features: [
            {
            title: "Dise\u00f1o Din\u00e1mico",
            desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
            image: "/images/toyota/hilux-gr-s/caracteristicas/rendimiento.png",
        },
            {
            title: "Conducci\u00f3n Eficiente",
            desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
            image: "/images/toyota/hilux-gr-s/caracteristicas/diseno-interior.png",
        },
            {
            title: "Tecnolog\u00edas Innovadoras",
            desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
            image: "/images/toyota/hilux-gr-s/caracteristicas/diseno-exterior.png",
        },
        ],
        gallery: [
            "/images/toyota/hilux-gr-s/galeria/galeria_5044.png",
            "/images/toyota/hilux-gr-s/galeria/galeria_5221.png",
            "/images/toyota/hilux-gr-s/galeria/galeria_5505.png",
            "/images/toyota/hilux-gr-s/galeria/galeria_5803.png",
            "/images/toyota/hilux-gr-s/galeria/galeria_6021.png",
            "/images/toyota/hilux-gr-s/galeria/galeria_6251.png",
            "/images/toyota/hilux-gr-s/galeria/galeria_6431.png",
            "/images/toyota/hilux-gr-s/galeria/galeria_6524.jpg",
            "/images/toyota/hilux-gr-s/galeria/galeria_6619.jpg",
            "/images/toyota/hilux-gr-s/galeria/galeria_6808.png",
            "/images/toyota/hilux-gr-s/galeria/galeria_7047.png",
        ],
        desktopBanner: "/images/toyota/hilux-gr-s/banner/banner_4649.png",
    },
    {
        id: "land-cruiser-prado",
        brand: "toyota",
        name: "Land Cruiser Prado",
        category: "SUV",
        price: 62990000,
        image: "/images/toyota/land-cruiser-prado/min-land-prado.png",
        vehicleType: "liviano",
        ivaIncluded: true,
        isHybrid: false,
        isElectric: false,
        isNew: false,
        versions: [
            {
            name: "VX-L 2.8",
            motor: "2.8L Turbo Di\u00e9sel",
            fuel: "Di\u00e9sel",
            transmission: "Autom\u00e1tica",
            power: "201 HP",
            torque: "500 Nm",
            traction: "4x4",
            airbags: 8,
            listPrice: 74990000,
            brandBonus: 3000000,
            financingBonus: 500000,
            bonusPrice: 71490000,
        },
            {
            name: "VX-L 2.8",
            motor: "2.8L Turbo Di\u00e9sel",
            fuel: "Di\u00e9sel",
            transmission: "Autom\u00e1tica",
            power: "201 HP",
            torque: "500 Nm",
            traction: "4x4",
            airbags: 8,
            listPrice: 74990000,
            brandBonus: 3000000,
            financingBonus: 500000,
            bonusPrice: 71490000,
        },
            {
            name: "WX ADVENTURE 2.8",
            motor: "2.8L Turbo Di\u00e9sel",
            fuel: "Di\u00e9sel",
            transmission: "Autom\u00e1tica",
            power: "201 HP",
            torque: "500 Nm",
            traction: "4x4",
            airbags: 8,
            listPrice: 66990000,
            brandBonus: 3500000,
            financingBonus: 500000,
            bonusPrice: 62990000,
        },
        ],
        slogan: "El modelo que buscabas, ahora m\u00e1s cerca que nunca",
        videoUrl: "CARACTER\u00cdSTICAS:",
        features: [
            {
            title: "Dise\u00f1o Din\u00e1mico",
            desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
            image: "/images/toyota/land-cruiser-prado/caracteristicas/airbags.png",
        },
            {
            title: "Conducci\u00f3n Eficiente",
            desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
            image: "/images/toyota/land-cruiser-prado/caracteristicas/nuevo-diseno.png",
        },
            {
            title: "Tecnolog\u00edas Innovadoras",
            desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
            image: "/images/toyota/land-cruiser-prado/caracteristicas/4x4.png",
        },
        ],
        gallery: [
            "/images/toyota/land-cruiser-prado/galeria/galeria_90766.jpg",
            "/images/toyota/land-cruiser-prado/galeria/galeria_90910.jpg",
            "/images/toyota/land-cruiser-prado/galeria/galeria_91088.jpg",
            "/images/toyota/land-cruiser-prado/galeria/galeria_91202.jpg",
            "/images/toyota/land-cruiser-prado/galeria/galeria_91313.jpg",
            "/images/toyota/land-cruiser-prado/galeria/galeria_91419.jpg",
            "/images/toyota/land-cruiser-prado/galeria/galeria_91519.jpg",
            "/images/toyota/land-cruiser-prado/galeria/galeria_91623.jpg",
            "/images/toyota/land-cruiser-prado/galeria/galeria_91779.png",
            "/images/toyota/land-cruiser-prado/galeria/galeria_91903.png",
            "/images/toyota/land-cruiser-prado/galeria/galeria_92075.png",
            "/images/toyota/land-cruiser-prado/galeria/galeria_92331.png",
            "/images/toyota/land-cruiser-prado/galeria/galeria_92558.png",
            "/images/toyota/land-cruiser-prado/galeria/galeria_92696.png",
            "/images/toyota/land-cruiser-prado/galeria/galeria_92832.png",
            "/images/toyota/land-cruiser-prado/galeria/galeria_92944.png",
            "/images/toyota/land-cruiser-prado/galeria/galeria_93093.png",
            "/images/toyota/land-cruiser-prado/galeria/galeria_93265.png",
            "/images/toyota/land-cruiser-prado/galeria/galeria_93399.png",
        ],
        desktopBanner: "/images/toyota/land-cruiser-prado/banner/banner-web.jpg",
    },
    {
        id: "new-yaris-sedan",
        brand: "toyota",
        name: "Yaris Sedan",
        category: "Sedán",
        price: 13790000,
        image: "/images/toyota/new-yaris-sedan/min_yaris.png",
        vehicleType: "liviano",
        ivaIncluded: true,
        isHybrid: false,
        isElectric: false,
        isNew: false,
        versions: [
            {
            name: "New Yaris Sed\u00e1n i MT",
            motor: "1.5L",
            fuel: "Gasolina",
            transmission: "Mec\u00e1nica",
            consumptionMixed: "Mixto 16,9 km/l",
            power: "105 HP",
            torque: "138 NM",
            traction: "4x2",
            airbags: 6,
            listPrice: 14990000,
            brandBonus: 600000,
            financingBonus: 600000,
            bonusPrice: 13790000,
        },
            {
            name: "New Yaris Sed\u00e1n E MT",
            motor: "1.5L",
            fuel: "Gasolina",
            transmission: "Mec\u00e1nica",
            consumptionMixed: "Mixto 16,9 km/l",
            power: "105 HP",
            torque: "138 NM",
            traction: "4x2",
            airbags: 6,
            listPrice: 16490000,
            brandBonus: 400000,
            financingBonus: 200000,
            bonusPrice: 15890000,
        },
            {
            name: "New Yaris Sed\u00e1n E CVT",
            motor: "1.5L",
            fuel: "Gasolina",
            transmission: "CVT",
            consumptionMixed: "Mixto 16,2 km/l",
            power: "105 HP",
            torque: "138 NM",
            traction: "4x2",
            airbags: 6,
            listPrice: 17490000,
            brandBonus: 0,
            financingBonus: 0,
            bonusPrice: 17490000,
        },
        ],
        slogan: "El modelo que buscabas, ahora m\u00e1s cerca que nunca",
        videoUrl: "CARACTER\u00cdSTICAS:",
        features: [
            {
            title: "Dise\u00f1o Din\u00e1mico",
            desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
            image: "/images/toyota/new-yaris-sedan/caracteristicas/airbags.jpg",
        },
            {
            title: "Conducci\u00f3n Eficiente",
            desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
            image: "/images/toyota/new-yaris-sedan/caracteristicas/vsc.jpg",
        },
            {
            title: "Tecnolog\u00edas Innovadoras",
            desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
            image: "/images/toyota/new-yaris-sedan/caracteristicas/abs.jpg",
        },
        ],
        gallery: [
            "/images/toyota/new-yaris-sedan/galeria/1.jpg",
            "/images/toyota/new-yaris-sedan/galeria/2.jpg",
            "/images/toyota/new-yaris-sedan/galeria/3.jpg",
            "/images/toyota/new-yaris-sedan/galeria/galeria_95933.jpg",
            "/images/toyota/new-yaris-sedan/galeria/galeria_96001.jpg",
            "/images/toyota/new-yaris-sedan/galeria/galeria_96137.jpg",
            "/images/toyota/new-yaris-sedan/galeria/galeria_96249.jpg",
        ],
        desktopBanner: "/images/toyota/new-yaris-sedan/banner/banner-web.jpg",
    },
    {
        id: "raize",
        brand: "toyota",
        name: "Raize",
        category: "SUV",
        price: 11990000,
        image: "/images/toyota/raize/min-raize.png",
        vehicleType: "liviano",
        ivaIncluded: true,
        isHybrid: false,
        isElectric: false,
        isNew: false,
        versions: [
            {
            name: "Raize i MT",
            motor: "1.2L",
            fuel: "Gasolina",
            transmission: "Mec\u00e1nica",
            consumptionMixed: "Mixto 18,9 km/l",
            power: "87 HP",
            torque: "113 NM",
            traction: "4x2",
            airbags: 2,
            listPrice: 13990000,
            brandBonus: 1400000,
            financingBonus: 600000,
            bonusPrice: 11990000,
        },
            {
            name: "Raize i MT",
            motor: "1.2L",
            fuel: "Gasolina",
            transmission: "Mec\u00e1nica",
            consumptionMixed: "Mixto 18,9 km/l",
            power: "87 HP",
            torque: "113 NM",
            traction: "4x2",
            airbags: 2,
            listPrice: 13990000,
            brandBonus: 1400000,
            financingBonus: 600000,
            bonusPrice: 11990000,
        },
            {
            name: "Raize E MT",
            motor: "1.2L",
            fuel: "Gasolina",
            transmission: "Mec\u00e1nica",
            consumptionMixed: "Mixto 18,9 km/l",
            power: "87 HP",
            torque: "113 NM",
            traction: "4x2",
            airbags: 2,
            listPrice: 15990000,
            brandBonus: 600000,
            financingBonus: 450000,
            bonusPrice: 14940000,
        },
            {
            name: "Raize E MT",
            motor: "1.2L",
            fuel: "Gasolina",
            transmission: "Mec\u00e1nica",
            consumptionMixed: "Mixto 18,9 km/l",
            power: "87 HP",
            torque: "113 NM",
            traction: "4x2",
            airbags: 2,
            listPrice: 15990000,
            brandBonus: 600000,
            financingBonus: 450000,
            bonusPrice: 14940000,
        },
            {
            name: "Raize E CVT",
            motor: "1.2L",
            fuel: "Gasolina",
            transmission: "CVT",
            consumptionMixed: "Mixto 17,4 km/l",
            power: "87 HP",
            torque: "113 NM",
            traction: "4x2",
            airbags: 2,
            listPrice: 16990000,
            brandBonus: 1200000,
            financingBonus: 250000,
            bonusPrice: 15540000,
        },
            {
            name: "Raize E CVT",
            motor: "1.2L",
            fuel: "Gasolina",
            transmission: "CVT",
            consumptionMixed: "Mixto 17,4 km/l",
            power: "87 HP",
            torque: "113 NM",
            traction: "4x2",
            airbags: 2,
            listPrice: 16990000,
            brandBonus: 1200000,
            financingBonus: 250000,
            bonusPrice: 15540000,
        },
            {
            name: "Raize G CVT",
            motor: "1.2L",
            fuel: "Gasolina",
            transmission: "CVT",
            consumptionMixed: "Mixto 17,4 km/l",
            power: "87 HP",
            torque: "113 NM",
            traction: "4x2",
            airbags: 6,
            listPrice: 18490000,
            brandBonus: 300000,
            financingBonus: 500000,
            bonusPrice: 17690000,
        },
        ],
        slogan: "F\u00e1cil de conducir, simple de disfrutar",
        videoUrl: "CARACTER\u00cdSTICAS:",
        features: [
            {
            title: "Dise\u00f1o Din\u00e1mico",
            desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
            image: "/images/toyota/raize/caracteristicas/airbags.jpg",
        },
            {
            title: "Conducci\u00f3n Eficiente",
            desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
            image: "/images/toyota/raize/caracteristicas/HAC.png",
        },
            {
            title: "Tecnolog\u00edas Innovadoras",
            desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
            image: "/images/toyota/raize/caracteristicas/motor.jpg",
        },
        ],
        gallery: [
            "/images/toyota/raize/galeria/1.jpg",
            "/images/toyota/raize/galeria/2.jpg",
            "/images/toyota/raize/galeria/3.jpg",
            "/images/toyota/raize/galeria/galeria_78210.jpg",
            "/images/toyota/raize/galeria/galeria_78354.jpg",
            "/images/toyota/raize/galeria/galeria_78502.jpg",
            "/images/toyota/raize/galeria/galeria_78614.jpg",
        ],
        desktopBanner: "/images/toyota/raize/banner/banner-web.jpg",
    },
    {
        id: "rav4-hybrid",
        brand: "toyota",
        name: "RAV4",
        category: "SUV",
        price: 26490000,
        image: "/images/toyota/rav4-hybrid/min-rav4-hibrido.webp",
        vehicleType: "liviano",
        ivaIncluded: true,
        isHybrid: false,
        isElectric: false,
        isNew: false,
        versions: [
            {
            name: "All New Rav4 LE 2.0 4x2 CVT",
            motor: "2.0L",
            fuel: "Gasolina",
            transmission: "CVT",
            consumptionMixed: "Mixto 14,3 km/l",
            power: "170 HP",
            torque: "203 NM",
            traction: "4x2",
            airbags: 7,
            listPrice: 27390000,
            brandBonus: 900000,
            financingBonus: 0,
            bonusPrice: 26490000,
        },
            {
            name: "All New Rav4 XLE 2.0 4x2 CVT",
            motor: "2.0L",
            fuel: "Gasolina",
            transmission: "CVT",
            consumptionMixed: "Mixto 14,3 km/l",
            power: "170 HP",
            torque: "203 NM",
            traction: "4x2",
            airbags: 7,
            listPrice: 30390000,
            brandBonus: 0,
            financingBonus: 0,
            bonusPrice: 30390000,
        },
            {
            name: "All New Rav4 LE 2.0 4x2 CVT",
            motor: "2.0L",
            fuel: "Gasolina",
            transmission: "CVT",
            consumptionMixed: "Mixto 14,3 km/l",
            power: "170 HP",
            torque: "203 NM",
            traction: "4x2",
            airbags: 7,
            listPrice: 28990000,
            brandBonus: 0,
            financingBonus: 1000000,
            bonusPrice: 27990000,
        },
            {
            name: "All New Rav4 LE 2.0 4x4 CVT",
            motor: "2.0L",
            fuel: "Gasolina",
            transmission: "CVT",
            consumptionMixed: "Mixto 13,8 km/l",
            power: "170 HP",
            torque: "203 NM",
            traction: "4x4",
            airbags: 7,
            listPrice: 29990000,
            brandBonus: 0,
            financingBonus: 1000000,
            bonusPrice: 28990000,
        },
            {
            name: "All New Rav4 XLE 2.0 4x2 CVT",
            motor: "2.0L",
            fuel: "Gasolina",
            transmission: "CVT",
            consumptionMixed: "Mixto 14,3 km/l",
            power: "170 HP",
            torque: "203 NM",
            traction: "4x2",
            airbags: 7,
            listPrice: 32490000,
            brandBonus: 0,
            financingBonus: 500000,
            bonusPrice: 31990000,
        },
        ],
        slogan: "RAV4 como nunca antes",
        videoUrl: "CARACTER\u00cdSTICAS:",
        features: [
            {
            title: "Dise\u00f1o Din\u00e1mico",
            desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
            image: "/images/toyota/rav4-hybrid/caracteristicas/version-adventure.jpg",
        },
            {
            title: "Conducci\u00f3n Eficiente",
            desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
            image: "/images/toyota/rav4-hybrid/caracteristicas/tecno-hibrida.jpg",
        },
            {
            title: "Tecnolog\u00edas Innovadoras",
            desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
            image: "/images/toyota/rav4-hybrid/caracteristicas/diseno-inspirador.jpg",
        },
        ],
        gallery: [
            "/images/toyota/rav4-hybrid/galeria/galeria_60263.jpg",
            "/images/toyota/rav4-hybrid/galeria/galeria_60512.jpg",
            "/images/toyota/rav4-hybrid/galeria/galeria_61897.jpg",
            "/images/toyota/rav4-hybrid/galeria/galeria_71138.jpg",
            "/images/toyota/rav4-hybrid/galeria/galeria_71206.jpg",
            "/images/toyota/rav4-hybrid/galeria/galeria_71265.jpg",
            "/images/toyota/rav4-hybrid/galeria/galeria_71340.jpg",
            "/images/toyota/rav4-hybrid/galeria/galeria_71446.jpg",
            "/images/toyota/rav4-hybrid/galeria/galeria_71582.jpg",
            "/images/toyota/rav4-hybrid/galeria/galeria_71618.jpg",
            "/images/toyota/rav4-hybrid/galeria/galeria_71700.jpg",
            "/images/toyota/rav4-hybrid/galeria/galeria_71777.jpg",
            "/images/toyota/rav4-hybrid/galeria/galeria_71845.jpg",
            "/images/toyota/rav4-hybrid/galeria/galeria_71943.jpg",
            "/images/toyota/rav4-hybrid/galeria/galeria_72030.jpg",
            "/images/toyota/rav4-hybrid/galeria/galeria_72165.jpg",
        ],
        desktopBanner: "/images/toyota/rav4-hybrid/banner/banner-web.jpg",
    },
    {
        id: "yaris-cross-hybrid",
        brand: "toyota",
        name: "Yaris Cross H\u00edbrido",
        category: "Híbrido, SUV",
        price: 21790000,
        image: "/images/toyota/yaris-cross-hybrid/min-yaris-cross-hybrid.png",
        vehicleType: "liviano",
        ivaIncluded: true,
        isHybrid: true,
        isElectric: false,
        isNew: false,
        versions: [
            {
            name: "Yaris Cross XI 1.5 H\u00edbrido CVT",
            motor: "1.5L H\u00edbrido",
            fuel: "H\u00edbrido",
            transmission: "CVT",
            power: "110 HP",
            torque: "141 Nm",
            traction: "4x2",
            airbags: 6,
            listPrice: 24590000,
            brandBonus: 2000000,
            financingBonus: 800000,
            bonusPrice: 21790000,
        },
            {
            name: "Yaris Cross XG 1.5 H\u00edbrido CVT",
            motor: "1.5L H\u00edbrido",
            fuel: "H\u00edbrido",
            transmission: "CVT",
            power: "110 HP",
            torque: "141 Nm",
            traction: "4x2",
            airbags: 6,
            listPrice: 25490000,
            brandBonus: 0,
            financingBonus: 600000,
            bonusPrice: 24890000,
        },
        ],
        slogan: "El modelo que buscabas, ahora m\u00e1s cerca que nunca",
        videoUrl: "CARACTER\u00cdSTICAS:",
        features: [
            {
            title: "Dise\u00f1o Din\u00e1mico",
            desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
            image: "/images/toyota/yaris-cross-hybrid/caracteristicas/motores.jpg",
        },
            {
            title: "Conducci\u00f3n Eficiente",
            desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
            image: "/images/toyota/yaris-cross-hybrid/caracteristicas/YarisCross_Lifestyle_Photo7.2e16d0ba.fill-565x300.jpg",
        },
            {
            title: "Tecnolog\u00edas Innovadoras",
            desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
            image: "/images/toyota/yaris-cross-hybrid/caracteristicas/conectividad.jpg",
        },
        ],
        gallery: [
            "/images/toyota/yaris-cross-hybrid/galeria/1.jpg",
            "/images/toyota/yaris-cross-hybrid/galeria/2.jpg",
            "/images/toyota/yaris-cross-hybrid/galeria/3.jpg",
            "/images/toyota/yaris-cross-hybrid/galeria/galeria_66097.jpg",
            "/images/toyota/yaris-cross-hybrid/galeria/galeria_66273.jpg",
            "/images/toyota/yaris-cross-hybrid/galeria/galeria_66360.jpg",
            "/images/toyota/yaris-cross-hybrid/galeria/galeria_66439.jpg",
            "/images/toyota/yaris-cross-hybrid/galeria/galeria_66568.jpg",
            "/images/toyota/yaris-cross-hybrid/galeria/galeria_66644.jpg",
        ],
        desktopBanner: "/images/toyota/yaris-cross-hybrid/banner/banner_65940.jpg",
    },
    {
        id: "yaris-gr",
        brand: "toyota",
        name: "Yaris GR",
        category: "Gazoo Racing, Hatchback",
        price: 54990000,
        image: "/images/toyota/yaris-gr/min-yarisgr.png",
        vehicleType: "liviano",
        ivaIncluded: true,
        isHybrid: false,
        isElectric: false,
        isNew: false,
        versions: [
            {
            name: "GR Yaris 1.6 MT",
            motor: "1.6L Turbo",
            fuel: "Gasolina",
            transmission: "Mec\u00e1nica",
            power: "280 HP",
            torque: "390 Nm",
            traction: "AWD",
            airbags: 8,
            listPrice: 54990000,
            brandBonus: 0,
            financingBonus: 0,
            bonusPrice: 54990000,
        },
            {
            name: "GR Yaris 1.6 AT",
            motor: "1.6L Turbo",
            fuel: "Gasolina",
            transmission: "Autom\u00e1tica",
            power: "280 HP",
            torque: "390 Nm",
            traction: "AWD",
            airbags: 8,
            listPrice: 56990000,
            brandBonus: 0,
            financingBonus: 0,
            bonusPrice: 56990000,
        },
        ],
        slogan: "Nuevo GR Yaris",
        videoUrl: "CARACTER\u00cdSTICAS:",
        features: [
            {
            title: "Dise\u00f1o Din\u00e1mico",
            desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
            image: "/images/toyota/yaris-gr/caracteristicas/motor.jpg",
        },
            {
            title: "Conducci\u00f3n Eficiente",
            desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
            image: "/images/toyota/yaris-gr/caracteristicas/gr-four.jpg",
        },
            {
            title: "Tecnolog\u00edas Innovadoras",
            desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
            image: "/images/toyota/yaris-gr/caracteristicas/transmision.jpg",
        },
        ],
        gallery: [
            "/images/toyota/yaris-gr/galeria/Sin_titulo-6_Mesa_de_trabajo_1-08.original.jpg",
            "/images/toyota/yaris-gr/galeria/Sin_titulo-6_Mesa_de_trabajo_1-12.original.jpg",
            "/images/toyota/yaris-gr/galeria/principal-gr.jpg",
            "/images/toyota/yaris-gr/galeria/segunda-gr.jpg",
            "/images/toyota/yaris-gr/galeria/tercera-gr.jpg",
            "/images/toyota/yaris-gr/galeria/yaris-gr-interior-3.jpg",
            "/images/toyota/yaris-gr/galeria/yaris-gr-interior-4.jpg",
            "/images/toyota/yaris-gr/galeria/yaris-gr-interior-5.jpg",
            "/images/toyota/yaris-gr/galeria/yaris-gr-interior.jpg",
        ],
        desktopBanner: "/images/toyota/yaris-gr/banner/banner.png",
    },
    {
        id: "yaris-sedan-hibrido",
        brand: "toyota",
        name: "Yaris Sedan H\u00edbrido",
        category: "Híbrido, Sedán",
        price: 21390000,
        image: "/images/toyota/yaris-sedan-hibrido/min-yaris-sedan-hibrido.png",
        vehicleType: "liviano",
        ivaIncluded: true,
        isHybrid: true,
        isElectric: false,
        isNew: false,
        versions: [
            {
            name: "New Yaris Sedan HEV 1.5 AT G",
            motor: "1.5L H\u00edbrido",
            fuel: "H\u00edbrido",
            transmission: "CVT",
            consumptionMixed: "Mixto 21,3 km/L",
            power: "101 HP",
            traction: "4x2",
            airbags: 6,
            listPrice: 21990000,
            brandBonus: 0,
            financingBonus: 600000,
            bonusPrice: 21390000,
        },
        ],
        slogan: "El modelo que buscabas, ahora m\u00e1s cerca que nunca",
        videoUrl: "CARACTER\u00cdSTICAS:",
        features: [
            {
            title: "Dise\u00f1o Din\u00e1mico",
            desc: "Dise\u00f1o hecho a la medida de tus deseos y necesidades.",
            image: "/images/toyota/yaris-sedan-hibrido/caracteristicas/airbags.jpg",
        },
            {
            title: "Conducci\u00f3n Eficiente",
            desc: "Din\u00e1mica y eficiencia excepcional en su conducci\u00f3n.",
            image: "/images/toyota/yaris-sedan-hibrido/caracteristicas/vsc.jpg",
        },
            {
            title: "Tecnolog\u00edas Innovadoras",
            desc: "Equipado con las \u00faltimas innovaciones para el d\u00eda a d\u00eda.",
            image: "/images/toyota/yaris-sedan-hibrido/caracteristicas/abs.jpg",
        },
        ],
        gallery: [
            "/images/toyota/yaris-sedan-hibrido/galeria/34_FRONTAL_de_tamano_grande.original.jpg",
            "/images/toyota/yaris-sedan-hibrido/galeria/34_TRASERA_de_tamano_grande.original.jpg",
            "/images/toyota/yaris-sedan-hibrido/galeria/FRONTAL_LUCES_ENCENDIDAS_de_tamano_grande.original.jpg",
            "/images/toyota/yaris-sedan-hibrido/galeria/LATERAL_COPILOTO_de_tamano_grande.original.jpg",
            "/images/toyota/yaris-sedan-hibrido/galeria/OK7749_de_tamano_grande.original.jpg",
            "/images/toyota/yaris-sedan-hibrido/galeria/OK8091_de_tamano_grande.original.jpg",
            "/images/toyota/yaris-sedan-hibrido/galeria/ok7773_de_tamano_grande.original.jpg",
        ],
        desktopBanner: "/images/toyota/yaris-sedan-hibrido/banner/banner_home_-_1200x420.max-1200x425.jpg",
    },
];
