import { Vehicle } from './types';

export const VOLKSWAGEN_MODELS: Vehicle[] = [
    {
        id: 'polo-track',
        brand: 'volkswagen',
        name: 'Polo Track',
        category: 'Hatchback',
        price: 11690000,
        image: '/images/volkswagen/polo-track.webp',
        isHybrid: false,
        isNew: true,
        slogan: 'Tu primer Volkswagen',
    },
    {
        id: 'polo',
        brand: 'volkswagen',
        name: 'Polo',
        category: 'Hatchback',
        price: 14590000,
        image: '/images/volkswagen/polo.webp',
        isHybrid: false,
        isNew: false,
        slogan: 'Inspiración en cada detalle',
    },
    {
        id: 'virtus',
        brand: 'volkswagen',
        name: 'Virtus',
        category: 'Sedán',
        price: 15290000,
        image: '/images/volkswagen/virtus.webp',
        isHybrid: false,
        isNew: true,
        slogan: 'Eleva tu camino',
    },
    {
        id: 'jetta',
        brand: 'volkswagen',
        name: 'Nuevo Jetta',
        category: 'Sedán',
        price: 19990000,
        image: '/images/volkswagen/nuevo jetta.webp',
        isHybrid: false,
        isNew: true,
        slogan: 'El clásico renovado',
    },
    {
        id: 't-cross',
        brand: 'volkswagen',
        name: 'T-Cross',
        category: 'SUV',
        price: 17490000,
        image: '/images/volkswagen/t-cross.webp',
        isHybrid: false,
        isNew: true,
        slogan: 'Tu vida en modo T-Cross',
    },
    {
        id: 'taos',
        brand: 'volkswagen',
        name: 'Taos',
        category: 'SUV',
        price: 23990000,
        image: '/images/volkswagen/taos.webp',
        isHybrid: false,
        isNew: false,
        slogan: 'Brillante en cada detalle',
    },
    {
        id: 'tiguan',
        brand: 'volkswagen',
        name: 'Tiguan',
        category: 'SUV',
        price: 27990000,
        image: '/images/volkswagen/tiguan.webp',
        isHybrid: false,
        isNew: false,
        slogan: 'Espacio para tus sueños',
    },
    {
        id: 'nuevo-tiguan',
        brand: 'volkswagen',
        name: 'Nuevo Tiguan',
        category: 'SUV',
        price: 32990000,
        image: '/images/volkswagen/ Nuevo Tiguan.webp',
        isHybrid: false,
        isNew: true,
        slogan: 'La evolución de un icono',
    },
    {
        id: 'atlas',
        brand: 'volkswagen',
        name: 'Atlas',
        category: 'SUV',
        price: 44990000,
        image: '/images/volkswagen/atlas.webp',
        isHybrid: false,
        isNew: false,
        slogan: 'Poder en gran escala',
    },
    {
        id: 'nuevo-tera',
        brand: 'volkswagen',
        name: 'Nuevo Tera',
        category: 'SUV',
        price: 15990000,
        image: '/images/volkswagen/Nuevo Tera.webp',
        isHybrid: false,
        isNew: true,
        slogan: 'Libertad sin límites',
    },
    {
        id: 'saveiro-cs',
        brand: 'volkswagen',
        name: 'Saveiro CS',
        category: 'Pick-up',
        price: 12990000,
        image: '/images/volkswagen/saveiro cs.webp',
        isHybrid: false,
        isNew: false,
        slogan: 'Tu compañero de trabajo',
    },
    {
        id: 'saveiro-dc',
        brand: 'volkswagen',
        name: 'Saveiro DC',
        category: 'Pick-up',
        price: 14490000,
        image: '/images/volkswagen/saveiro dc.webp',
        isHybrid: false,
        isNew: false,
        slogan: 'Versatilidad total',
    },
    {
        id: 'amarok',
        brand: 'volkswagen',
        name: 'Amarok',
        category: 'Pick-up',
        price: 31990000,
        image: '/images/volkswagen/Nueva Amarok.webp',
        isHybrid: false,
        isNew: true,
        slogan: 'Potencia sin límites',
    },
    {
        id: 'caravelle',
        brand: 'volkswagen',
        name: 'Nueva Caravelle',
        category: 'Van',
        price: 38990000,
        image: '/images/volkswagen/Nueva Caravelle.webp',
        isHybrid: false,
        isNew: true,
        slogan: 'Transporte de clase mundial',
    },
    {
        id: 'transporter',
        brand: 'volkswagen',
        name: 'Nuevo Transporter',
        category: 'Furgón',
        price: 34990000,
        image: '/images/volkswagen/Nuevo Transporter.png',
        isHybrid: false,
        isNew: true,
        slogan: 'Eficiencia para tu negocio',
    }
];
